### ISSUE TITLE
Crash when gallery image is shared with the Commons app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#668] opened 2017-05-21 11:46 UTC
From the stock gallery I shared to Commons.
The image loaded fullscreen, but surprisingly the UI did not load anything else.
Killing Commons by swiping it was not enough to fix the problem, I had to force-stop it in Settings→Apps

**Comment by misaochan** [comment] 2017-05-23 15:35
@nicolas-raoul does this happen all the time for you, or just once?

Sorry, I am going to be in a plane most of tomorrow so can't check it :(

**Comment by nicolas-raoul** [comment] 2017-05-23 15:43
It happened 3 times, among 26 uploads.

**Comment by misaochan** [comment] 2017-05-23 18:48
Wow, that is pretty bad. 

Do you guys think we should revert to the last stable version for production (2.2.2)? It will be missing all the improvements we made over the weekend but it might be needed if lots of people aren't able to upload. Please help test if you can and provide feedback. 

@nicolas-raoul do you think you could do the revert for production if needed? I will be flying/ transiting till Thursday so I may not be able to access the internet. I'm in Zurich airport now, leaving soon. 

We can probably leave the beta on 2.4 since anyone who really needs to will be able to drop out of beta. 

Thanks!

**Comment by VojtechDostal** [comment] 2017-05-23 19:03
This just happened to me too. There was an android update in the morning, or maybe just Google Play's update. Whatever it was, I couldnt open the Commons app today (it said: "app not installed"). So I uninstalled and installed the app again, it now works, but when I choose a picture to upload it just shows on full-screen. When I try to do this repeatedly, or try to click here an there, it often causes the app to crash.

I don't mind keeping it in beta, as soon as we will work on this in a matter of days/few weeks max. If it takes more then let's revert to the stable version.

**Comment by tobias47n9e** [comment] 2017-05-23 21:04
Couldn't reproduce the issue today trying a few different Android versions in the emulator. Anyone have steps that always lead to the issue?

**Comment by nicolas-raoul** [comment] 2017-05-24 03:25
@VojtechDostal Would you mind repeating the full-screen bug while taking the log with adb logcat, and sending us the log? Thanks a lot!
Same for the crashes if possible, as a new issue :-)

**Comment by VojtechDostal** [comment] 2017-05-24 08:56
OK, will do but not before today evening. Which category of logs in Android Studio do you want me to send? I can choose several options from the rollup. thanks

**Comment by nicolas-raoul** [comment] 2017-05-24 09:31
Everything? :-)
If it is too big you can post to pastebin.

**Comment by misaochan** [comment] 2017-05-25 02:26
I reverted production to the latest stable version (2.2.2). Left 2.4 in beta, so those who aren't having issues or want to test the new features can remain in 2.4, while those who are having issues can opt out of beta for the time being.

Hopefully we'll find a fix for 2.4 soon.

**Comment by VojtechDostal** [comment] 2017-05-25 06:41
I cannot reproduce the problem I had yesterday. I will keep trying.

**Comment by misaochan** [comment] 2017-05-26 10:56
@nicolas-raoul Are you able to reproduce the issue with 2.4? If you are, could you post the logs? Thanks!

**Comment by misaochan** [comment] 2017-05-26 10:57
There is a crash report, not sure if it's the same bug:

```
USER_COMMENT=Tried to share two pictures with the Wikimedia Commons app
ANDROID_VERSION=7.1.1
APP_VERSION_NAME=2.4
BRAND=OnePlus
PHONE_MODEL=ONEPLUS A3003
CUSTOM_DATA=
STACK_TRACE=java.lang.ClassCastException: com.facebook.drawee.view.SimpleDraweeView cannot be cast to fr.free.nrw.commons.MediaWikiImageView
at fr.free.nrw.commons.upload.MultipleUploadListFragment$PhotoDisplayAdapter.getView(MultipleUploadListFragment.java:82)
at android.widget.AbsListView.obtainView(AbsListView.java:2379)
at android.widget.GridView.onMeasure(GridView.java:1065)
at android.view.View.measure(View.java:19955)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
at android.view.View.measure(View.java:19955)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:19955)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
at android.view.View.measure(View.java:19955)
at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
at android.view.View.measure(View.java:19955)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
at android.view.View.measure(View.java:19955)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
at android.view.View.measure(View.java:19955)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:19955)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
at android.view.View.measure(View.java:19955)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
at android.view.View.measure(View.java:19955)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2309)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1392)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1645)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6432)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
at android.view.Choreographer.doCallbacks(Choreographer.java:686)
at android.view.Choreographer.doFrame(Choreographer.java:621)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6290)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by nicolas-raoul** [comment] 2017-05-26 10:59
Sorry I haven't had time to try (_ _)

**Comment by misaochan** [comment] 2017-05-26 14:25
Got 2 more crash reports similar to the one above. I think that is quite clearly the source of the issue, or at least one of the sources.

**Comment by misaochan** [comment] 2017-05-26 14:27
Oh, I think that portion of MultipleUploadListFragment.java was part of @dbrant 's patch, haha. :)

**Comment by dbrant** [comment] 2017-05-26 14:49
D'oh!  Will look into it asap.

**Comment by dbrant** [comment] 2017-05-26 17:44
Should be fixed via #681.

**Comment by misaochan** [comment] 2017-05-27 06:47
Thanks @dbrant ! Will push to beta ASAP. In the meantime, if anyone could help test the current master branch and see if it's still crashing for them, that would be a huge help. :)

**Comment by misaochan** [comment] 2017-05-27 14:49
v 2.4.1 pushed to beta, if anyone is still having issues with this crash please let us know.

**Comment by misaochan** [comment] 2017-05-30 06:25
Anyone? Will close issue otherwise.

**Comment by VojtechDostal** [comment] 2017-05-30 09:24
No problem here.

**Comment by tobias47n9e** [comment] 2017-05-30 10:06
It works for me. A seperate issue to implement some upload tests would be a good idea though. We should never accidentally break our main features.

**Comment by misaochan** [comment] 2017-05-30 10:21
@tobias47n9e : Agreed, sounds like a good idea to me

**Closed by misaochan** 2017-05-30 10:21 UTC
Labels: bug, metadata
