### ISSUE TITLE
White font for place type search box and "x"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3236] opened 2019-11-29 09:57 UTC
I could not find 😂
It hides part of the map.
![Screenshot_20191129-185633_Commons](https://user-images.githubusercontent.com/99590/69860600-f2dd1600-12d9-11ea-864e-5bdb24e3452a.jpg)

**Comment by neslihanturan** [comment] 2019-11-29 13:17
Clicking the small "x" next to search area makes it for me. Does it work for you too @nicolas-raoul ?

**Comment by nicolas-raoul** [comment] 2019-11-29 14:25
wow I could not see it lol
by the way how about making the font white? same color as "place type" 🙂

**Comment by chaytanyasinha** [comment] 2019-12-01 15:00
Yes @nicolas-raoul even I feel that it should be in white

**Comment by chaytanyasinha** [comment] 2019-12-04 11:36
May I do this

**Comment by neslihanturan** [comment] 2019-12-04 11:40
Sure @chaytanyasinha , givve a try. We especially want to have a white "x"

**Comment by chaytanyasinha** [comment] 2019-12-04 12:01
The selected items also needs to be written in white?
@neslihanturan

**Comment by neslihanturan** [comment] 2019-12-04 12:08
Displaying selected items is another issue, we should implement them separately. So for this issue just color of "x" button should be fine. By the way, you don't have any other assigned issues, right? We make one issue at a time.

**Comment by chaytanyasinha** [comment] 2019-12-04 12:17
No @neslihanturan I don't have any issue on which I am currently working.Okay I'll change the color.

**Comment by nicolas-raoul** [comment] 2019-12-04 12:19
Thanks @chaytanyasinha ! I think the "x" and also the text inside the place type search box (which says `Bridge, museum, ho...` in the screenshot above) should be made with the same font color as "Place type".

**Comment by chaytanyasinha** [comment] 2019-12-04 12:24
Okay @nicolas-raoul I'll do it.

**Comment by chaytanyasinha** [comment] 2019-12-05 18:23
@nicolas-raoul @neslihanturan I made the changes last night just after you assigned me but my ram is not working properly because of which I am not able to test the codes.
What should I do?

**Comment by chaytanyasinha** [comment] 2019-12-07 12:31
@neslihanturan @nicolas-raoul should I send a pull request?

**Comment by nicolas-raoul** [comment] 2019-12-09 06:31
Please send a pull request with the title "[WIP] White font for place type search box and x"
WIP means "Work In Progress"
Thanks :-)

**Comment by chaytanyasinha** [comment] 2019-12-09 06:48
okay @nicolas-raoul I'll do it.

**Comment by neslihanturan** [comment] 2019-12-09 08:53
@chaytanyasinha since the straightforward solution will not work for this issue (I also tried setting hint text color, I assume this is what you did too, am I right?) would be nicer to test it at least once before sending the PR. Is your issue with your ram permanent, or will be solved soon?

**Comment by neslihanturan** [comment] 2019-12-09 11:27
Additionally, this issue is one of our hot issues, see: https://github.com/commons-app/apps-android-commons/issues/3256 so it would be amazing if you can send your [WIP] PR as soon as possible, so that, if it does not work I will have time to work on the same.

**Comment by chaytanyasinha** [comment] 2019-12-09 13:08
No @neslihanturan RAM issue will be soon resolved,I'll try to test the codes now and will be sending the PR ASAP.

**Comment by chaytanyasinha** [comment] 2019-12-09 13:40
Yes @neslihanturan I also tried using changing the hint color only.

**Comment by chaytanyasinha** [comment] 2019-12-13 12:37
@neslihanturan @nicolas-raoul I have sent the pull request 2 days back with tag [WIP].I tried to check the codes but it was showing error "sdk files missing".I'll be thankful if you check it once for updating it.
Thanks.

**Comment by chaytanyasinha** [comment] 2019-12-14 03:19
@neslihanturan please guide me where I am wrong I'll try to resolve the codes.

**Comment by chaytanyasinha** [comment] 2019-12-15 08:11
@neslihanturan please guide me where I am wrong I'll try to resolve the codes.

**Comment by neslihanturan** [comment] 2019-12-16 11:19
Please see my reviews below your closed PR @chaytanyasinha . I think testing and seeing that your changes works is a must for sending a PR. so please focus on solving your issues with missing SDK filses, and make sure you can build the app with no issues. Then you can continue to contribute easier. Meanwhile I may have to send the PR for this issue, since it is on one of to do lists which has to be completed soon. But we have plenty other issues waiting for contributors:)

**Comment by chaytanyasinha** [comment] 2019-12-16 12:08
Sure @neslihanturan I will soon resolve my problem of computer and will again start contributing to the community.
Earlier I was upset because of first PR rejection because I knew how to solve these type of issues but thanks for supporting.
I'll soon start contributing again

**Comment by neslihanturan** [comment] 2019-12-16 12:15
Really no need to be upset, it is very normal to have some issues on your PR when your computer does not work properly and also SDK is not found. We need our tools to write code:)

**Comment by chaytanyasinha** [comment] 2019-12-16 13:34
Okay @neslihanturan I will resolve the issue.

**Comment by chaytanyasinha** [comment] 2019-12-24 05:18
@neslihanturan Can you please tell by what variable is the text defined which is there in the search box and the Cancel button.

**Comment by neslihanturan** [comment] 2019-12-24 09:52
There are no variables defined in the Java code, you can create them by findView. Did you solved you issues with Android Studio? :)

**Comment by chaytanyasinha** [comment] 2019-12-24 16:56
Actually @neslihanturan my ram was completely burnt from inside it will take few weeks to get new parts.That's why I am not active these days.

**Comment by maskaravivek** [comment] 2020-01-13 01:24
@chaytanyasinha Are you still working on this issue? If not, please let us know so that it can be reassigned to someone else. :)

**Comment by chaytanyasinha** [comment] 2020-01-13 02:31
@maskaravivek No,I am not working on it due to some technical issues,I'll be back with contributing in few days.Please assign to someone else.
Regards

**Comment by albendz** [comment] 2020-01-14 02:05
I can pick this up.

**Comment by maskaravivek** [comment] 2020-01-14 04:18
Sure. Assigned to you. :)

**Comment by albendz** [comment] 2020-01-18 19:09
@maskaravivek I'm unable to test the app due to a "Chain validation failed" error at the login page. Do you know what this is caused by? Tried on two different computers, multiple emulators, etc.

**Comment by maskaravivek** [comment] 2020-01-18 19:12
Yes, I too faced the same issue while using the beta flavor of the app. It is being discussed here. #3320

You can build and use the prod flavor of the app for the time being.

**Comment by albendz** [comment] 2020-01-18 19:16
Thanks, will do!

**Closed** 2020-01-22 10:25 UTC
Labels: enhancement, nearby
