### ISSUE TITLE
App crashing while uploading certain pictures.

### ISSUE THREAD

**Issue by Jatin0312** [commons-app/apps-android-commons#1323] opened 2018-03-16 21:42 UTC
**Summary:** 
I tried to upload one picture the app crashed. But it's not happening with every picture that I try to upload. Happens with picture located in content://com.android.providers.downloads.documents/document/

**Steps to reproduce:** 
Open app and click on upload picture and try to upload picture(Does not happen with every picture).

**Add System logs:**
```
03-17 03:06:15.693 748-748/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: fr.free.nrw.commons.debug, PID: 748
java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons.debug/fr.free.nrw.commons.upload.ShareActivity}: java.lang.NullPointerException: Attempt to get length of null array
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
at fr.free.nrw.commons.upload.ShareActivity.findOtherImages(ShareActivity.java:537)
at fr.free.nrw.commons.upload.ShareActivity.getFileMetadata(ShareActivity.java:519)
at fr.free.nrw.commons.upload.ShareActivity.performPreUploadProcessingOfFile(ShareActivity.java:398)
at fr.free.nrw.commons.upload.ShareActivity.onCreate(ShareActivity.java:298)
at android.app.Activity.performCreate(Activity.java:6672)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
at android.app.ActivityThread.-wrap12(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
 at android.app.ActivityThread.main(ActivityThread.java:6123) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
03-17 03:06:16.375 748-1001/fr.free.nrw.commons.debug D/ExistingFileAsync: File already exists in Commons: false


```

**Expected behavior:** 
It should not crash.

**Observed behavior:** 
It crashed.
![device-2018-03-16-194758](https://user-images.githubusercontent.com/17095817/37526049-739ef586-2954-11e8-91e2-837aeec0e209.gif)

**Device and Android version:** 
Moto G4 plus 
Android 7.0.0
Xiaomi
 8.1.0

 **Commons app version:** 
2.6.7

**Would you like to work on the issue?**
Yes i would like to work on this issue.

**Comment by hjoshi123** [comment] 2018-03-17 04:19
I would like to work on this. Can you briefly explain what might be or what is causing this error?
Is related to size of the images or the MIME type or something?

**Comment by Jatin0312** [comment] 2018-03-17 06:59
Hi @hjoshi123 I don't think it is related to size actually and I already have a fix for it.
In the method getPath located in FileUtils class.
```
else if (isDownloadsDocument(uri))  { // DownloadsProvider

                final String id = DocumentsContract.getDocumentId(uri);
                final Uri contentUri = ContentUris.withAppendedId(
                        Uri.parse("content://downloads/public_downloads"), Long.valueOf(id));

                returnPath =  getDataColumn(context, contentUri, null, null);
```
Changing
` Uri.parse("content://downloads/public_downloads"), Long.valueOf(id));`
to this
` Uri.parse("content://downloads/document"), Long.valueOf(id));`
seems to work fine.
I have tested this on 3 device.
Moto G4 plus Android 7.0.0
Xiaomi Android 8.1.0
Xiaomi Android 7.1.2

**Comment by knight-shade** [comment] 2018-03-17 07:10
@Jatin0312  How old is your fork? I am unable to find `getPath` method in FileUtils class.

**Comment by Jatin0312** [comment] 2018-03-17 07:14
No I think it's still there I'm checking from original repo.

**Comment by knight-shade** [comment] 2018-03-17 07:15
It's not there in the original repo as of now.

**Comment by Jatin0312** [comment] 2018-03-17 07:16
I will check and confirm.

**Comment by Jatin0312** [comment] 2018-03-17 07:43
@knight-shade I saw this method here if I'm wrong please correct me.
Sorry if I'm wrong with this.

![confirming](https://user-images.githubusercontent.com/17095817/37552944-763ad86a-29e4-11e8-85c0-29dfd22fb3b2.png)

**Comment by O-O-Balance** [comment] 2018-03-17 12:01
The problem appears to be in `upload.ShareActivity`:

    private void findOtherImages(boolean gpsEnabled) {
        Timber.d("filePath"+getPathOfMediaOrCopy());
        String filePath = getPathOfMediaOrCopy();
        long timeOfCreation = new File(filePath).lastModified();//Time when the original image was created
        File folder = new File(filePath.substring(0,filePath.lastIndexOf('/')));
        File[] files = folder.listFiles();
        Timber.d("folderTime Number:"+files.length);

The issue is with `folder.listFiles()`. It will return `null` when `folder` is not a directory or when an I/O error occurs (see its documentation). The app will then crash upon trying to get the `length`of a `null` array. So testing for `null` will fix this.

Another problem with this code occurred to me: `getPathOfMediaOrCopy()` may return `null` as well (see its implementation). So `filePath` should be checked for `null` before creating a `File` from it.

**Comment by Jatin0312** [comment] 2018-03-17 13:41
Here's the complete process which got this crash for better understanding.

Link : https://drive.google.com/open?id=13-rWrsrZsJWzkDq68j3NvF17JJXX7RU3

**Comment by Jatin0312** [comment] 2018-03-17 13:41
@O-O-Balance ya you are right there should be null check but the problem here I guess is about finding the location of file correctly.

**Comment by hjoshi123** [comment] 2018-03-17 13:43
@Jatin0312 I think the problem is that the URI is pointing at a temporary location. So next time you refer it its returning null. A better approach might be to directly get the file location instead of using URI's. I am working on a fix considering this. Please let me know your opinion

**Comment by Jatin0312** [comment] 2018-03-17 13:48
Ya I already have a fix for it
https://github.com/commons-app/apps-android-commons/issues/1323#issuecomment-373899479
It was working till now. I'm testing on more device right now.
Ya you are correct It's about the location problem.

**Comment by hjoshi123** [comment] 2018-03-17 13:49
Cool @Jatin0312 Lemme know if the crash is fixed

**Comment by Mansi449** [comment] 2018-03-20 14:54
@Jatin0312 I would like to fix this issue. Please assign it to me!

**Comment by Jatin0312** [comment] 2018-03-20 15:25
Hi @Mansi449  Actually I think I have a fix for this issue. Just waiting for mentors to confirm this issue.

**Comment by Mansi449** [comment] 2018-03-27 05:29
Please do review my PR :-)

**Comment by Mansi449** [comment] 2018-03-29 05:10
Please review my PR.

**Comment by Mansi449** [comment] 2018-03-29 07:12
App crashes when we try to upload a picture located in content://com.android.providers.downloads.documents/document/ 
After making this change, the app no longer crashed.

**Closed** 2018-04-30 10:49 UTC
