### ISSUE TITLE
setVisibility on null at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1657] opened 2018-06-22 14:58 UTC
```
06-22 23:02:24.720  5023  5023 W System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
06-22 23:02:24.728  5023  5023 W System.err:    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
06-22 23:02:24.728  5023  5023 W System.err:    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
06-22 23:02:24.729  5023  5023 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
06-22 23:02:24.729  5023  5023 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
06-22 23:02:24.729  5023  5023 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
06-22 23:02:24.729  5023  5023 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
06-22 23:02:24.729  5023  5023 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
06-22 23:02:24.729  5023  5023 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
06-22 23:02:24.729  5023  5023 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
06-22 23:02:24.729  5023  5023 W System.err:    at android.os.Looper.loop(Looper.java:154)
06-22 23:02:24.729  5023  5023 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6186)
06-22 23:02:24.729  5023  5023 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
06-22 23:02:24.729  5023  5023 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-22 23:02:24.729  5023  5023 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-22 23:02:24.731  5023  5023 W System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
06-22 23:02:24.731  5023  5023 W System.err:    at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList(SearchImageFragment.java:119)
06-22 23:02:24.731  5023  5023 W System.err:    at fr.free.nrw.commons.explore.SearchActivity.lambda$setTabs$1$SearchActivity(SearchActivity.java:108)
06-22 23:02:24.731  5023  5023 W System.err:    at fr.free.nrw.commons.explore.SearchActivity$$Lambda$1.accept(Unknown Source)
06-22 23:02:24.731  5023  5023 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
06-22 23:02:24.731  5023  5023 W System.err:    ... 10 more
06-22 23:02:24.731  5023  5023 E AndroidRuntime: FATAL EXCEPTION: main
06-22 23:02:24.731  5023  5023 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 5023
06-22 23:02:24.731  5023  5023 E AndroidRuntime: io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-22 23:02:24.731  5023  5023 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList(SearchImageFragment.java:119)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at fr.free.nrw.commons.explore.SearchActivity.lambda$setTabs$1$SearchActivity(SearchActivity.java:108)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at fr.free.nrw.commons.explore.SearchActivity$$Lambda$1.accept(Unknown Source)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
06-22 23:02:24.731  5023  5023 E AndroidRuntime:        ... 10 more
06-22 23:02:24.734   786 32093 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.explore.SearchActivity
```

**Comment by ujjwalagrawal17** [comment] 2018-06-26 18:49
@nicolas-raoul Seems like it is fixed now. I can't reproduce this too.

**Closed** 2018-06-27 01:11 UTC
Labels: branch-browse-commons-via-app, browsing, bug
