### ISSUE TITLE
Tapping "Tap to view upload" notification has no effect, should open the media details of the uploaded image

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#5083] opened 2022-10-22 01:53 UTC
![Screenshot_20221021-203157_One UI Home.jpg](https://user-images.githubusercontent.com/1230959/197311321-8d786a73-dba1-48a9-88dd-8b9f7cafac15.jpg)
We tap the above notification, but nothing happens. Samsung Galaxy Android 12
4.0.5~f03b7dd8d

**Comment by jidanni** [comment] 2022-10-22 01:54
Sure we can switch to the app manually, but it takes some of the fun out of it.

**Comment by nicolas-raoul** [comment] 2022-10-25 09:17
I can reproduce the issue on current master.

Anyone taking this, you find find this helpful: #4656

**Comment by Drirth** [comment] 2023-03-28 16:40
Hello @nicolas-raoul!, I am interested in working on this issue and would love to be assigned to it. Please let me know if there are any additional details or information I should be aware of before starting. Thank you.

**Comment by wldeh** [comment] 2023-03-28 16:40
Hello @nicolas-raoul!, I am interested in working on this issue and would love to be assigned to it. Please let me know if there are any additional details or information I should be aware of before starting. Thank you.

**Comment by mnalis** [comment] 2023-06-07 14:08
I have same issue on Android 10 (MIUI 12). 
- clicking on successful upload does nothing
- clicking on failed upload opens the app (but does not position on failed picture, nor give any more information about the error, as one would expect)
- clicking on notification that description was changed does open the browser linking to commons metadata page, which is correct at least.

Video:

https://github.com/commons-app/apps-android-commons/assets/156656/df391468-862d-416b-b38e-ad655a2bfb2e

**Comment by mnalis** [comment] 2023-06-15 15:07
Also can confirm that _"clicking on successful upload does nothing"_  in latest f-droid release (4.1.0~1649d1e2c)

**Comment by mnalis** [comment] 2023-11-19 11:59
Can confirm that _"clicking on successful upload does nothing"_  bug is still present in latest f-droid release (4.2.1~14b6c455b) on Android 10 (EMUI 12), Huawei P30 Pro.

**Comment by nicolas-raoul** [comment] 2024-01-13 13:33
@wldeh  Any progress to share? :-)

**Comment by ShashwatKedia** [comment] 2024-03-27 08:00
I face this issue on the current master as well, and this happens with almost all upload notifications, such as "Upload Failed", "Upload Paused", etc.

**Comment by ShashwatKedia** [comment] 2024-03-27 08:30
I still face this problem on the current master, and it seems to be there for almost all upload notifications, such as "Uploading Paused", "Failed to upload", etc.

**Comment by mnalis** [comment] 2024-05-04 20:35
Can confirm that _"clicking on successful upload does nothing"_ bug is still present in latest f-droid release (`5.0.1~af028cbdd`) on Android 14 (OneUI 6.1), Samsung Galaxy S23+

**Comment by mnalis** [comment] 2024-06-23 03:53
@wldeh are you still interested on working on this Commons issue? Or would you rather be unassigned?

**Comment by OpenGreenStreet** [comment] 2024-08-18 12:52
I tap on the Commons app message in the push notifications. No matter how I press, nothing happens. The strange thing is that it does work in very rare cases. But I have no idea under what circumstances it works and when it doesn't.

See also #5779

**Comment by nicolas-raoul** [comment] 2024-08-26 02:32
@wldeh  I unassign for now, but if you are you still working on this, please let us know. If no answer, someone else may be assigned to it. Thanks a lot. :-)

**Comment by OpenGreenStreet** [comment] 2024-09-01 07:19
If the smartphone is unlocked, it does not work for me. If the smartphone is locked (lock screen), it works for me

**Comment by PetitPotiron** [comment] 2024-09-01 17:03
> If the smartphone is unlocked, it does not work for me. If the smartphone is locked (lock screen), it works for me

I just tried, and cannot reproduce this on my Samsung Galaxy A40 (Android 11, v4.2.1)

**Comment by chrisdebian** [comment] 2024-12-17 11:59
Hi, all. Are people still having this issue in the latest release?

Thanks,

Chris.

**Comment by OpenGreenStreet** [comment] 2024-12-29 15:52
@chrisdebian : I tried it earlier (Version 5.1.0~707997bd1). It worked both in lock screen and unlocked state. Thank you very much!

**Closed** 2024-12-29 22:08 UTC
Labels: bug
