### ISSUE TITLE
Orientation change cancels the ongoing login process.

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1294] opened 2018-03-12 17:12 UTC
**Summary:** 

After filling the username and password, when we click on login button, a progress bar starts. But if orientation change takes place when the progress bar is active, it leads to cancellation of login process. Again the user has to tap login button to start the login process.

**Steps to reproduce:** 

1. Go to the login screen.
2. Fill out username and password field.
3. Click on Login button and change orientation while the progress bar is still active.

**Expected behavior:** 

The login process should continue even if orientation change occurs.

**Observed behavior:** 

The login process cancels if orientation change occurs.

**Device and Android version:** 

Redmi Note 4 Android 7.0 MIUI V9 Global
 
## Before
![before](https://user-images.githubusercontent.com/20313518/37297936-fd7eb0b0-2644-11e8-8db5-2084c93fa2c9.gif)

## After
![after](https://user-images.githubusercontent.com/20313518/37298010-36580cc4-2645-11e8-8983-36d98da7d02b.gif)

In case anybody is wondering why login was not successful, its because I have put random password for demonstration purpose. :yum: 

Shall I create a PR for it ? @maskaravivek @misaochan

**Comment by nicolas-raoul** [comment] 2018-03-13 02:18
Thanks!
Yes a PR would be most welcome :-)

2018/03/13 2:16 "Abhishek Poonia" <notifications@github.com>:

**Comment by madhurgupta10** [comment] 2018-03-13 05:10
can I work on this?

**Comment by nicolas-raoul** [comment] 2018-03-13 06:38
@knight-shade do you intend to send a pull request soon? In how many days? Thanks :-)
@madhurgupta10 The issue is assigned to @knight-shade's for now.

**Comment by madhurgupta10** [comment] 2018-03-13 08:10
@nicolas-raoul Ok, no problem.

**Comment by knight-shade** [comment] 2018-03-13 10:32
@nicolas-raoul I already have a fix for it locally, that's how I have 'after' gif demonstrating the changes. Just was a little bit hesitant to create the PR, so asked for opinion. Will create the PR right way :smile:

**Closed** 2018-03-16 11:46 UTC
Labels: assigned
