### ISSUE TITLE
After click on backButton, application goes back to the exploreActivity 

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4063] opened 2020-12-05 03:19 UTC
**Summary:** 
when your are at SearchActivity  then click on Backbutton application goes back to exploreActivity .
I want application goes to RecentSearch fragment  and when click again on backbutton application goes back to exploreActivity.

**Steps to reproduce:** 
>Menu
->Explore
->Search something
->Click on BackButton

**Device and Android version:** 
API :29 
**Commons app version:** 
2.13.1
**Screen-shots:** 
![20201204_214647](https://user-images.githubusercontent.com/65972015/101232060-6aa40480-36d5-11eb-8037-3ae7a72f197c.gif)
**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by Prince-kushwaha** [comment] 2020-12-05 03:20
I want to work on this issue 
asssinged me

**Comment by nicolas-raoul** [comment] 2020-12-15 13:46
Thanks for the screencasts, that's very helpful to explain the issue.

**Comment by neslihanturan** [comment] 2020-12-22 17:41
I am not sure the expected behavior would be going back to the recent searches fragment. I think the way it works now is fine.

**Comment by neslihanturan** [comment] 2021-01-11 12:35
Hi all, I was reviewing the latest PR and recognized this is not the case in current master of fixed already. See my screen record, tested at 3.0.0-debug-master~8e9b39fa8 :

https://user-images.githubusercontent.com/3127881/104183062-6f6d7e00-5422-11eb-9e6d-3b40b5730b16.mp4

**Comment by neslihanturan** [comment] 2021-01-11 12:36
So closing this issue and related PR, since it seems like there is no issue at all actually.

**Closed** 2021-01-11 12:38 UTC
Labels: bug, explore
