### ISSUE TITLE
So hard to choose language with massive list

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4032] opened 2020-11-12 23:11 UTC
I can't even tell if there is Chinese deep down in this massive list. I looked and looked. Why isn't there some help to choose the language with a short search string?
![Screenshot_20201113-070711.jpg](https://user-images.githubusercontent.com/1230959/99007456-34b0ac00-257f-11eb-9a0e-f2b295853e08.jpg)

**Comment by jidanni** [comment] 2020-11-12 23:12
I'm also wondering. Let's say I do finally find the language. Hopefully it'll be remembered on my frequently chosen languages list. That way the next time I need to do this it'll be right up on the top.

**Comment by jidanni** [comment] 2020-11-12 23:13
As you see, I gave up on trying to find Chinese. And just inserted Chinese in the English box.
![Screenshot_20201113-070746.jpg](https://user-images.githubusercontent.com/1230959/99007700-b1438a80-257f-11eb-87aa-28e5c0c1602c.jpg)

**Comment by jidanni** [comment] 2020-11-12 23:14
2.13.1.828~2ed5a74

**Comment by jidanni** [comment] 2020-11-12 23:15
Even though it was raining, and I was in a hurry, I still checked under the z h, traditional Chinese, Chinese, Hans...

**Comment by jidanni** [comment] 2020-11-12 23:32
By the way at the top of the list there were about 50 greyed-out variants of English. If there are grayed out I suppose I couldn't choose them. Well why don't you put the grayed-out stuff at the bottom of the list as people are in a hurry...

**Comment by jidanni** [comment] 2020-11-12 23:36
By the way, even though Chinese is not the most popular language according to the rank of a number of Wikipedia articles, but it is the most spoken language in the world so hopefully it will appear closer to the top, if ever.

**Comment by nicolas-raoul** [comment] 2020-11-15 01:28
Duplicate of #3681

**Closed by nicolas-raoul** 2020-11-15 01:28 UTC
