### ISSUE TITLE
App posts deletion request notifications ({{subst:idw}}) on the wrong user's talk page

### ISSUE THREAD

**Issue by bjh21** [commons-app/apps-android-commons#3464] opened 2020-03-04 18:28 UTC
I'm afraid I don't actually use the app: this issue is based on observing edits made on Commons by people apparently using it.

When someone nominates a file for deletion, a notification (using {{subst:[idw](https://commons.wikimedia.org/wiki/Template:Idw)}}) should be placed on the user talk page of everyone who uploaded a version of that file. It seems that instead, the app is placing such a notification on the user talk page of the user who nominated the image for deletion. This is a serious problem, since it means that uploaders may not find out that one of their uploads has been nominated for deletion.

Examples:
* [Commons:Deletion requests/File:The Valleys.png](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:The_Valleys.png): file uploaded by Realitys; nominated by Magurale; notification appears on [User talk:Magurale](https://commons.wikimedia.org/wiki/User_talk:Magurale) but not on [User talk:Realitys](https://commons.wikimedia.org/wiki/User_talk:Realitys)
* [Commons:Deletion requests/File:Daegu1 Life Treatment Center (coronavirus)1.png](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:Daegu1_Life_Treatment_Center_(coronavirus)1.png): file uploaded by Choikwangmo9; nominated by Kurtkaiser; notification appears on [User talk:Kurtkaiser](https://commons.wikimedia.org/wiki/User_talk:Kurtkaiser) but not on [User talk:Choikwangmo9](https://commons.wikimedia.org/wiki/User_talk:Choikwangmo9)
* [Commons:Deletion requests/File:Vilnia, Łukiški. Вільня, Лукішкі (V. Zacharčyk, 1865-79).jpg](https://commons.wikimedia.org/wiki/File:Vilnia,_%C5%81uki%C5%A1ki._%D0%92%D1%96%D0%BB%D1%8C%D0%BD%D1%8F,_%D0%9B%D1%83%D0%BA%D1%96%D1%88%D0%BA%D1%96_(V._Zachar%C4%8Dyk,_1865-79).jpg): file uploaded by Kazimier Lachnovič; nominated by Nitiphonbinsoh407; notification appears on [User talk:Nitiphonbinsoh407](https://commons.wikimedia.org/wiki/User_talk:Nitiphonbinsoh407) but not on [User talk:Kazimier Lachnovič](https://commons.wikimedia.org/wiki/User_talk:Kazimier_Lachnovi%C4%8D)
* [Commons:Deletion requests/File:中苏友谊纪念塔 2020.jpg](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:%E4%B8%AD%E8%8B%8F%E5%8F%8B%E8%B0%8A%E7%BA%AA%E5%BF%B5%E5%A1%94_2020.jpg): file uploaded by Rowingbohe; nominated by Somesh Desai; notification appears on [User talk:Somesh Desai ](https://commons.wikimedia.org/wiki/User_talk:Somesh_Desai ) but not on [User talk:Rowingbohe](https://commons.wikimedia.org/wiki/User_talk:Rowingbohe)

**Comment by misaochan** [comment] 2020-03-05 14:01
@nicolas-raoul , is it okay if I nominate one of your photos for deletion to try and reproduce this?

**Comment by sivaraam** [comment] 2020-03-05 18:22
@misaochan If you're just looking for some photo to test this, you can feel free to test it on the [ones that I've uploaded](https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Kaartic&ilshowall=1) if they meet the requirements. Particularly here's one which I won't mind even if it's actually deleted: 

https://commons.wikimedia.org/wiki/File:Partially_visible_instructions_for_getting_suggested_articles_for_editing.png

My commons talk page could be found here: https://commons.wikimedia.org/wiki/User_talk:Kaartic

Oh, and don't get confused by the deletion notifications there. Those were self-nominations ([except for one](https://commons.wikimedia.org/wiki/User_talk:Kaartic#File:Tail_of_Notification_bar_in_Wikimedia_Phabricator.png)). FWIW, I did make the self-nominations using the app.

**Comment by misaochan** [comment] 2020-03-05 18:52
Yup, I can confirm that this is very reproducible - https://commons.wikimedia.org/wiki/User_talk:Misaochan2#File:Sunset_at_Chunnambar.jpg came from the deletion request that I submitted for a photo that @sivaraam uploaded (sorry about choosing that one @sivaraam , I could not for the life of me find the "partially visible instructions" pic in Explore, lol. I did leave a note that I was only testing and the photo shouldn't be deleted).

This seems to be a new issue as we had just fixed #3147 in v2.12. Regardless, this needs to be fixed in 2.13.

**Comment by sivaraam** [comment] 2020-03-05 18:58
I just got a chance to test this myself by nominating images in the beta instance and am *able to* reproduce the issue described.

Here's what I did.

First I nominated [this image](https://commons.m.wikimedia.beta.wmflabs.org/wiki/File%3AImage_20.jpg) using [my account](https://commons.wikimedia.beta.wmflabs.org/wiki/User:Sivaraam). The nomination was successful as could be seen from the nomination notice in the file page. Then I went to the [talk page of that image's author](https://commons.m.wikimedia.beta.wmflabs.org/wiki/User_talk:Animeshk08) to check if the nomination notification was there. I couldn't find it. Then I went to [my talk page](https://commons.wikimedia.beta.wmflabs.org/wiki/User_talk:Sivaraam) to see if the nomination notice was there as described in this issue. Interestingly, I couldn't find it there either! The talk page was empty at that time. Looks like nomination notifications don't get added when the talk page is empty (*bug ?*). So, I then added to some dummy text to the talk page.

Then, I nominated [another image](https://commons.m.wikimedia.beta.wmflabs.org/wiki/File%3ADash.jpg) for deletion. Then, I checked my talk page. I found a notification about the deletion there. Then I checked the [uploader's talk page](https://commons.m.wikimedia.beta.wmflabs.org/wiki/User%20talk:dash) but couldn't find any notification. It might also be because of the empty talk page issue that I described above.

To be double sure, I nominated [yet another image](https://commons.m.wikimedia.beta.wmflabs.org/wiki/File%3AMobileTest_20200301-01.jpg) for deletion which was uploaded by a user who had a non-empty talk page (hope `@domdomegg` doesn't mind ;-). I observed that the deletion notification appears only in my talk page and not in the [uploader's talk page](https://commons.m.wikimedia.beta.wmflabs.org/wiki/User_talk:Domdomegg) thus confirming the issue.

**Comment by sivaraam** [comment] 2020-03-05 19:04
> (sorry about choosing that one @sivaraam ,

Ah, that was one of the only good ones that I've uploaded. But never mind. It's fine as you've mentioned not to delete it 🙂  

> Ah, you I could not for the life of me find the "partially visible instructions" pic in Explore, lol.

😄

> I did leave a note that I was only testing and the photo shouldn't be deleted).

Thank you! As you could've observed from my previous comment this issue is reproducible in the beta server too. So, you do have the option of testing this with the beta server. There you can happily test this without any worries of getting images deleted. 🙂

**Comment by VitalyVPinchuk** [comment] 2020-03-11 12:44
Hi
Could I try to fix it?

**Comment by nicolas-raoul** [comment] 2020-03-11 12:47
@VitalyVPinchuk Sure, thanks :-)

**Closed** 2020-03-17 11:39 UTC
Labels: assigned, bug, high priority
