### ISSUE TITLE
Location not available, Nearby unusable

### ISSUE THREAD

**Issue by FatimahGoldhirsch** [commons-app/apps-android-commons#4156] opened 2021-01-05 22:51 UTC
**Summary:** 

Nearby does not recognize location, does not show quests and is practically unusable.

**Steps to reproduce:** 

1. Allow app to access location via GPS
2. Open app, go to Home, select Nearby
3. Map is centered to Tower of London, displays error message "Nearby might not work properly, Location not available"
4. It is not possible to get the location and also not possible to scroll to the right place manually and display quests

- My location is not recognized despite GPS being available. 
- I cannot see possible places to take photos of, which is the main reason why I downloaded the app. 

Am I missing something? If you need any more information, let me know. Thank you for your time.

**System logs:**

**Device and Android version:** 

device: Fairphone 2
android version: LineageOS 17.1 (Android Version 10)
custom ROM
also: no gapps/microg and no SIM card
 
**Commons app version:** 

2.13.2~757c7b008 (via F-Droid)

**Screen-shots:** 

![Screenshot_20210105-232919_Commons](https://user-images.githubusercontent.com/77028308/103707569-23988000-4faf-11eb-8c47-d2dd5c0fd76e.png)

**Comment by misaochan** [comment] 2021-01-06 14:23
Hi @FatimahGoldhirsch , sorry to hear about that. We've just released v3.0 to beta, which should contain a fix for this issue. If you are enrolled in beta testing, could you please update your app to v3.0 and see if it solves the problem for you? If not, could you sign up for the beta at https://play.google.com/apps/testing/fr.free.nrw.commons ?

Thanks a lot!

**Comment by FatimahGoldhirsch** [comment] 2021-01-09 22:25
Hello @misaochan 
thanks, it is good to know that this problem has been worked on. 

I have never compiled an app before (after all, I'm just a regular user) and couldn't make it work yet. That means I will wait for v3.0 to become published on F-Droid. Sorry that I can't help with beta testing.

**Comment by misaochan** [comment] 2021-01-14 15:41
Thanks for letting us know! Is it possible for you to send logs for us to investigate this? Go to Nearby and get that error message, then Settings > Send Log File.

**Comment by 4D17Y4** [comment] 2021-01-15 09:46
Hey @misaochan ,
I think this issue might be related to the issue #3924 .
I have investigated on it and have reported [here](https://github.com/commons-app/apps-android-commons/issues/3924#issuecomment-743808555) .
Let me know if the solution suits you, otherwise ill try to find other possible ways of handling the issue.

Just to confirm @FatimahGoldhirsch , can you try waiting for sometime and check wheter the location gets updated and let me know if it does, it will help me determining whether the issue is same as #3924 .

PS: [Linking](https://github.com/commons-app/apps-android-commons/issues/3924#issuecomment-690852174) Log file comment, if @misaochan  you wanna go through them once.



Thx.

**Comment by FatimahGoldhirsch** [comment] 2021-01-19 22:44
Hello and thank you for your replies.

@4D17Y4 Yes, that issue looks similar to mine. I waited for several minutes and it did not get the location, whereas another app was able to get the location. 

What I am wondering the whole time is why I cannot load needed pictures when the app does not know my location in the first place. Can I only look at the needed pictures at my current location? 

@misaochan I tried using the "Send Log File" feature. Unfortunately it did not really seem to do anything and I did not find any information about how this is supposed to work. Is the log sent in the background? Is it stored in a place that I can't find? 

best regards

**Comment by 4D17Y4** [comment] 2021-01-20 06:43
Thanks for letting me know @FatimahGoldhirsch , 
I'll look into it, and convey as get more info.

**Comment by misaochan** [comment] 2021-01-21 10:45
> What I am wondering the whole time is why I cannot load needed pictures when the app does not know my location in the first place. Can I only look at the needed pictures at my current location?

@FatimahGoldhirsch This is a good question. The map was initially designed as a "Nearby" map, that would allow users to view needed pictures at their current location. We eventually added the option to "Search" for needed pics at other areas, but we did not change the location requirement. This issue still needs to be fixed, but I do think that there is merit in switching to a system where we DON'T need the user's location to display the map. I will create a new issue and CC you.

Re: the Send Log File feature, it was supposed to pull up your email client and attach the logs, you would need to send the email manually. Which email client are you using?

@4D17Y4 it does look like a similar issue to #3924 , thanks for spotting that!

**Comment by FatimahGoldhirsch** [comment] 2021-01-26 23:27
@misachan 
Send Log File issue: I'm using the default client that came with my OS (com.android.email).

And thank you for opening that new issue. I was not sure whether this topic was already discussed and settled.

**Comment by endim8** [comment] 2021-08-09 00:54
Im also getting this issue. I'm also using LOS 17.1 with no gapps, and also unable to upload a log :(

**Comment by misaochan** [comment] 2021-08-12 14:55
I think this should have been fixed at #4259 . I agree, the error message is inconsistent.

**Comment by rohit9625** [comment] 2024-02-19 16:40
This issue seems to be resolved now. I would prefer to close it. 
What do you think @FatimahGoldhirsch?

**Closed** 2024-02-20 00:31 UTC
Labels: bug, nearby
