### ISSUE TITLE
Contributions Screen- Nearest Feature

### ISSUE THREAD

**Issue by chrisdebian** [commons-app/apps-android-commons#4861] opened 2022-02-26 13:14 UTC
### What is the user problem or growth opportunity you want to see solved?

When using the app, at the top of the Contributions tab/page, I can see the nearest location to me, that is recognised as being if interest. In many cases, a photograph of the location has already been submitted.

### How do you know that this problem exists today? Why is this important?

So that it is easier to identify the next item needing a photo, would it be possible to only show 'near' places that actually need a photo?

### Who will benefit from it?

This will enable photos to be taken and uploaded, with less effort, so should increase contributions. 

### Anything else you would like to add?

Forgive me if this was an options in the settings, that I missed. The 'Display Nearby Notification' is turned on, but seems to show all locations, not just those needing photos.

Cheers,

chris_debian
2E0FRU

**Comment by chrisdebian** [comment] 2022-02-26 13:19
I'm using version 3.1.1~1c9267ca0, on a Pixel 4a.

**Comment by ShashwatKedia** [comment] 2024-03-24 04:45
@nicolas-raoul, this seems to be a duplicate of #5448 which is already solved by #5468. Could we close this as completed?

**Comment by nicolas-raoul** [comment] 2024-03-25 10:45
Oops I am the one who created a duplicate.
Thanks for noticing!

**Closed by nicolas-raoul** 2024-03-25 10:45 UTC
Labels: enhancement
