### ISSUE TITLE
Number of Contributions reduces to zero on re-login

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2377] opened 2019-01-31 04:26 UTC
**Summary:** 

Contibution fragment shows 0 contibutions(both failed and successful on re-login 

**Steps to reproduce:** 

- First have some contributions either failed or successful
- Logout of your account from you app
- Log-in to the same account
- Your contributions are all vanished

### Expected

- Previous succcessful as well as faile images must have been retained in the application
- Also this empty fragment displays no such message like "You haven't made any contributions yet"

**Device and Android version:** 
Vivo 1713 Android version 7.0

**Screen-shots:** 
![whatsapp image 2019-01-31 at 9 48 23 am](https://user-images.githubusercontent.com/34261945/52030463-07c40e00-253e-11e9-9518-91130efaeea5.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by neslihanturan** [comment] 2019-03-11 14:30
I can verify this happens after re-login. A very weird issue. @madhurgupta10 did you made any progress with this? Did you managed to find the root cause?

**Comment by neslihanturan** [comment] 2019-03-12 13:40
This happened to me again. I found it very annoying and obvious, will prioritize it

**Comment by madhurgupta10** [comment] 2019-03-12 13:42
@neslihanturan I will prioritize it and deep dive to find the root cause to it.

**Comment by neslihanturan** [comment] 2019-03-12 13:45
Thanks for your interest @madhurgupta10 but I think it is assigned to @vanshikaarora . @vanshikaarora  can you please verify you are still working on this issue?

**Comment by vanshikaarora** [comment] 2019-03-12 13:51
I am sorry, for no response since long. I'll start working on this soon.

**Comment by vanshikaarora** [comment] 2019-03-12 16:37
@neslihanturan I was going through the issue what I noticed was that in the application contributions were added to the ContentProvider using 
```
public void save(Contribution contribution) {
        ContentProviderClient db = clientProvider.get();
        try {
            if (contribution.getContentUri() == null) {
                contribution.setContentUri(db.insert(BASE_URI, toContentValues(contribution)));
            } else {
                db.update(contribution.getContentUri(), toContentValues(contribution), null, null);
            }
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        } finally {
            db.release();
        }
    }
```
And while  logging out all files except the libraries are removed (including the ContentProviders) using the `clearApplicationData() ` function of `CommonsApplication.java` 

```
 File cacheDirectory = context.getCacheDir();
        File applicationDirectory = new File(cacheDirectory.getParent());
        if (applicationDirectory.exists()) {
            String[] fileNames = applicationDirectory.list();
            for (String fileName : fileNames) {
                if (!fileName.equals("lib")) {
                    FileUtils.deleteFile(new File(applicationDirectory, fileName));
                }
            }
        }
```

**Comment by vanshikaarora** [comment] 2019-03-13 12:42
>Is the above conclusion correct? Please correct me if I am wrong :)

@neslihanturan Can you give please give your suggestion here? :)

**Comment by vanshikaarora** [comment] 2019-03-13 16:56
@neslihanturan I have gone through the Issue closely. 

### Reason's for failure

- Contribution and other data(like personal preferences in settings) are not fetched through API. They are stored locally in cache, files, databases and other storage's
- While logging out we call the delete file method, that delete's the following 8 Files:


1. cache
2. code_cache
3. shared_prefs
4. files
5. app_ACRA-unapproved
6. app_ACRA-approved
7. lib-main
8. databases

These files contain data of the contributions and other preferences of the User

### Solution
We can avoid deleting the data by removing these methods but then we need to take care of the case that this same information isn't used if the user is logged in using a different account

@neslihanturan Can you please share your opinion? :)

**Comment by misaochan** [comment] 2019-04-16 16:19
Does this happen just in master, or in an actual release? I experienced the same problem in master, but I have not received any reports from v2.10.2 users about it (and usually users are quite vocal about problems like this ;)).

If we can concur that it just happens in master, it may be a good idea to find out which commit is causing the problem rather than trying to solve from scratch.

BTW, I wonder why number of contributions are not fetched through the API anymore? They used to be IIRC.

**Comment by madhurgupta10** [comment] 2020-03-13 22:13
@neslihanturan @misaochan Is this issue still there?

**Comment by misaochan** [comment] 2020-03-16 10:13
I have not noticed it recently, but I'm not sure. Could you test this and let us know what you find @madhurgupta10 ? :)

**Comment by macgills** [comment] 2020-03-16 10:44
I would judge this "feature, not a bug", if I've understood it correctly. At least for failed contributions.

We delete our databases so that another user can login ,an unlikely scenario but possible.

To support this we would have to key the data in our databases by user and never delete them.

Previously successful contributions should be accessible from the endpoint though.

**Comment by misaochan** [comment] 2020-03-17 11:35
> Previously successful contributions should be accessible from the endpoint though.

This is what I was thinking. AFAIK we DID have an API for this, but not sure what happened with that. @maskaravivek any idea?

**Comment by madhurgupta10** [comment] 2020-04-12 14:58
> I have not noticed it recently, but I'm not sure. Could you test this and let us know what you find @madhurgupta10 ? :)

I don't face this issue anymore, rather sometimes I get "Error occurred while loading images" error.

**Comment by ashishkumar468** [comment] 2020-10-11 17:25
Happening no more on 2.13. Also as this is very old, closing this one, feel free to re-open if it happens again :)

**Closed by ashishkumar468** 2020-10-11 17:25 UTC
Labels: assigned, bug, high priority
