### ISSUE TITLE
App "minimizes" immediately

### ISSUE THREAD

**Issue by magnusmanske** [commons-app/apps-android-commons#352] opened 2017-01-10 13:24 UTC
Nexus 5x (2016), Android 7.1.1

When I open the app, it shows for a second, black screen with the "My uploads" title bar, then minimizes itself. It keeps running in the apps list, but when I switch to it, same thing happens.

**Comment by misaochan** [comment] 2017-01-16 10:18
Hi @magnusmanske ,

Thanks for reporting this. Has this happened the entire time you have been using the app, or is it only a recent occurrence that followed some sort of change (e.g. updating to Android 7.x)?

**Comment by magnusmanske** [comment] 2017-01-16 10:29
I believe it was working prior to 7.x. I had the app removed for a while, so I'm not sure exactly when the breaking started.

**Comment by misaochan** [comment] 2017-01-16 11:00
Hmm. Can anyone with a 7.x device please help test and see if it breaks for them as well? 7.x hasn't been pushed to my (unrooted) Android device yet, and I am stuck with a slow laptop for the time being so running an emulator is difficult (my desktop is currently en route to Australia via sea, heh).

**Comment by misaochan** [comment] 2017-02-06 14:43
Finally managed to test on a 7.1.1 device, not able to reproduce this bug. Is anyone still experiencing this?

**Comment by VojtechDostal** [comment] 2017-02-19 15:20
Magnus do you use two-factor authentication? I experienced the same bug a few weeks before and had to unistall, disable 2FA and install again (maybe i did not have to uninstall and reinstall, just logging in/our would be enough)

**Comment by addshore** [comment] 2017-05-13 15:39
I just experienced this too while writing https://github.com/commons-app/apps-android-commons/commit/db19c20bc10bb923186403a5d086a5236e556d26 which adds logging into to 2fa.

I have a feeling that it relates to the attempted login of accounts where details are already stored by the app. If you have 2fa enabled the app needs to ask for your 2fa code again, but instead it just thinks the login has failed and bails.

**Comment by misaochan** [comment] 2017-05-19 15:53
Oh, this now happens even with non-2fa logins lol.

**Comment by neslihanturan** [comment] 2018-01-16 09:55
I don't think this happens anymore. Does it?

**Comment by VojtechDostal** [comment] 2018-01-16 09:57
Haven't experienced this for a long long time

**Comment by VojtechDostal** [comment] 2018-01-16 09:58
But then, I switched off 2FA...

**Comment by misaochan** [comment] 2018-01-17 06:51
Nope, this doesn't happen with non-2FA logins (that was a bug with one of the hackathon builds I believe), but still happens for 2FA logins on master I think.

**Comment by maskaravivek** [comment] 2018-01-17 17:12
Yes, this is still reproducible with 2FA enabled. Am working on fixing it. :)

**Comment by maskaravivek** [comment] 2018-02-06 08:08
Fixed in #1048

**Closed by maskaravivek** 2018-02-06 08:08 UTC
Labels: bug, prehackathon/hackathon
