### ISSUE TITLE
Caption lost after accepting "Is this a picture of..."

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5842] opened 2024-09-30 06:51 UTC
Steps:
1. Prepare two images, the second with coordinates near a Wikidata item (you can download them from Commons to test)
2. Enter a caption. Imagine the user is taking the time to write a great/accurate/descriptive very long caption.
3. Go to the second image. The dialog "Is this a picture of..." appears, click Yes
4. Problem: You loose everything you had typed.

https://github.com/user-attachments/assets/15c92af5-0ed7-4b0b-9305-aea3b9f1ae5a

Ideally the app would read the coordinates of all pictures of the multi-upload, find the first one whose coordinates are near a Wikidata item (something smarter can be devised in the future such as barycenter or clustering but let's keep this task simple for now), ask "Are these pictures of...", and only then let the user enter captions.

**Comment by QuantumPineapple68** [comment] 2024-10-01 11:14
actually, i have ran the application i cannot see any error as such. is it this problem still there or is it closed

**Comment by nicolas-raoul** [comment] 2024-10-01 22:37
@QuantumPineapple68 Still happening to me. Are you using the GitHub main branch? Can you post a screencast? Thanks!

**Comment by QuantumPineapple68** [comment] 2024-10-17 06:46
I checked it so many times and the issue seems to be solved. I am using the main branch itself. Can you please check once again from your end, and let me know ?? Thanks ![]()[]()[]()[]()[]()https://github.com/user-attachments/assets/a17c37c2-a116-4414-ab44-dc45f4060ab5

**Comment by savsch** [comment] 2024-12-13 21:11
I’d like to work on this issue, can I be assigned to it?

**Comment by nicolas-raoul** [comment] 2024-12-13 22:46
@savsch Did you manage to  reproduce the issue? 🙂

**Comment by savsch** [comment] 2024-12-14 06:23
> @savsch Did you manage to reproduce the issue? 🙂

Yes, I was able to reproduce this issue. As a note, I typically do that part before requesting for assignment 😁

**Comment by nicolas-raoul** [comment] 2024-12-14 06:27
Fantastic, thanks! 🙂

**Closed** 2024-12-14 10:12 UTC
Labels: bug
