### ISSUE TITLE
Preview image in ShareActivity fails to load

### ISSUE THREAD

**Issue by harisankerPradeep** [commons-app/apps-android-commons#1175] opened 2018-02-21 19:20 UTC
Sometimes when the selected image is heavy the preview image in ShareActivity, the one that appears in the background of the title and descriptions screen, fails to load.  This mostly happens when the camera operates at maximum resolution. If the resolution of the image is a couple of notches lower it loads just fine.

Observed 

![godavnvis](https://user-images.githubusercontent.com/26009796/36500454-56348782-176a-11e8-8a52-22121852130d.png)

Expected (This was achieved by clicking the same photo at a lower resolution using open camera)

![godavvis](https://user-images.githubusercontent.com/26009796/36500267-dc6633ce-1769-11e8-87b3-a92f01adef4e.png)

Device and Android version: 
Xiaomi Redmi 4A, Android 6.0.1, MIUI 8.5.7.0

Solution: I think most of this can be solved by using downsampling and resizing functions of fresco given  [here .](http://frescolib.org/docs/resizing.html) I also came across #889 which intents to replace fresco with glide. 

I'd like to work on this if the community feels it's a good idea. 

Cheers!

**Comment by nicolas-raoul** [comment] 2018-02-22 05:39
I can confirm this problem.
Is it not a duplicate of #1004 though?

**Comment by harisankerPradeep** [comment] 2018-02-22 06:17
@nicolas-raoul My bad, it's same as #1004. But I strongly feel about downsampling and resizing because my screen resolution is 720x1280 and the maximum resolution of my camera is 3280x2160. Knowing this I should be able to resize the image without any loss in quality of the displayed picture, right? Or am I getting this wrong somewhere? 
Also should I move this conversation to #1004 .

Thanks in advance!

**Comment by nicolas-raoul** [comment] 2018-02-22 06:50
Closing as duplicate of #1004.
Yes, please copy/paste your comment there, thanks :-)

**Closed by nicolas-raoul** 2018-02-22 06:50 UTC
