### ISSUE TITLE
Handle and Fix the Delay in Logout

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2764] opened 2019-03-27 14:52 UTC
**Summary**
Handle and Fix the Delay in Logout.

**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment] 2019-03-27 15:17
@madhurgupta10 Why is the toast required?

**Comment by madhurgupta10** [comment] 2019-03-27 15:26
@maskaravivek Sometimes when a user logout there is a couple of seconds delay, this creates confusion for the user to hit the log out button again or not, A toast will ensure that the logout was successful and user don't need to redo the task.

**Comment by maskaravivek** [comment] 2019-03-27 16:15
If theres a delay then it might be better to show a progress bar instead. 

But before that can you investigate the cause of delay. No network operation occurs while the user logs out. So it would be better to find out which task is taking time

**Comment by madhurgupta10** [comment] 2019-03-27 16:56
@maskaravivek Sure, I will investigate the cause of the delay, and a Progress Bar would be better.

**Comment by macgills** [comment] 2020-03-19 15:40
closing as duplicate of #3547

**Closed by macgills** 2020-03-19 15:40 UTC
Labels: assigned, auth
