### ISSUE TITLE
[Bug]: Category search often doesn't find matches, especially if more than one word is supplied

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5712] opened 2024-05-05 00:53 UTC
### Summary

Often, category search fails to find anything for multi-word search. Sometimes also fails for single-word search which should match multi-word category.

### Steps to reproduce

1. select picture to upload
2. fill any data until you get to `Step 3 of 4: Categories`
3. type name _"alojzije stepinac"_ to search
4. notice no category is found
5. reduce search term to just _"alojzije"_
6. notice many results, including those with _"Alojzije Stepinac"_ in them

### Expected behaviour

in step `4.` there would be matches for _"alojzije stepinac"_ (just as there are in step `6.` !) 

### Actual behaviour

there are no category matches shown in step `4.`

### Device name

Samsung Galaxy S23+

### Android version

Android 14 (OneUI 6.1)

### Commons app version

5.0.1~af028cbdd (latest F-droid)

### Device logs

[CommonsAppLogs-alojzije.log](https://github.com/commons-app/apps-android-commons/files/15211365/CommonsAppLogs-alojzije.log)

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/156656/479c69c4-51f9-4c66-b6b5-43d3c83b0c76

### Would you like to work on the issue?

None

**Comment by mnalis** [comment] 2024-05-05 01:10
- Seems to be related to https://github.com/commons-app/apps-android-commons/issues/3179 but not complete duplicate. Here is another example which shows that single-word with correct case not finding the multi-word match:


https://github.com/commons-app/apps-android-commons/assets/156656/0a78d33b-7b06-461f-8b90-aeb536425be7

and log: 
[CommonsAppLogs-5712-franjo.log](https://github.com/commons-app/apps-android-commons/files/15211384/CommonsAppLogs-5712-franjo.log)

Note specifically:
1. `00:00:08`: `No categories found` for search term _"franjo tuđman"_
2. `00:00:18`: 1 category (`Tuđman: surname`) found for search term _"tuđman"_
3. `00:00:23`: 1 category (`Tuđman: surname`) found for search term _"Tuđman"_ (uppercase), although the app also says `No categories found` (?!)
4. `00:00:31`: **many** categories found for _"Franjo Tuđman"_ (correct result).

So even if search term _"Tuđman"_ was in correct case in step `3.`, it did not match as it contained only one word of the category name _"Franjo Tuđman"_, and not all words.

---

Additinal info (not in the screencast): searching for _"franjo Tuđman"_ (case of only first word incorrect) works to find matches, but _"Franjo tuđman"_ (case of only second word incorrect) doesn't find anything

**Comment by mnalis** [comment] 2024-05-05 01:26
Interestingly, when typing categories on https://commons.wikimedia.org/wiki/Special:UploadWizard

steps `2a.` and `3a.` also find only one match as the commons app, however trying step `1a` actually works (i.e. produces the same result as `4a`!)

Could the Commons app use the same API that Special:UploadWizard uses for category search?

**Comment by nicolas-raoul** [comment] 2024-05-08 01:36
I think we were using a different API in the past but switched for some reason, unfortunately I don't remember what API nor what the issue was.

Would you be able to:
1. Identify the API URL of Special:UploadWizard, you can use Chrome DevTools' network tab to find out.
2. List OK/fail for various search strings.

That would be super helpful. Thanks a lot!

**Comment by mnalis** [comment] 2024-05-11 19:15
> 1. Identify the API URL of Special:UploadWizard, you can use Chrome DevTools' network tab to find out.

When typing into `Categories` fields of `Special:UploadWizard`, which seems to handle search case-insensitive manner (which we would like too) it calls (when searching for _"franjo tuđman"_ all lowercase) this URL:
 
https://commons.wikimedia.org/w/api.php?action=opensearch&format=json&formatversion=2&namespace=14&limit=10&search=franjo%20tu%C4%91man

It successfully finds results in different case, e.g. :
```
0	"Category:Franjo Tuđman"
1	"Category:Franjo Tuđman bridge (Dubrovnik)"
2	"Category:Franjo Tuđman square in Blato (Korčula)"
[...]
```

> 2. List OK/fail for various search strings.

Do you mean list of  OK/fail currently in Commons app, or those  in `Special:UploadWizard` ? Or both?

**Comment by sivaraam** [comment] 2024-05-12 18:21
> When typing into `Categories` fields of `Special:UploadWizard`, which seems to handle search case-insensitive manner (which we would like too) it calls (when searching for _"franjo tuđman"_ all lowercase) this URL:
> 
> https://commons.wikimedia.org/w/api.php?action=opensearch&format=json&formatversion=2&namespace=14&limit=10&search=franjo%20tu%C4%91man
>

I think we specifically avoided the `search` API (which I think is now `opensearch` but good to confirm once) as it would not bring up categories for which a category page does not exist [[ref](https://github.com/commons-app/apps-android-commons/issues/3179#issuecomment-612052320)]. Further it is possible to filter out hidden categories with the current API that we use but not the search API. Does the Special:UploadWizard bring up such pages when your search for it?



> * Seems to be related to [Make category search non case-sensitive #3179](https://github.com/commons-app/apps-android-commons/issues/3179) but not complete duplicate. Here is another example which shows that single-word with correct case not finding the multi-word match:
> 

I'm kind of unsure. The category search bring up only prefix matches AFAIR. That's why "Franjo Tuđman" / "Franjo" / "franjo" would've brought the result you expected but not "Tuđman" / "tuđman". The API allows the first character of the title to be of any case only because MediaWiki itself treats the first character of the page title case insensitively. Otherwise, the API does a pure case-sensitive prefix match.

Overall, I think this is still is essentially a duplicate of #3179. Let me know in case I'm wrong.

**Comment by nicolas-raoul** [comment] 2024-05-13 06:21
> Do you mean list of OK/fail currently in Commons app, or those in Special:UploadWizard ? Or both?

Both.
It would be even better if you can put a link to the search string as reference for each result.

More test searches can be found at https://github.com/commons-app/apps-android-commons/issues/22 https://github.com/commons-app/apps-android-commons/issues/237 https://github.com/commons-app/apps-android-commons/issues/2664 https://github.com/commons-app/apps-android-commons/issues/3641 https://github.com/commons-app/apps-android-commons/issues/4192 https://github.com/commons-app/apps-android-commons/issues/4901#issuecomment-1073006271 https://github.com/commons-app/apps-android-commons/issues/5588

@sivaraam 

`Tudman` not finding `Franjo Tudman` (as seen in the screencast above) is a bug not related to case, I believe. Possibly that part is the same as https://github.com/commons-app/apps-android-commons/issues/5588

Hopefully the table from Matija will give us a clear vision of all use cases, and what we should be using with what preprocessing.

**Comment by sivaraam** [comment] 2024-05-13 13:33
> `Tudman` not finding `Franjo Tudman` (as seen in the screencast above) is a bug not related to case, I believe. Possibly that part is the same as #5588
> 

I don't think that's a bug in our end. It's basically a result of us using the `allcategories` API for search which does a prefix-match (i.e., results are shown only when the query matches the first part of the category title. see [this comment](https://github.com/commons-app/apps-android-commons/issues/3641#issuecomment-614831501) for more details). This is also the root-cause of the following issues: #237 and #5588 (unless I didn't understand those issues correctly).

I'm closing this one in favour of continuing the discussion at #3179  which seems like a more appropriate place to discuss improvements to category search. It would help keep discussions / findings in one place. @mnalis could also feel free to post their findings there. 🙂

**Closed by sivaraam** 2024-05-13 13:33 UTC
Labels: bug
