### ISSUE TITLE
Release v5.0.0

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5528] opened 2024-02-09 03:25 UTC
We're due the release of ~~v4.3.0~~ v5.0.0 soon. Thanks to our volunteer community, we have significant things such as the migration from Mapbox to OSM droid, other enhancements, removal of the data-client module and various bug fixes. 🙂 

It would be ideal if we iron out few things before the release, though. For instance, we could look into converging the following MR that fixes some issues in Nearby: #5494 

Feel free to chime in if there other such things which we should certainly handle before release.

## Checklist

- [x] Converge the following MRs
  - [x] #5494 
  - [x] #5525
- [x] If possible, a fix for #5218 (moved over to #5715)

## Post release

- [x] Tweak data safety form to clarify we don't gather telemetry
- [x] Close this issue: #5373

**Comment by sivaraam** [comment] 2024-02-09 03:44
There's this one thing about the switch to Mapbox that bugs me a bit. The speed at which tiles are loaded has drastically reduced after the switch IIt takes several seconds for the tiles to load.

Is this just me or does this also happen to others too? If yes, we should likely open a separate issue about this amd discuss there.

**Comment by kanahia1** [comment] 2024-02-09 03:58
@sivaraam This also happens to me, osmdroid takes time to load tiles for first time.

**Comment by nicolas-raoul** [comment] 2024-02-09 04:34
@sivaraam Created https://github.com/commons-app/apps-android-commons/issues/5529 about slow maps, I don't think that should delay release though, as it may take time to solve and is still quite usable.

**Comment by sivaraam** [comment] 2024-03-26 04:25
There's a user report now about the app not showing user statistics. We should plan on releasing v4.3.0 soon.

Commons talk link: https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app#c-Alex_Blokha-20240321230800-App_shows_error,_when_dispalying_stats

**Comment by nicolas-raoul** [comment] 2024-04-09 13:18
I don't really think we need to wait for 5494 and 5218. Any other blocker?

**Comment by sivaraam** [comment] 2024-04-09 13:59
The only reason, I kept #5494 as a blocker is because it fixes many broken flows in nearby / explore map screens. It's already in a decently ready state. So, we shouldn't have trouble merging it down for this release.

The only other blocker is getting the release notes for this release. There have been a huge amount of changes. I hope the MR title and descriptions are clear enough to easily draft release notes from them. 🙂

**Comment by sivaraam** [comment] 2024-04-17 03:57
@nicolas-raoul [This issue](https://github.com/commons-app/apps-android-commons/issues/5692) seems like a regression when compared to v4.2.1. It seems like it might be bad UX in locations where multiple pins could be present. So, should we fix that before releasing v4.3.0?

**Comment by nicolas-raoul** [comment] 2024-04-17 04:02
@sivaraam It is a regression indeed, but not an important one because:
- It is rare that there are so many pins close to each other.
- Any user would typically zoom in before choosing a pin.
- The place name is also visible at the bottom.
So it should not delay release. :-)

**Comment by mnalis** [comment] 2024-04-17 23:30
I'm a big fan of _"release early, release often"_. It reduces anxiety, gives better feedback to users, and smaller changes means easier triage of new bugs (e.g. if regression was introduced in just the last release which changed just a little code, it is much easier to find why/where than if there is a ton of new code to wade through).

It's already been **half a year** since the last release. I'd love to see new one. There've been few issuees I wanted to test if there were fixed, but by now I've even forgotten what they even were :cry: 

Then, when that #5692 (and perhaps a few others) are fixed, `4.3.1` can easily be released in a month or two, no problems.

**Comment by sivaraam** [comment] 2024-04-24 04:04
Makes sense, @mnalis 🙂 

I'll look into releasing v4.3.0 soon-ish. We could do iterative smaller releases soon as you suggest. Let's see if we could change the release cycle to make it a montly release at the least 👍🏼  Don't hesitate to nudge us if we don't do so 😉

**Comment by sivaraam** [comment] 2024-04-28 12:25
Rolled out v5.0.1 for testing just now. Yeah, I thought it made total sense to bump the major version considering the quantum of changes that has gone [[ref](https://github.com/commons-app/apps-android-commons/releases/tag/v5.0.0)] 🚀 

Thank you very much to the contributors for all your invaluable contributions! It is great to see so many contributors willing to improve the app and thus contributing to the Wikimedia Commons community in some way. ❤️ 

---

The released version is v5.0.1 and not v5.0.0 as we hit the ProGuard trimming issue in v5.0.0. That went unnoticed and the release variants were literally broken. So, I tweaked the rules in [this commit](https://github.com/commons-app/apps-android-commons/commit/da0b2c28e39f61b64a981c8b114ab5e6d4be7406) and bumped the version to [v5.0.1](https://github.com/commons-app/apps-android-commons/releases/tag/v5.0.1) to avoid removing the existing tag. 

I did release the v5.0.1 after testing all the major flows work fine. Regardless, @psh could you kindly take a look at [this commit](https://github.com/commons-app/apps-android-commons/commit/da0b2c28e39f61b64a981c8b114ab5e6d4be7406) and ensure that I've not accidentally excluded any package that should be excluded from R8 trimming?

On a side note, I also created a release for [v4.3.0](https://github.com/commons-app/apps-android-commons/tree/v4.3.0) as I realized that it is ideal to bump the major version _after_ pushing our the v4.3.0 tag. It's just there for reference purposes.

---

On another side note, GitHub has the great release notes generation ability which works after the tag is published. If anyone is aware of how to use the same without pushing the tag, kindly let me know. It would be helpful for adding the entries in CHANGELOG file 🙂

**Comment by sivaraam** [comment] 2024-04-28 12:29
@linsui There are two tags v4.3.0 and v5.0.0 which contain non-working code (unfortunately). Could you help us with disabling both of those from being published in F-droid?

Only the v5.0.1 one has working code.

I hope this time it should be easy as all versions have different version name and version codes 🙂 

Will try to avoid this issue in future 👍🏼

**Comment by linsui** [comment] 2024-04-28 15:26
Done. :)

**Comment by sivaraam** [comment] 2024-04-28 15:49
Thank you @linsui ! 🙂

**Comment by sivaraam** [comment] 2024-05-12 18:26
I've initiated a staged rollout of the app to Production on Google Play. So, it should be available to users in a few days 🙂

**Closed** 2024-05-24 18:47 UTC
