### ISSUE TITLE
Explore category shows same image indefinitely

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2182] opened 2018-12-20 03:12 UTC
**Steps to reproduce:** 

1. Go to Explore
2. Type "pictures of the year" in the search bar (UPDATE: category has changed, use `Velles (Indre)` instead)
3. Select the "categories" tab
4. Tap the first one https://commons.wikimedia.org/wiki/Category:Pictures_of_the_Year
5. Scroll its media
6. Notice that after two other picture, the picture https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg is repeated infinitely
7. Scrolling more just makes that same picture appear more.

**System logs:**

```
12-20 12:07:05.183 31263  5939 D CustomApiResult: API response is
12-20 12:07:05.183 31263  5939 D CustomApiResult:  <?xml version="1.0" encoding="UTF-8"?><api><continue iistart="2007-02-11T14:50:24Z" gcmcontinue="2014-05-29 03:53:32|33050273" continue="gcmcontinue||"/><query><pages><page _idx="33050273" pageid="33050273" ns="14" title="Category:Pictures of the Year/2013 (finalist)"/><page _idx="30597925" pageid="30597925" ns="14" title="Category:Picture of the year barnstars"/><page _idx="3207499" pageid="3207499" ns="4" title="Commons:Grafika roku"/><page _idx="1662301" pageid="1662301" ns="6" title="File:POTY Feb 11.jpg" imagerepository="local"><imageinfo><ii url="https://upload.wikimedia.org/wikipedia/commons/5/56/POTY_Feb_11.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=1662301"><extmetadata><DateTime value="2007-02-11 22:18:06" source="mediawiki-metadata" hidden=""/><ObjectName value="POTY Feb 11" source="mediawiki-metadata" hidden=""/><CommonsMetadataExtension value="1.2" source="extension" hidden=""/><Categories value="Media lacking a description|Pictures of the Year|Self-published work" source="commons-categories" hidden=""/><Assessments value="" source="commons-categories" hidden=""/><DateTimeOriginal value="" source="commons-desc-page"/><Credit value="&lt;span class=&quot;int-own-work&quot; lang=&quot;en&quot;&gt;Own work&lt;/span&gt;" source="commons-desc-page" hidden=""/><Artist value="&lt;a href=&quot;//commons.wikimedia.org/wiki/User:Alvesgaspar&quot; title=&quot;User:Alvesgaspar&quot;&gt;Alvesgaspar&lt;/a&gt; (&lt;a href=&quot;//commons.wikimedia.org/wiki/User_talk:Alvesgaspar&quot; title=&quot;User talk:Alvesgaspar&quot;&gt;talk&lt;/a&gt;&lt;span style=&quot;white-space:nowrap&quot;&gt; &lt;b&gt;·&lt;/b&gt;&lt;/span&gt; &lt;a href=&quot;//commons.wikimedia.org/wiki/Special:Contributions/Alvesgaspar&quot; title=&quot;Special:Contributions/Alvesgaspar&quot;&gt;contribs&lt;/a&gt;)" source="commons-desc-page"/><LicenseShortName value="CC BY-SA 2.5" source="commons-desc-page" hidden=""/><UsageTerms value="Creative Commons Attribution-Share Alike 2.5" source="commons-desc-page" hidden=""/><AttributionRequired value="true" source="commons-desc-page" hidden=""/><LicenseUrl value="https://creativecommons.org/licenses/by-sa/2.5" source="commons-desc-page" hidden=""/><Copyrighted value="True" source="commons-desc-page" hidden=""/><Restrictions value="" source="commons-desc-page" hidden=""/><License value="cc-by-sa-2.5" source="commons-templates" hidden=""/></extmetadata></ii></imageinfo></page><page _idx="24840980" pageid="24840980" ns="14" title="Category:Pictures of the Year/2012 (finalist)"/><page _idx="20107176" pageid="20107176" ns="14" title="Category:Pictures of the Year/2011 (finalist)"/><page _idx="20107168" pageid="20107168" ns="14" title="Category:Pictures of the Year/2010 (finalist)"/><page _idx="20107166" pageid="20107166" ns="14" title="Category:Pictures of the Year/2009 (finalist)"/><page _idx="20107165" pageid="20107165" ns="14" title="Category:Pictures of the Year/2007 (finalist)"/><page _idx="20081670" pageid="20081670" ns="14" title="Category:Pictures of the Year exhibitions"/></pages></query></api>
12-20 12:07:05.230 31263 31263 W System.err: java.lang.ClassCastException: fr.free.nrw.commons.category.CategoryDetailsActivity cannot be cast to fr.free.nrw.commons.category.CategoryImagesActivity
12-20 12:07:05.230 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.handleSuccess(CategoryImagesListFragment.java:245)
12-20 12:07:05.230 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.bridge$lambda$0$CategoryImagesListFragment(CategoryImagesListFragment.java)
12-20 12:07:05.230 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment$$Lambda$4.accept(Unknown Source)
12-20 12:07:05.230 31263 31263 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
12-20 12:07:05.230 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutObserver.onNext(ObservableTimeoutTimed.java:94)
12-20 12:07:05.231 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
12-20 12:07:05.231 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
12-20 12:07:05.231 31263 31263 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
12-20 12:07:05.231 31263 31263 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
12-20 12:07:05.231 31263 31263 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
12-20 12:07:05.231 31263 31263 W System.err:    at android.os.Looper.loop(Looper.java:154)
12-20 12:07:05.231 31263 31263 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6186)
12-20 12:07:05.231 31263 31263 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
12-20 12:07:05.231 31263 31263 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-20 12:07:05.231 31263 31263 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-20 12:07:05.232 31263 31263 D MediaDetailPagerFragmen: Skipping getCount. Returning as activity is destroyed!
12-20 12:07:05.256 31263 31263 W View    : requestLayout() improperly called by android.widget.ProgressBar{691c78 V.ED..... ......ID 468,624-612,768 #7f090113 app:id/loadingImagesProgressBar} during layout: running second layout pass
12-20 12:07:05.796 31263  5939 D CustomApiResult: API response is
12-20 12:07:05.796 31263  5939 D CustomApiResult:  <?xml version="1.0" encoding="UTF-8"?><api><continue iistart="2007-02-11T14:50:24Z" gcmcontinue="2014-05-29 03:53:32|33050273" continue="gcmcontinue||"/><query><pages><page _idx="33050273" pageid="33050273" ns="14" title="Category:Pictures of the Year/2013 (finalist)"/><page _idx="30597925" pageid="30597925" ns="14" title="Category:Picture of the year barnstars"/><page _idx="3207499" pageid="3207499" ns="4" title="Commons:Grafika roku"/><page _idx="1662301" pageid="1662301" ns="6" title="File:POTY Feb 11.jpg" imagerepository="local"><imageinfo><ii url="https://upload.wikimedia.org/wikipedia/commons/5/56/POTY_Feb_11.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=1662301"><extmetadata><DateTime value="2007-02-11 22:18:06" source="mediawiki-metadata" hidden=""/><ObjectName value="POTY Feb 11" source="mediawiki-metadata" hidden=""/><CommonsMetadataExtension value="1.2" source="extension" hidden=""/><Categories value="Media lacking a description|Pictures of the Year|Self-published work" source="commons-categories" hidden=""/><Assessments value="" source="commons-categories" hidden=""/><DateTimeOriginal value="" source="commons-desc-page"/><Credit value="&lt;span class=&quot;int-own-work&quot; lang=&quot;en&quot;&gt;Own work&lt;/span&gt;" source="commons-desc-page" hidden=""/><Artist value="&lt;a href=&quot;//commons.wikimedia.org/wiki/User:Alvesgaspar&quot; title=&quot;User:Alvesgaspar&quot;&gt;Alvesgaspar&lt;/a&gt; (&lt;a href=&quot;//commons.wikimedia.org/wiki/User_talk:Alvesgaspar&quot; title=&quot;User talk:Alvesgaspar&quot;&gt;talk&lt;/a&gt;&lt;span style=&quot;white-space:nowrap&quot;&gt; &lt;b&gt;·&lt;/b&gt;&lt;/span&gt; &lt;a href=&quot;//commons.wikimedia.org/wiki/Special:Contributions/Alvesgaspar&quot; title=&quot;Special:Contributions/Alvesgaspar&quot;&gt;contribs&lt;/a&gt;)" source="commons-desc-page"/><LicenseShortName value="CC BY-SA 2.5" source="commons-desc-page" hidden=""/><UsageTerms value="Creative Commons Attribution-Share Alike 2.5" source="commons-desc-page" hidden=""/><AttributionRequired value="true" source="commons-desc-page" hidden=""/><LicenseUrl value="https://creativecommons.org/licenses/by-sa/2.5" source="commons-desc-page" hidden=""/><Copyrighted value="True" source="commons-desc-page" hidden=""/><Restrictions value="" source="commons-desc-page" hidden=""/><License value="cc-by-sa-2.5" source="commons-templates" hidden=""/></extmetadata></ii></imageinfo></page><page _idx="24840980" pageid="24840980" ns="14" title="Category:Pictures of the Year/2012 (finalist)"/><page _idx="20107176" pageid="20107176" ns="14" title="Category:Pictures of the Year/2011 (finalist)"/><page _idx="20107168" pageid="20107168" ns="14" title="Category:Pictures of the Year/2010 (finalist)"/><page _idx="20107166" pageid="20107166" ns="14" title="Category:Pictures of the Year/2009 (finalist)"/><page _idx="20107165" pageid="20107165" ns="14" title="Category:Pictures of the Year/2007 (finalist)"/><page _idx="20081670" pageid="20081670" ns="14" title="Category:Pictures of the Year exhibitions"/></pages></query></api>
12-20 12:07:05.817   790   888 D WifiStateMachine: updateCapabilities for config:mywififalse,false
12-20 12:07:05.844 31263 31263 W System.err: java.lang.ClassCastException: fr.free.nrw.commons.category.CategoryDetailsActivity cannot be cast to fr.free.nrw.commons.category.CategoryImagesActivity
12-20 12:07:05.845 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.handleSuccess(CategoryImagesListFragment.java:245)
12-20 12:07:05.845 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.bridge$lambda$0$CategoryImagesListFragment(CategoryImagesListFragment.java)
12-20 12:07:05.845 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment$$Lambda$4.accept(Unknown Source)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutObserver.onNext(ObservableTimeoutTimed.java:94)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
12-20 12:07:05.845 31263 31263 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
12-20 12:07:05.845 31263 31263 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
12-20 12:07:05.845 31263 31263 W System.err:    at android.os.Looper.loop(Looper.java:154)
12-20 12:07:05.845 31263 31263 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6186)
12-20 12:07:05.845 31263 31263 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
12-20 12:07:05.845 31263 31263 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-20 12:07:05.845 31263 31263 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-20 12:07:05.846 31263 31263 D MediaDetailPagerFragmen: Skipping getCount. Returning as activity is destroyed!
```

**Device and Android version:** 

Android 7.1.2 LineageOS

**Commons app version:** 

2.9.0.118

**Screen-shots:** 

![screenshot_20181220-120208](https://user-images.githubusercontent.com/99590/50261519-3a172180-0450-11e9-8dd6-a9c24aba2fc8.png)

**Comment by nicolas-raoul** [comment] 2018-12-20 03:51
The problem might have always existed. I just discovered that category randomly.
It does not happen for the other categories I have tried.
I reproduced the problem for that particular category, so it probably has _something_ special.

**Comment by zhao-gang** [comment] 2018-12-24 14:40
I found the reason. It's related to continue parameters. Currently we only set and save two continue parameters(`continue` and `gcmcontinue`). Actually it could include a `iistart` parameter in continue node of a `generator=categorymembers` query's response. 

Sample:
 https://commons.wikimedia.org/w/api.php?gcmtitle=Category%3APictures+of+the+Year&gcmtype=file&gcmdir=desc&continue=gcmcontinue%7C%7C&prop=imageinfo&gcmcontinue=2014-05-29+03%3A53%3A32%7C33050273&iistart=2007-02-11T14%3A50%3A24Z&format=xml&gcmsort=timestamp&action=query&generator=categorymembers&iiprop=url%7Cextmetadata&gcmlimit=10&format=xml

API response(striped):
```
...
<continue iistart="2007-02-11T11:31:18Z" gcmcontinue="2014-05-29 03:53:32|33050273" continue="gcmcontinue||"/>
...
```

I tested that if the `iistart` parameter is added to the query, the query would continue and won't repeat indefinitely.

So I think the solution might be to change [QueryContinue class](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/category/QueryContinue.java), so it can deal with all possible `continue` node parameters. If it's OK, I'd like to work on this.

**Comment by maskaravivek** [comment] 2018-12-25 08:03
Good investigation @zhao-gang! Feel free to take this up. :)

**Comment by zhao-gang** [comment] 2019-03-03 15:55
This issue can't be reproduced since the server made some category changes related to "Pictures of the Year". But there is a newer issue reported the indefinite repeat image problem(#2523).

**Comment by neslihanturan** [comment] 2019-03-15 08:45
Closing this one, seems outdated:)

**Comment by zhao-gang** [comment] 2019-03-15 14:14
The indefinitely repeated images issue is caused by commons client. It can only process two parameters(`gcmcontinue`  `continue`) returned by the server. The server never promised it only returns two parameters: [API documentation](https://www.mediawiki.org/wiki/API:Query#Continuing_queries). When the server returns some parameters other than above two, the client just ignores them, which causing the client to make the same request to the server in following requests. That's the reason why server returns the same image indefinitely. Because the client always use the exactly same request to the server.

The issue can still be reproduced in #2523 

If this client side limitation is not removed, there will be other categories showing indefinite images on commons app. I think it's worth the effort to address this client side bug.

@neslihanturan Please reopen this issue as it's still valid and needs to be fixed.

**Closed** 2019-11-06 11:06 UTC
Labels: assigned, bug, explore
