### ISSUE TITLE
Description edit dialog does not always work

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4931] opened 2022-04-11 12:18 UTC
### Steps to reproduce

1. Open app
2. In Explore>Featured, tap on any picture (this opens media details)
4. Tap on the pen circled in red:
![adb](https://user-images.githubusercontent.com/99590/160240295-fc195ac7-b38b-4f78-9b78-da2110c0d16c.png)

### Expected behaviour

Description edition dialog opens

### Actual behaviour

Spinner keeps spinning, dialog never opens.

**Comment by JustinLiang522** [comment] 2022-04-11 14:28
@nicolas-raoul I tried to reproduce the bug, but the dialog opened as expected...
<img src="https://user-images.githubusercontent.com/73240868/162761165-94b0599b-9c7a-4ed2-82e6-2ade546b069e.png"  width="30%">

**Comment by Ayan-10** [comment] 2022-04-11 19:08
@nicolas-raoul Actually the issue is not only about the picture which is not uploaded by the app. The algorithm which is extracting descriptions from `wikitext` is mainly based on a general syntax of `description` structured in `wikitext` which is `|description={{language1|1=description in language1}}, {{language2|1=description in language 1}}`. The descriptions of the pictures uploaded from phone are stored in `wikitext` in the above format. But in the case of the web, descriptions don't follow the above format for being stored in wikitext. Even for some files, the structure is way different. Due to this kind of difference among the files the algorithm is failing to handle those cases and acting abnormally. So, If the description is structured in the above format it will act as expected no matter from where it's been uploaded.

@JustinLiang522 Thanks for sharing the screenshot, sharing the file name also would be more helpful. As I can see in the attached image the description and caption are not there in the Activity. As far as I know, there should be at least one description and caption. I think, in this case, the algorithm is breaking in a different way than "Spinner keeps spinning" because of a different way of storing description in **wikitext**.

Thanks.

**Comment by nicolas-raoul** [comment] 2022-04-12 00:49
Thanks @JustinLiang522 for testing and thanks @Ayan-10 for your explanation which makes a lot of sense.

My fault for not identifying what picture it was. I can reproduce using this picture: https://commons.wikimedia.org/wiki/File:Antique_cash_register_in_a_cafe,_Darjeeling.jpg which can be found in Explore>Featured.

So, the goal of this issue would be to:
- Make other descriptions editable by analyzing and implementing the most common syntax patterns (at least `description={{en|1=Antique cash register in a cafe, Darjeeling}}` and similar).
- If parsing fails, show a popup `Sorry, this image's descriptions follow a rare syntax and thus can only be edited on the website.`
- Randomly pick 20 Commons pictures and make their wikitext into unit tests.

**Comment by nicolas-raoul** [comment] 2022-04-12 00:50
Note: This bug has existed since a long time (since at least 85bdcd5a7a689b2782e22501e6aa355f97dbe796)

**Comment by JustinLiang522** [comment] 2022-04-15 02:26
@nicolas-raoul Can I work on this issue?

**Comment by nicolas-raoul** [comment] 2022-04-15 05:00
@JustinLiang522 Yes thanks!

**Comment by JustinLiang522** [comment] 2022-04-16 11:04
I intercepted the description of the picture that can cause this bug from `getCurrentWikiText()` of `MediaClient.kt`, but it seems to be in the right format.
```
=={{int:filedesc}}==
{{Information
|description={{en|1=Antique cash register in a cafe, Darjeeling}}
|date=2017-05-17 17:07:26
|source={{own}}
|author=[[User:Subhrajyoti07|Subhrajyoti07]]
|permission=
|other versions=
}}
{{Location|27.043186|88.267003}}
{{Assessments|featured=1}}


=={{int:license-header}}==
{{self|cc-by-sa-4.0}}

[[Category:Images by User:Subhrajyoti07]]
[[Category:Taken with Nikon D3200]]
[[Category:Quality images of West Bengal]]
[[Category:Cash registers in India]]
{{QualityImage}}
```

**Comment by nicolas-raoul** [comment] 2022-04-16 12:14
Interesting!
Would you mind creating a unit test based on this wikitext, and debugging the issue?

**Comment by Ayan-10** [comment] 2022-04-16 12:16
Yes, the format is right but the algorithm divides the descriptions (ex. `{{language1|1=description in language1}} , {{language2|1=description in language 2}}`) of different languages by the comma/"," to get the description in different laguages (ex. arr[`"{{language1|1=description in language1}}"` **,** `"{{language2|1=description in language 2}}"`]). However in this case of description there is a comma/"," inside the content of the description so it's dividing the description as arr[`"{{en|1=Antique cash register in a cafe"` **,** `" Darjeeling}}"`] instead of arr[`"{{en|1=Antique cash register in a cafe, Darjeeling}}"`]. This is the reason for the bug. So, we can understand that the different languages description can not be divided by comma we need to do it in a more efficient way.

Like this, there can be different scenarios where the algorithm will fail for different reasons. Try to find the cause by dry run the algorithm line by line with respect to the wikitext.

**Comment by JustinLiang522** [comment] 2022-04-16 12:21
@Ayan-10 Got it, thanks!

**Comment by Ayan-10** [comment] 2022-04-16 12:25
@nicolas-raoul I missed your comment.

**Comment by JustinLiang522** [comment] 2022-04-16 14:40
How about changing the original algorithm into a repeatedly matching string pattern of `{{languageCode|desciption}}` and putting them into the description list?

**Comment by JustinLiang522** [comment] 2022-04-17 03:56
I have tried the algorithm I described in my last comment and it worked for most files except for two cases:
1. The description is a bare string of words without specifying any language.
2. Multiple string patterns of the form `{{A|B}}` can appear after `desciption=` but inside some double curly brackets the `A` may not be a language code. (This can probably be addressed by checking whether `A` is a valid language code before adding the description to the list)

**Comment by nicolas-raoul** [comment] 2022-04-17 10:56
@JustinLiang522 Nice progress! 🙂

**Comment by JustinLiang522** [comment] 2022-04-17 15:06
@nicolas-raoul I have created a few unit tests for the `getDescriptions` method, should also I commit them?

**Comment by nicolas-raoul** [comment] 2022-04-17 22:54
@JustinLiang522 Yes, unit tests are very valuable, thanks a lot!

**Closed** 2022-04-28 07:34 UTC
Labels: bug
