### ISSUE TITLE
No crash information in crash email (Gmail)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3466] opened 2020-03-05 13:55 UTC
**Summary:** 

Since a rather long time, ACRA seems to not attach logs to the crash report email.
For instance, I just got a crash and after the ACRA screen, Gmail opens on this screen:
![Screenshot_20200305-225033_Gmail](https://user-images.githubusercontent.com/99590/75987872-054b9900-5f34-11ea-82f5-7527e2d49587.jpg)
As you can see, the email is empty, so there is no point sending it.

Fortunately I had logcat running this time, here it is, hopefully it can explain why the crash info is not included in the email:
[empty_acra.txt](https://github.com/commons-app/apps-android-commons/files/4293249/empty_acra.txt)

**Comment by vvijayalakshmi21** [comment] 2020-03-06 06:08
HI, I am an Outreachy applicant and would like to contribute,
Kindly assign this issue to me 
Also, I know just the basics of Android dev. It would be really helpful if you could help me get started with setting up the project.

**Comment by nicolas-raoul** [comment] 2020-03-06 06:17
@vvijayalakshmi21 It is yours :-)

Here is how I would do:
1. Run the app in debug mode, make sure breakpoints work.
2. Modify the code to throw an exception somewhere, for instance in the About menu.
3. Debug step-by-step what happens after the exception.
4. Use Git to take the source code of the app like it was 6 months ago (crash info was coming through at that time), and compare.

Thanks!

**Comment by sivaraam** [comment] 2020-03-06 15:45
FWIW, I _recently_ tried to send the crash email from ACRA using K-9 mail and I was able to see the crash information in the mail body. I've even sent it to the crash Google group where people with access to it can find it for reference.

**Comment by sivaraam** [comment] 2020-03-06 15:47
To clarify my previous comment, I'm just saying crash reporting works fine with K-9 mail So, there's a chance this _might be_ a Gmail specific thing that needs to be handled.

**Comment by vvijayalakshmi21** [comment] 2020-03-07 05:58
Thank you so much for the direction sir. 
Kindly help me get started. How do I set up the project in my local machine? (Windows 10 Home)
Is there a way to replicate the issue in the live website?

**Comment by nicolas-raoul** [comment] 2020-03-07 06:41
@sivaraam Interesting! So it seems to be specific to the crash found in the empty_acra.txt above. I modify the instructions.

**Comment by nicolas-raoul** [comment] 2020-03-07 06:44
@vvijayalakshmi21 See https://github.com/commons-app/documentation/blob/master/android/Volunteers-welcome!.md

**Comment by vvijayalakshmi21** [comment] 2020-03-09 04:28
Hi Nicolas, I have cloned the repo as mentioned in the guidelines. On reading about the exception from the above log file, it seems like it is more likely to occur in the cases when 1) Order of read and write in Parcelable is different, 2) the CREATOR is not mentioned as static in proguard. I checked the source code and upon checking I see that in our code both of them are rightly done.
I also read in one of the posts that such issue could happen when the app is kept open for a long time in the background and when a memory-consuming app is opened then this app will be cleared of the memory which leads to a crash when accessed again. Would it be possible to let me know how you reproduced this issue?
Do you think I can just change the order in one of the Parcelable codes to reproduce the crash and see what happens? Will this be a good start to approach? Kindly let me know your thoughts about this.

**Comment by sivaraam** [comment] 2020-03-10 06:57
> So it seems to be specific to the crash found in the empty_acra.txt above.

I just checked now and came to know that this really isn't specific to the crash observed by @nicolas-raoul. In my observation, for a crash that's different from the one observed by Nicolas:

* When I choose K-9 mail to send the mail I see the To, Subject and Body of the e-mail getting filled appropriately.
* When I choose Gmail to send the mail I only the To field gets filled. The Subject and Body are empty as initially observed by Nicolas

So, I really think the actual problem is the interaction with Gmail.

@vvijayalakshmi21 Can you verify this?

**Comment by vvijayalakshmi21** [comment] 2020-03-10 07:36
@sivaraam Just want to clear my understanding on this issue. The problem is that we are not seeing the attachment file (in the case of a crash in the app) in the composed mail when we use Gmail whereas other mail providers like K-9 works just fine. So I have to check if this could be replicated for any crash. Is that right? Kindly confirm

**Comment by sivaraam** [comment] 2020-03-10 08:12
@vvijayalakshmi21 I'm not sure about whether an attachment is added when you report crash but when I report a crash (read 'send a crash report email') using K-9 mail I see the To, Subject and Body fields of the e-mail filled correctly. Here's a screenshot of K-9 mail:
![Screenshot_2020-03-10-13-33-24](https://user-images.githubusercontent.com/12448084/76292107-92944200-62d4-11ea-96c5-acfb6c8ea860.png)

When I do the same reporting with Gmail only the To field gets filled. The Subject and Body are empty:
![Screenshot_2020-03-10-13-32-46](https://user-images.githubusercontent.com/12448084/76292168-b8214b80-62d4-11ea-9816-2be42f915333.png)

I know crash reporting works fine with K-9 mail but haven't tested other e-mail clients. Hope this helps. Let me know if need any other clarifications. 🙂

**Comment by vvijayalakshmi21** [comment] 2020-03-11 04:43
Thanks so much for this. I read a couple of S.Overflow posts related to this:

https://stackoverflow.com/questions/59314608/android-studio-mailto-intent-doesnt-show-subject-and-mail-body
https://stackoverflow.com/questions/59237274/email-intent-subject-is-ignored-in-gmail-but-works-with-other-mail-clients

I have been trying to replicate the issue and try out the above solutions using my emulator on Android studio but I have been having issues. Could you please help me out?

**Comment by sivaraam** [comment] 2020-03-11 06:09
> I have been trying to replicate the issue and try out the above solutions using my emulator on Android studio but I have been having issues. Could you please help me out?

Sure. Share the details about the issues you are facing. 🙂

**Comment by vvijayalakshmi21** [comment] 2020-03-13 04:41
The target device for the app is set as Pixel 3a API 28.
![image](https://user-images.githubusercontent.com/34595292/76590025-080d3780-64ba-11ea-88fb-aa735cf2d5f9.png)

I have been trying to run the emulator. The process is running in the background but I am not able to view the Emulator. 
![image](https://user-images.githubusercontent.com/34595292/76589946-d1372180-64b9-11ea-9456-ae853ad82a59.png)

I also tried to run the app on my device (Pixel 3a - same as the emulator I have configured) but I could not get it installed. 
![image](https://user-images.githubusercontent.com/34595292/76590374-d3e64680-64ba-11ea-8318-0b4e330d72b0.png)

I noticed that the apk is by default generated in the debug folder (../apps-android-commons\app\build\outputs\apk\beta\debug). Should I add a release config?

Requesting your help to get this fixed

**Comment by macgills** [comment] 2020-03-13 09:00
You can't install on your device? have you enabled usb debugging in developer settings?

You could also try a much lower spec emulator, I go for much smaller screens because even though the emulator has improved greatly over the years it is still awful.

**Comment by misaochan** [comment] 2020-03-13 09:55
There is no need to add a release config in order to test the app, debug should work. You may want to experiment with different kinds of virtual devices, and also make sure they are up to date. 

What exactly happens when you try with your real device?

**Comment by vvijayalakshmi21** [comment] 2020-03-17 04:54
The Android emulator does not show up even though the process is running in the background. I missed to enable the developer options and now I can install and run the app in my device but the debug points are not hit despite having USB debugging set to true

**Comment by sivaraam** [comment] 2020-03-17 06:01
> ... run the app in my device but the debug points are not hit despite having USB debugging set to true

The breakpoints work only if you run the debug variant of the app. You can do that by hitting the debug icon instead of the run icon in Android studio. This is how the debug icon would look like:
![image](https://user-images.githubusercontent.com/12448084/76826482-8fec9c00-6842-11ea-8346-16568eed4e5a.png)

Refer the following page for more information: https://developer.android.com/studio/debug/

**Comment by misaochan** [comment] 2020-03-25 10:56
I can confirm that this problem still happens for me on current master (I use Gmail).

@vvijayalakshmi21 , how are things going?

**Comment by neslihanturan** [comment] 2020-03-27 16:05
Hey @vvijayalakshmi21 , since this issue is a blocker for v2.13 release (urgent), ı may need to claim this one. By looking the comments above the last one sent 2 days ago, I feel like you are not around anymore and this should be okay for you. I hope this is ok for you :)

**Comment by vvijayalakshmi21** [comment] 2020-03-28 07:03
Hi, My sincere apologies for not responding here. I had been on quarantine with no access to my laptop. I totally understand the urgency of the issue. Please go ahead.

@misaochan or @nicolas-raoul Please could you assign me another issue to work on? I am available from today.

**Comment by nicolas-raoul** [comment] 2020-03-28 07:53
@vvijayalakshmi21 Sure, no problem, thanks for letting us know. How about #3117? :-)

**Comment by vvijayalakshmi21** [comment] 2020-03-30 06:28
Hi @neslihanturan Not sure if this has been already fixed. But just noticed that the logs DO get attached to Gmail when we click ''Send Log file" from Settings.
![Screenshot_20200330-115421](https://user-images.githubusercontent.com/34595292/77881978-aa9d1880-7225-11ea-8f28-9451d4a76f97.png)

**Comment by sivaraam** [comment] 2020-03-30 07:39
@vvijayalakshmi21 Those are not the logs we're concerned about in this issue. We're concerned about the crash logs not getting attached from (ACRA) crash dialog. After you face an app crash you are shown a dialog (by ACRA) that suggests you to send the logs via e-mail for further debugging. It looks something like the following:

![Screenshot_2020-03-30-13-05-56](https://user-images.githubusercontent.com/12448084/77887064-8d009b00-7287-11ea-9d5c-65589c28b66d.png)

When you use Gmail to complete that action the logs are not attached. That's the issue.

**Comment by vvijayalakshmi21** [comment] 2020-03-30 09:21
Hi @sivaraam, I think we're both highlighting the same point. It's from the acra dialog where the logs aren't attached to Gmail and not that the logs aren't attached to Gmail at all. Just wanted to drop this note if that'd be helpful in any way.

**Comment by misaochan** [comment] 2020-03-30 09:59
Thanks @vvijayalakshmi21 , it's interesting to see that Send Log File works but not ACRA. That does help us narrow the potential causes indeed.

**Comment by neslihanturan** [comment] 2020-03-30 11:18
I found a very similar issue is mentioned here, and it is told that fixed from Gmail side: https://github.com/ACRA/acra/issues/744

**Comment by neslihanturan** [comment] 2020-03-30 14:17
Well an interesting detail,if I change ACRA configuration to send the stacktrace as file, instead of text as:
```
@AcraMailSender(
        mailTo = "commons-app-android-private@googlegroups.com",
        reportAsFile = true,
        reportFileName = "test"
)
```
It works with gmail too. But if I set it to false as 
```
@AcraMailSender(
            mailTo = "commons-app-android-private@googlegroups.com",
            reportAsFile = false
    )
``` 
It does not work this time.

**Comment by misaochan** [comment] 2020-03-31 09:54
As I discussed with Neslihan, my main concern with switching to files is that it will be difficult to search the google groups forum for a particular crash or version number. Currently in a forum thread we can see everything directly without needing to download them one by one.

But on the other hand, we already have access to crashes on the Dev Console so we would only be using ACRA to get user comments for the most part (or for users who did not consent to google collecting crash info from them). So it may be a "good enough" fix if we can't find a better one.

**Comment by sivaraam** [comment] 2020-03-31 10:28
> (or for users who did not consent to google collecting crash info from them). 

Just curious, how do users do that? I don't see an option in the app's settings that says it to use ACRA instead of Google's crash reporting 🤔 

Also, I only remember seeing the ACRA dialog during a crash. I don't remember seeing the Google's crash reporting dialog when the app crashes. Do we show that only for the *stable* versions released to play store? I ask this because I mostly just use alpha play store version (or) beta versions and don't remember denying any consent to use Google's crash reporting.

**Comment by misaochan** [comment] 2020-03-31 11:37
> Just curious, how do users do that? 

I believe there is an Android system setting for users to say "automatically share diagnostics and crash data" or not. 

> I don't see an option in the app's settings that says it to use ACRA instead of Google's crash reporting

It doesn't really work as a binary choice. Basically, if the user allows the above Android setting, Google will automatically collect crash stats from their phone for us (and all other apps) in the dev console. Additionally, an ACRA dialog pops up when a crash happens in OUR app, and the user can make an additional choice to email us their stack trace or not.

> Also, I only remember seeing the ACRA dialog during a crash. I don't remember seeing the Google's crash reporting dialog when the app crashes. 

Google does not have a dialog. :)

**Comment by sivaraam** [comment] 2020-03-31 18:12
> I believe there is an Android system setting for users to say "automatically share diagnoscs and crash data" or not.
> 

Thanks for the tip. There does seem to be a [setting for the diagnostics](https://support.google.com/accounts/answer/6078260).

> It doesn't really work as a binary choice. Basically, if the user allows the above Android setting, Google will automatically collect crash stats from their phone for us (and all other apps) in the dev console. You can see more about that here: [support.google.com/googleplay/android-developer/answer/6083203?hl=en](https://support.google.com/googleplay/android-developer/answer/6083203?hl=en)
> 
> Additionally, an ACRA dialog pops up when a crash happens in OUR app, and the user can make an additional choice to email us their stack trace or not.
>

Ah. Now I see what you're saying. Thanks for the clarification.
 
> > Also, I only remember seeing the ACRA dialog during a crash. I don't remember seeing the Google's crash reporting dialog when the app crashes.
> 
> Google does not have a dialog. :)

I'm not sure about this part though. When I said Google's crash report dialog the following is what I had in mind.

![Screenshot_2020-03-31-18-39-34](https://user-images.githubusercontent.com/12448084/78058960-b9f79f80-73a6-11ea-8a29-e7da78f70434.png)

This is what I see when I tap on "Report":
![Screenshot_2020-03-31-18-39-50](https://user-images.githubusercontent.com/12448084/78060214-c8df5180-73a8-11ea-898d-45873c99804b.png)

I thought you were speaking of the crash reporting done via this method and was curious to know how a user can prevent this dialog from happening. FYI: I have 'Usage & Diagnostics' turned off and still see this dialog. So, I think it's unrelated to that.

In case anyone is curious the app for which I saw the above crash dialog is opensource and can it's source code can be found at https://github.com/TeamAmaze/AmazeFileManager

Anyways, thanks for the clarification @misaochan.

**Comment by sivaraam** [comment] 2020-03-31 19:00
Ok. Coming back to the topic of the issue. I actually noticed an interesting thing. When the size of the crash log is small the crash logs are filled in the the mail body just fine even when I use Gmail.

![Screenshot_1585662482](https://user-images.githubusercontent.com/12448084061914-8bc88e80-73ab-11ea-9a4e-58f3464e1162.png)

I observed this in the emulator (Nexus 5 API 24) but am _unable to_ observe the same behaviour in my Samsung SM-J111F i.e., the logs are _not filled in_ the mail body even when they are relatively small. cc @neslihanturan

**Comment by neslihanturan** [comment] 2020-04-02 13:53
It is very unexpected to get different results based on devices. My suggestion is merging #3605 before release if we don't find a better approach to be able to get crash logs in a way. Meanwhile I will continue to look for root cause. Thanks @sivaraam your findings seems really helpful.

**Comment by macgills** [comment] 2020-04-06 09:32
I am in favor of merging and have approved the pr.

**Closed** 2020-04-06 18:58 UTC
Labels: assigned, bug
