### ISSUE TITLE
Files renamed to .jpeg in 2.8.0

### ISSUE THREAD

**Issue by PeterFisk** [commons-app/apps-android-commons#1825] opened 2018-08-14 06:39 UTC
**Summary:** 
When uploading photos via the share button (in Android) and choosing "upload to commons", the files are renamed to _.jpeg_. When uploading within the app itself, the files remains as _.jpg_.

**Steps to reproduce:** 
Use Gallery (in Android); select an image; share; upload to commons; give the file a name (without extension); add categories and send.

The problem was not present in 2.7.2.

**Add System logs:**
[logs_PeterFisk.txt](https://github.com/commons-app/apps-android-commons/files/2285741/logs_PeterFisk.txt)

(Log for when I uploaded inside the app (at 08:08) and when I uploaded via share button (at 08:24).

https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/PeterFisk&ilshowall=1

**Device and Android version:** 
Samsung Galaxy S9, SM-G960F
Android 8.0.0
Stock version Samsung Experience 9.0
 
 **Commons app version:** 
2.8.0

**Would you like to work on the issue?**
No, I'm not qualified.

**Comment by misaochan** [comment] 2018-08-14 07:40
Thanks for creating the issue, Peter.

@neslihanturan do you think we might have changed this by accident during the upload workflow overhaul?

At any rate, hopefully it will be a fairly simple fix. :)

**Comment by VaishSiddharth** [comment] 2018-08-14 09:00
@misaochan I would like to work on this.

**Comment by VaishSiddharth** [comment] 2018-08-14 17:44
@misaochan I am trying to reproduce this error in master branch but the upload fails. (build varient prodDebug)

**Comment by neslihanturan** [comment] 2018-08-14 17:47
Oh, probably I am responsible with this issue. @VaishSiddharth you can reproduce the issue on 2.8.0 branch

**Comment by VaishSiddharth** [comment] 2018-08-14 17:51
@neslihanturan Still the same problem, not able to upload any image.

**Comment by PeterFisk** [comment] 2018-08-14 18:39
The .jpeg problem exists in 2.8.1 too. You probably knew that.

Den tir. 14. aug. 2018, 19:51 skrev Siddharth Vaish <
notifications@github.com>:

**Comment by neslihanturan** [comment] 2018-08-14 18:42
Can you please share your logs under upload fails issue @VaishSiddharth ?

**Comment by neslihanturan** [comment] 2018-08-14 18:54
@VaishSiddharth if your uploads fails with no reason, please do not reinstall the app. Because we might need you to help with testing. After we propose a solution, you can verify if it is worked or not. Because most of us couldn't reproduce the issue.

**Comment by VaishSiddharth** [comment] 2018-08-14 18:58
@neslihanturan Ok I will not reinstall the app. I will share the logs.

**Comment by VaishSiddharth** [comment] 2018-08-15 16:15
@neslihanturan Here are the logcats
08-15 21:43:12.046 8119-8119/fr.free.nrw.commons E/ANDR-PERF: IPerf::tryGetService failed!
08-15 21:43:12.437 8119-8119/fr.free.nrw.commons E/ANDR-PERF: IPerf::tryGetService failed!
08-15 21:43:12.587 8119-8119/fr.free.nrw.commons E/ANDR-PERF: IPerf::tryGetService failed!
08-15 21:43:12.690 8119-8119/fr.free.nrw.commons E/ANDR-PERF: IPerf::tryGetService failed!
08-15 21:43:13.627 8119-8119/fr.free.nrw.commons E/ANDR-PERF: IPerf::tryGetService failed!
08-15 21:43:13.671 8119-8119/fr.free.nrw.commons E/ANDR-PERF: IPerf::tryGetService failed!
08-15 21:43:13.872 8119-8119/fr.free.nrw.commons E/ANDR-PERF: IPerf::tryGetService failed!
08-15 21:43:23.893 8119-8119/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 8119
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x52 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by misaochan** [comment] 2018-08-15 17:03
@VaishSiddharth Just checking that you are running the latest version of master (with all the recent changes)? Could you link to the most recent commit in your local build? Thanks!

**Comment by VaishSiddharth** [comment] 2018-08-15 17:12
@misaochan Please have a look
commit 61888f7456b723ded88caa7c822f0bea060dffe8 (HEAD -> master, upstream/master)
Merge: 2fdcddd9 b17957db
Author: misaochan <josephinelim86@gmail.com>
Date:   Tue Aug 14 17:59:48 2018 +1000

    Merge remote-tracking branch 'refs/remotes/origin/2.8-release'

commit b17957dbb1e12119aef4dcd479c2ac1b791cea50 (upstream/2.8-release, 2.8-release)
Author: Josephine Lim <josephinelim86@gmail.com>
Date:   Tue Aug 14 17:58:32 2018 +1000

    Versioning and changelog for v2.8.1 (#1827)
    
    * Versioning for v2.8.1
    
    * Update changelog.md
    
    * Fix changelog.md typo

commit 7dee0a45b1e12aa61671d64e301e115b26277484
Author: Vivek Maskara <maskaravivek@gmail.com>
Date:   Mon Aug 13 22:17:23 2018 +0530

    Fix category edits (#1823)

commit 2fdcddd977766c1d9e0ca03d859a82f0c65785da
Author: translatewiki.net <l10n-bot@translatewiki.net>
Date:   Mon Aug 13 08:08:25 2018 +0200

    Localisation updates from https://translatewiki.net.

commit a694ff1887da3486626c7689635a961eb969ef64
Author: Amir Aharoni <amir.aharoni@mail.huji.ac.il>
Date:   Sat Aug 11 14:30:55 2018 +0300

    Fixes in grammar and punctuation in English translatable messages

commit 81053a13b5dac8ba52cc4ad86cdd372d4ae42c53
Author: Siddharth Vaish <36266597+VaishSiddharth@users.noreply.github.com>
Date:   Fri Aug 10 00:45:57 2018 +0530

    Username in nav drawer centrally aligned #1806 (#1817)

commit 654ef80ff7f7324935670feb542c6c3a532cac4a
Author: Siddharth Vaish <36266597+VaishSiddharth@users.noreply.github.com>
Date:   Fri Aug 10 00:45:31 2018 +0530

    Renamed Set wallpaper to Set as wallpaper #1813 (#1818)

commit 56675c91a48a7733953c88361ba85dbc3ce989bb
Author: translatewiki.net <l10n-bot@translatewiki.net>
Date:   Thu Aug 9 09:20:21 2018 +0200

    Localisation updates from https://translatewiki.net.

commit 78cab495443233b7bf7e5f62d26c190c21624dc8
Merge: fa13c1b4 98ed7beb
Author: Nicolas Raoul <nicolas.raoul@gmail.com>
Date:   Wed Aug 8 16:48:57 2018 +0900

    Merge branch 'master' of github.com:commons-app/apps-android-commons

commit 98ed7beb3358d47e3c0582e6f0835b9ba297e1bc
Merge: e00f69a2 634814e9
Author: misaochan <josephinelim86@gmail.com>
Date:   Wed Aug 8 17:38:01 2018 +1000

    Merge remote-tracking branch 'refs/remotes/origin/2.8-release'

commit 634814e9d027ec75faf0f13d257d27dcc167f5c0
Author: Josephine Lim <josephinelim86@gmail.com>
Date:   Wed Aug 8 17:36:56 2018 +1000

    Versioning and changelog for v2.8.0 (#1812)
    
    * Increment version number to 87
    
    Because 86 used for alpha release
    
    * Update changelog.md

commit bf50e749ece7ceba65be26d4fa5f8eec783dd9f2
Author: Ujjwal Agrawal <ujjwal@codenicely.in>
Date:   Wed Aug 8 12:45:06 2018 +0530

    Fixes #1801 (Media details view for Browse is lacking author field)  in 2.8-release branch (#1810)
    
    * In media search results, rotating screen triggers crash fixed #1753
    
    * Updated API to get Author name too
    
    * Crash fixed due to notifyDataSetChange
    
    * search API duplicate images fixed

commit fa13c1b4f8d070d785ae7e2912e75bb2447660c7
Merge: e00f69a2 825a5290
Author: Nicolas Raoul <nicolas.raoul@gmail.com>
Date:   Wed Aug 8 16:07:22 2018 +0900

    Merge branch 'fix_skip_login_nearby_bug' of github.com:ujjwalagrawal17/apps-android-commons

commit e00f69a23d0ec98b98919b7a842b83fb20e2a7c7
Merge: 87b6568a a5d4e8f7
Author: Nicolas Raoul <nicolas.raoul@gmail.com>
Date:   Wed Aug 8 15:07:51 2018 +0900

    Merged from 2.8-release

commit 87b6568abeb18e37bc65f590931e714c26e6cca7
Author: Ujjwal Agrawal <ujjwal.iitism@gmail.com>
Date:   Wed Aug 8 04:12:06 2018 +0530

    search API duplicate images fixed

commit ecebe4c584a99383b553ee74837bf402415ec6cd
Author: Ujjwal Agrawal <ujjwal.iitism@gmail.com>
Date:   Wed Aug 8 03:37:48 2018 +0530

    Crash fixed due to notifyDataSetChange

commit c93bcda6f69b60f1f0a40475f1227479c56497d1
Author: Ujjwal Agrawal <ujjwal.iitism@gmail.com>
Date:   Wed Aug 8 01:02:41 2018 +0530

    Updated API to get Author name too

commit 825a529003dbb13198bf2b245d9c9abf930429c4
Author: Ujjwal Agrawal <ujjwal.iitism@gmail.com>
Date:   Tue Aug 7 23:12:28 2018 +0530

    Changed default value of skip login to false

commit a5d4e8f7395fb2595c16257f5ffb76473c0a14fd
Author: Tanvi Dadu <tanvidadu1998@gmail.com>
Date:   Sun Jul 29 00:58:39 2018 +0530

     changed Icon (#1759)

commit b5e90bea7635ffdb026ccba6f766105090efe19d
Author: Vivek Maskara <maskaravivek@gmail.com>
Date:   Tue Aug 7 14:33:59 2018 +0530

    Wikidata edit fix (#1800)
    
    Wikidata edit fix

commit f12f1d50a300ad595ffdf0a0f14f82b0d2bccba4
Merge: 23014e07 bf58fcab
Author: Nicolas Raoul <nicolas.raoul@gmail.com>
Date:   Tue Aug 7 13:12:00 2018 +0900

    Merge branch 'skip_login' of github.com:ujjwalagrawal17/apps-android-commons

commit 23014e07c8f5e4889f5618987e61dd8d0a9519a0
Merge: 6f86299a 143ad001
Author: misaochan <josephinelim86@gmail.com>
Date:   Mon Aug 6 18:36:35 2018 +1000

    Merge remote-tracking branch 'refs/remotes/origin/2.8-release'

commit 6f86299a908a3e71d5ce4c1447b989b73d9f6c5d
Author: translatewiki.net <l10n-bot@translatewiki.net>
Date:   Mon Aug 6 07:15:25 2018 +0200

    Localisation updates from https://translatewiki.net.

commit 143ad00149156e9c7dea292b1a975ecc115a17f3
Author: Vivek Maskara <maskaravivek@hotmail.com>
Date:   Sun Aug 5 01:26:00 2018 +0530

    Fix failed uploads (#1790)
    
    * Cusom Mediawiki api layer
    
    * Fix tests

commit b73535f62136eaeb61fe18b88e2c3f35a9ff185d
Author: Ashish Kumar <ashishkumar468@gmail.com>
Date:   Sat Aug 4 21:33:57 2018 +0530

    added null check before initialising LatLng after receiving location … (#1791)
    
    * added null check before initialising LatLng after receiving location permission
    
    * flipped null==lastKL with lastKL==null

commit e32f8d3d361fc54d2f012245ff6fe0092a7c92f5
Author: Josephine Lim <josephinelim86@gmail.com>
Date:   Sun Aug 5 02:03:31 2018 +1000

    Fix title/desc prefill bug (#1794)
    
    * Move isDirectUpload putExtra above Wikidata edits try catch block
    
    * Check value of boolean isDirectUpload in intent
    
    * Change to getBooleanExtra to prevent NPE
    
    * Fix whitespaces, logging, and lint issues

commit ff9f43ef8b5f501caea8ae8ffcf9a3e496174c55
Author: Josephine Lim <josephinelim86@gmail.com>
Date:   Sun Aug 5 01:43:10 2018 +1000

    Only do http logging if a debug build is run (#1795)

commit f46da6639cdd0433e4454907322ea1a6dc351321 (upstream/upload-overhaul)
Merge: 18fbd475 12a83da3
Author: misaochan <josephinelim86@gmail.com>
Date:   Sat Aug 4 19:29:55 2018 +1000

    Merge branch 'master' of https://github.com/commons-app/apps-android-commons

commit 18fbd47535a03aad6050c685024774dfb3ef39ff
Merge: 386bd0a1 d29aa2e2
Author: misaochan <josephinelim86@gmail.com>
Date:   Sat Aug 4 19:29:50 2018 +1000

    Merge remote-tracking branch 'refs/remotes/origin/2.8-release'

**Comment by misaochan** [comment] 2018-08-16 07:15
@VaishSiddharth That looks correct, thanks! For the logs, we will need much longer logs than that (as there is nothing usable in that log :)). Generally what I do is open the app, tap the upload from gallery button in the app, clear logcat (the dustbin button in Android Studio), and then proceed with image selection and upload. Then copy EVERYTHING from your logcat and paste it here, using the GitHub code markup. You may want to use a word processor first to remove your IP/location.

I will reopen the failed upload issue for you, please post it there, thanks so much!

**Comment by misaochan** [comment] 2018-08-19 17:01
If anyone is having trouble reproducing this, it may be worth trying a few different emulators/devices/APIs. My API 24 Nexus One emulator cannot reproduce this problem (even if I upload via Share, my images are .jpg), but my API 26 Samsung Galaxy S7 can.

**Comment by misaochan** [comment] 2018-10-05 17:35
Should be fixed, see #228

**Closed by misaochan** 2018-10-05 17:35 UTC
Labels: beginner friendly, bug
