### ISSUE TITLE
App keeps toggling between Home and Notifications and then crashes

### ISSUE THREAD

**Issue by ShridharGoel** [commons-app/apps-android-commons#2196] opened 2018-12-20 16:57 UTC
**Summary:** 

App keeps toggling between Home and Notifications and then crashes when notifications is visited through the bell icon.

**Steps to reproduce:** 

1. Use the bell icon on the top-right of Home to go to Notifications.
2. Press back, Home will open.
3. Press back again, it will go to Notifications.
4. This will repeat.
5. Doing this many times crashes the app.

Instead, the app should have closed on pressing back when on the Home screen.

**System logs for the crash:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences fr.free.nrw.commons.contributions.MainActivity.getSharedPreferences(java.lang.String, int)' on a null object reference
        at fr.free.nrw.commons.notification.UnreadNotificationsCheckAsync.onPostExecute(UnreadNotificationsCheckAsync.java:51)
        at fr.free.nrw.commons.notification.UnreadNotificationsCheckAsync.onPostExecute(UnreadNotificationsCheckAsync.java:18)
        at android.os.AsyncTask.finish(AsyncTask.java:667)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6205)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

```

**Device and Android version:** 

Android 7.1.2 (API 25)
 
**Commons app version:** 

2.9.0
Branch: master
Build: betaDebug

**GIF:** 

![ezgif com-video-to-gif 9](https://user-images.githubusercontent.com/35566748/50298858-32826780-04a6-11e9-988d-a7834f3dc7d5.gif)

**Would you like to work on the issue?**

Yes

**Comment by domdomegg** [comment] 2018-12-20 16:59
Duplicate of #2044 which has fix ready in #2102

**Closed by domdomegg** 2018-12-20 16:59 UTC
