### ISSUE TITLE
Integrating crash report service with crashlytics(fabric)

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1312] opened 2018-03-15 12:15 UTC
**Observed Behaviour**

Currently, there is no crash tracking service in the app now.

**Expected Behaviour**

There should be a crash tracking service.

**Steps to Reproduce** 

Integrating Fabric crash report service with crashlytics.
Web URL: https://fabric.io/

**Would you like to work on the issue?**

Yes.

**Comment by ujjwalagrawal17** [comment] 2018-03-15 12:18
We will need an API key for adding this feature.

**Comment by nicolas-raoul** [comment] 2018-03-15 12:36
We are already using the open source https://github.com/ACRA/acra for that.

Crash reports are sent to the private mailing list https://groups.google.com/forum/#!forum/commons-app-android-private

Strangely the crash reports seem to have stopped arriving to the mailing list in January, not sure why, any idea @misaochan ?

We should probably switch to using the same thing as the Wikipedia app.

**Comment by misaochan** [comment] 2018-03-15 13:55
@nicolas-raoul Good point, I have no idea! :/ We should probably look into that.

What is the Wikipedia app using again?

**Comment by Bluesir9** [comment] 2018-03-15 15:11
It looks like Wikipedia uses [Hockey](https://www.hockeyapp.net/)

**Comment by nicolas-raoul** [comment] 2018-03-16 02:48
Hockey is proprietary, that's surprising.
As crash reports contain private information, it might be worth asking WMF.

**Comment by maskaravivek** [comment] 2018-04-07 19:49
Lets, keep the issue open for discussion. IMO if WMF approves it would be great to have fabric crashlytics integrated. It would make tracking crashes/non-fatals much easier. 

@dbrant Any opinion on using crashlytics from a privacy standpoint?

**Comment by domdomegg** [comment] 2018-12-19 22:33
Duplicate of #858

**Closed by domdomegg** 2018-12-19 22:33 UTC
