### ISSUE TITLE
Image downloading fails

### ISSUE THREAD

**Issue by gupta-meghna64** [commons-app/apps-android-commons#1216] opened 2018-02-27 04:35 UTC
### Summary
Clicking the download button after going to My Recent Recent Uploads fails to download an image to the phone's storage even when the app has been granted Storage Permission.

### Screenshots

![whatsapp image 2018-02-27 at 9 09 05 am 2](https://user-images.githubusercontent.com/20908024/36710487-50a884c4-1ba4-11e8-967e-e74c2558c918.jpeg)
![whatsapp image 2018-02-27 at 9 02 21 am 2](https://user-images.githubusercontent.com/20908024/36710504-6945a16a-1ba4-11e8-9e03-e924da415b56.jpeg)

### System Logs
The log report can be found at this link:
[Log Report File](https://docs.google.com/document/d/1iFANGofxS37m9KHb7kZIQOdNAK3aybGCTXPTFY6m8vs/edit?usp=sharing)

### Device and Android version
Redmi Note 3
6.0.1 MMB29M
MIUI Version: MIUI Global 8.5
 
 **Commons app version:** 
2.6.7

**Comment by knight-shade** [comment] 2018-02-27 06:14
Yup @gupta-meghna64 , I can confirm the issue.
**Device and Android Version**
Android 7.0 MIUI Global V9.0 

Can I take up this issue?

**Comment by gupta-meghna64** [comment] 2018-02-27 06:26
Let us wait for a confirmation @knight-shade

**Comment by VojtechDostal** [comment] 2018-02-27 09:34
That's really weird but I confirm that I cannot download images either. ("Download Failed")

**Comment by maskaravivek** [comment] 2018-02-27 10:16
Please feel free to take up the issue. @gupta-meghna64 or @knight-shade.

**Comment by gupta-meghna64** [comment] 2018-02-27 10:26
I'd like to explore about the issue and work on it :-)

**Comment by knight-shade** [comment] 2018-02-27 16:50
@gupta-meghna64 didn't realised this issue was assigned to you, although this might be useful for you:

The following two options appear before you select the download one:

![whatsapp image 2018-02-27 at 9 10 02 pm 2](https://user-images.githubusercontent.com/20313518/36738168-e633da6c-1c02-11e8-9325-493d1599a46a.jpeg)

The reason why all the downloads are unsuccessful is both the urls of the above options are different, just for example in case of image I uploaded:

View in Browser url : 
https://commons.m.wikimedia.beta.wmflabs.org/wiki/File:Madhugiri_fort.jpg

Download url: 
https://upload.beta.wmflabs.org/wikipedia/commons/6/64/File%3AMadhugiri_fort.jpg

The Download url is the one which leads to 404 error, hence obviously download being unsuccessful because there is no image existing at that url.

The correct download url should be:
https://upload.beta.wmflabs.org/wikipedia/commons/0/0c/Madhugiri_fort.jpg

The below picture lists the necessary changes( ~ just 2 lines), after which all downloads are successful.
![solution](https://user-images.githubusercontent.com/20313518/36740988-012cdb32-1c0a-11e8-970d-a7007aa4982a.png)

I have tested the solution on real device and  attached a gif below illustrating successful download of image:
![uploadsolution](https://user-images.githubusercontent.com/20313518/36741452-27563596-1c0b-11e8-9740-8df69e7a367a.gif)

@maskaravivek, @gupta-meghna64  AFAIK very likely 99% :) this problem is caused due to issue mentioned in #1169 . 
Can you verify the same ?

**Comment by gupta-meghna64** [comment] 2018-02-27 17:47
@knight-shade The base imageUrl that you have specified in the code as https://upload.beta.wmflabs.org/wikipedia/commons/0/0c/ isn't the same for every image being uploaded. In my case, the base url turns out to be 
https://upload.beta.wmflabs.org/wikipedia/commons/b/bd/

So, I guess we'll have to find out an alternative way of fetching the base URL instead of hard-coding it.

**Comment by knight-shade** [comment] 2018-02-27 17:51
@gupta-meghna64 , Uh ohh, this concern came to mind though, I think it varies for each user, is it?
Better solution might be just make the backend much bettter.

**Comment by gupta-meghna64** [comment] 2018-02-27 18:07
@knight-shade The URL generated in the case of images with no spaces in the name is perfect, and the downloading is also taking place. But the problem comes when the image that has been uploaded has a space/special symbol in the name because of which the imageURL being generated is incorrect.

**Comment by knight-shade** [comment] 2018-02-28 04:35
@gupta-meghna64 I have come up with a fix, shortly will update in detail.

**Comment by gupta-meghna64** [comment] 2018-02-28 10:54
@knight-shade It's working :-)

**Comment by VojtechDostal** [comment] 2018-02-28 10:59
A few difficult file names to check:

- File:ČSD ř. M 260.001 1939-02.17. 24.jpg
- File:دمشق جبل قاسيون.jpg

Does the regex work for them?

**Comment by knight-shade** [comment] 2018-02-28 12:01
Currently the app crashes for filenames which are not in english, trying to work on the issue.

**Comment by gupta-meghna64** [comment] 2018-02-28 13:44
@knight-shade Since you've already figured out the solution, I request you to put a PR to this and @VojtechDostal and @maskaravivek to re-assign the issue to @knight-shade

**Comment by knight-shade** [comment] 2018-02-28 15:31
@gupta-meghna64 , now again it will take more time to re-assign the task, its hardly a line, and since its already assigned to you, I request you to make the PR kindly. :ok_hand:

**Closed** 2020-08-14 09:35 UTC
Labels: assigned, bug
