### ISSUE TITLE
Position is  not updated by nearby 

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#674] opened 2017-05-25 13:04 UTC
It is still possible to get a empty Nearby list with GPS turned on and position available.

Steps to reproduce in emulator:
1) Turn off GPS
2) Go to Nearby list (don't turn on GPS)
3) In NearbyActivity `curLatLong` will be `null`.
4) List is empty
5) Turn on GPS
6) Go to home screen
7) Back to nearby.
8) In NearbyActivity `curLatLong` will still be `null`.
9) Change location using the emulator.
10) This fires in `LocationServiceManager` the `onLocationChanged` method.
11) Next refresh will now again contain items.

Waiting for Android to detect a location change might not be the best way to get the current location.

**Comment by misaochan** [comment] 2017-06-02 07:23
Would like to bump this if possible, as this is the last major roadblock before we can push all the new features to production - production is currently missing all the improvements we made during the hackathon due to us having to resolve these bugs. ( #650 is also needed, but I'm currently working on that in #707 and that should be merge-ready soon).

**Comment by sivaraam** [comment] 2017-09-06 19:13
Just to be sure has this been fixed by #707?

**Comment by nicolas-raoul** [comment] 2017-09-07 03:09
@sivaraam  Not sure... would you mind testing the reproduction steps described in the issue? Thanks!

**Comment by misaochan** [comment] 2017-09-07 09:54
#707 was not meant to fix this, it was made to fix #650 . It's possible that this might have been fixed along with one of the refactors done in the past few months, but as far as I'm aware, there hasn't been any direct attempt at fixing this.

**Comment by sivaraam** [comment] 2017-09-13 10:39
> @sivaraam Not sure... would you mind testing the reproduction steps described in the issue? Thanks!

I tried but it seems to be //worser// than what's described in the description. I don't get any items in 'nearby' until the nearby activity gets created again after a location change has been triggered even if I hit the refresh button. When I say the nearby activity gets created again I mean the following scenarios,

- I //hit the back button// when I'm in the nearby and get back to 'nearby' screen
- I remove the app from the recent list and then open it and go to the 'nearby' screen

Seems somebody has played with the activity life cycle. Anyways, I guess it's better to ensure this by asking the person who started this issue, @tobias47n9e

**Comment by misaochan** [comment] 2017-09-13 11:54
@sivaraam To clarify, which version of the app are you experiencing that issue with? Pre-release (current master), release (beta or production)?

**Comment by sivaraam** [comment] 2017-09-13 12:49
@misaochan My bad, I tested that with the current master.

**Comment by misaochan** [comment] 2017-09-13 14:55
@sivaraam Would it be possible for you to test the current beta release and see if the same issue exists with that? Then at least we'll know if the worsened issue was introduced with a recent PR.

Thanks!

**Comment by sivaraam** [comment] 2017-09-14 11:59
> @sivaraam Would it be possible for you to test the current beta release and see if the same issue exists with that for you? Then at least we'll know if the worsened issue was introduced with a recent PR.

Just a little curious, Is there no way to test the beta other than to get it from the play store?  IOW, is there any way to get the beta from the source? (I don't see any tags for the beta since version 2)

**Comment by misaochan** [comment] 2017-09-15 14:43
You can get the latest beta from https://github.com/commons-app/apps-android-commons/releases (v2.5.0). Should they be tagged differently? Betas are almost always moved to production a few days to a week after they are published in beta (the recent version is the only exception).

**Comment by sivaraam** [comment] 2017-09-15 15:26
> Should they be tagged differently?

I'm actually accustomed tags like [this](https://github.com/wikimedia/apps-android-wikipedia/tags). So, I thought the beta's tag would contain the word 'beta'. I find it to be more communicative.

**Comment by misaochan** [comment] 2017-09-18 04:43
The Wikipedia app actually has a separate "beta" app though, doesn't it? So in their case it would make sense to tag beta and production versions separately since they are actually different builds, in my view. In our case the exact same APK makes its way from beta to production with a push of the button in the Play Store a few days later (most of the time), we don't have a dedicated beta app. Would be great to hear others' comments on this, I'm happy to change my tagging style if there is a consensus. :)

**Comment by nicolas-raoul** [comment] 2017-09-18 06:56
My understanding is that two different things are called "beta":
- "beta" in Google Play: Before going to all users, the APK first stays for a few days as a "beta" in Google Play, being delivered only to people who have subscribed for beta in Google Play
- "beta" in Gradle: Dedicated to testing, these APKs should never be uploaded to the current Google Play app. Creating a new Google Play app (like Wikipedia does) is doable, but I tend to think it would be overkill, as people who want to use the test Commons server are only a handful, and all already have Gradle.

**Comment by janpio** [comment] 2017-09-18 09:39
The [Wikipedia Beta](https://play.google.com/store/apps/details?id=org.wikipedia.beta) app is actually a #3:

* "beta" in the sense of "Wikipedia Beta" goes to the same servers as the release version (in contrast to the "Gradle beta") but is published before the changes are promoted to the real Wikipedia app. It enables users to have the prodution and beta app installed at the same time and switch between the two how they see fit. (Using the "beta" lane in Google Play does not enable this)

**Comment by janpio** [comment] 2017-09-18 09:41
Different names might be:

1. Beta Rollout (in Google Play)
1. Debug or development Build (via Gradle)
1. Preview Release (in Google Play)

**Comment by sivaraam** [comment] 2017-09-19 06:15
> It enables users to have the prodution and beta app installed at the same time and switch between the two how they see fit. (Using the "beta" lane in Google Play does not enable this)

I think that's why the Wikipedia app has a separate beta (but as has been felt by it's users it's stability is almost equal to that of production).

**Comment by sivaraam** [comment] 2017-09-19 07:44
@sivaraam Would it be possible for you to test the current beta release and see if the same issue exists with that for you? Then at least we'll know if the worsened issue was introduced with a recent PR.

Getting back to where I left off. Yeah, I get the same behaviour as described in [my comment](https://github.com/commons-app/apps-android-commons/issues/674#issuecomment-329129076) in the current beta release.

Note: I'm testing this on an emulated device.

**Closed** 2017-10-26 15:30 UTC
Labels: bug, high priority, nearby
