### ISSUE TITLE
When the coordinates have been copied from another picture, explain it in description

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4700] opened 2021-11-08 14:26 UTC
When a picture has no EXIF coordinates and another picture taken shortly before or after has some, the app asks the user whether they want to use the same coordinates.

That's a great feature, but we should write something like this in the description:

> The coordinates are not the exact coordinates, but the person who uploaded this picture thinks they are close enough.

In a subsequent phase, we could even link to the picture the coordinates have been taken from, if it is present on Commons.

Steps to reproduce:
1. Make sure your camera app has location enabled.
2. Take two pictures, one after the other very quickly (within 2  seconds). Let's call them picA and picB.
3. Using an EXIF modification tool, remove the location of picB.
4. Using your stock gallery app, select both and share to Commons.
5.  When the metadata form for picB comes, it should show the dialog that asks whether you want to use picA's coordinates. Say yes.
6. Finish the upload.
7. Check the resulting uploads and their descriptions.

**Comment by misaochan** [comment] 2021-11-09 10:32
Sounds good. Should be a good first issue too since it's just a text change, what do you think? :)

**Comment by nicolas-raoul** [comment] 2021-11-09 10:48
Indeed it is a good first issue. The main difficulties are:
- set a flag or something when the coordinates are taken from another picture.
- append the message above to the English-language description, or set it as the English-language description if the user has set none.

**Comment by ujjman** [comment] 2021-11-23 16:06
can I work on this @nicolas-raoul?

**Comment by nicolas-raoul** [comment] 2021-11-24 00:53
@ujjman Yes thanks! Please let us know about your progress every few days at least :-)

**Comment by ujjman** [comment] 2021-11-24 16:22
made the PR @nicolas-raoul

**Comment by ArmanNavodia** [comment] 2023-02-21 13:54
I want to work on this issue but I am not able to reproduce the issue in my emulator (pixel 5 API 31) can you provide steps to reproduce the issue? i.e I am not able to get use coordinates from another picture dialog.

**Comment by nicolas-raoul** [comment] 2023-02-21 22:06
@ArmanNavodia Steps added, thanks for the feedback! 🙂

**Comment by nicolas-raoul** [comment] 2023-02-21 22:07
@ArmanNavodia Steps added, thanks for the feedback! 🙂

**Comment by ArmanNavodia** [comment] 2023-02-23 08:19
I followed all the steps in emulator (pixel 5 API 31) and Redmi note 10s (android 12)  but not able to reproduce the bug. When ever I try to upload photo from gallery it says no location found even I tried to explicitly add the location using google photos and EXIF data modifier but still facing the same issue of no location found.

**Comment by nicolas-raoul** [comment] 2023-02-23 10:03
@ArmanNavodia You are probably hitting #5015.
Can you please try with an Android 9 emulator?

**Comment by nicolas-raoul** [comment] 2023-03-03 05:02
@ujjman Are you still working on this?

**Comment by nicolas-raoul** [comment] 2023-03-03 05:16
@ArmanNavodia You can upload pictures from https://drive.google.com/drive/folders/1T5wfM16qb78XCvnf1Zunww4neg8BXJj6?usp=sharing
If all pictures there have been uploaded already, or if the pictures do not contain EXIF location, please let me know. Thanks!

**Comment by ArmanNavodia** [comment] 2023-03-05 10:53
@nicolas-raoul could this be a fix for this issue??
https://user-images.githubusercontent.com/77919824/222956119-3ce33e0c-d5fb-4894-9234-c234aa497805.mp4

**Comment by nicolas-raoul** [comment] 2023-03-06 07:35
@ArmanNavodia Yes, it looks great! :-)
And sorry for the typo in the description above, I had forgotten the word "_are_".
Thanks!

**Comment by ArmanNavodia** [comment] 2023-03-06 09:31
@nicolas-raoul please assign me this issue.

**Closed** 2023-03-10 02:37 UTC
Labels: enhancement, good first issue
