### ISSUE TITLE
"No Wikidata item matching" message remains despite items loaded

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3109] opened 2019-08-02 10:38 UTC
It might be hard to reproduce, but I managed to get this when searching (see red arrow):
![adb-screenshot](https://user-images.githubusercontent.com/99590/62364518-a9173580-b55c-11e9-9669-a7404e08dbaf.png)
Maybe hide the message when you load items?

**Comment by vanshikaarora** [comment] 2019-08-03 11:44
Hey @nicolas-raoul although i was not able to reproduce the issue, yet i have modified the code to hide the view so that this issue won't come across any more. Here is the [commit](https://github.com/commons-app/apps-android-commons/pull/2970/commits/39834fb61faeacc0fe0c3265cceb74de54030a44)

**Comment by nicolas-raoul** [comment] 2019-08-05 06:07
Fixed, thanks! :-)

**Comment by nicolas-raoul** [comment] 2020-04-03 03:03
Strangely this problem seems to have reappeared (up-to-date structured-data branch):
![Screenshot_20200403-120026_Commons](https://user-images.githubusercontent.com/99590/78319897-2a6b1000-75a3-11ea-9062-e9e3d7fabbbd.jpg)

**Comment by 318anushka** [comment] 2020-04-10 17:03
@nicolas-raoul I have managed to reproduce this error. This occurs maybe due to slow internet because we are setting errorView when query list is empty as well as when error occurs while fetching from api.
Cut the internet connection while loading items and message appears. I'd fix this

**Comment by sivaraam** [comment] 2020-04-10 17:30
@318anushka I've assigned this to you. Go for it :)

**Comment by misaochan** [comment] 2020-06-23 14:39
According to @macgills this is redundant after the pagination changes.

**Closed by misaochan** 2020-06-23 14:39 UTC
Labels: assigned, bug, structured-data
