### ISSUE TITLE
Typed text lost after screen orientation change

### ISSUE THREAD

**Issue by YevgeniyMovsesov** [commons-app/apps-android-commons#2910] opened 2019-04-22 07:08 UTC
**Summary:** 

Typed text lost after screen orientation change

**Steps to reproduce:** 

1. Open main screen
2. Tap "+" to add image, select "gallery" and select any image from the gallery
3. Fill in "title" and "description", add description in second language
4. Change device orientation

Actual result: "title" and all "descriptions" were lost

Expected result: "title" and all "descriptions" remains with filled values

**Device and Android version:** 

Samsung J7, Android 8.1.0, stock
 
**Commons app version:** 

2.10.2

**Comment by madhurgupta10** [comment] 2019-04-24 03:37
@YevgeniyMovsesov I am unable to reproduce the issue, would you please upload a gif?

**Comment by YevgeniyMovsesov** [comment] 2019-04-24 06:40
![2019_04_24_09_31_35](https://user-images.githubusercontent.com/13016833/56637695-ebcf9480-6674-11e9-8867-8423c2d62113.gif)

**Comment by madhurgupta10** [comment] 2019-04-24 07:41
@YevgeniyMovsesov I tested the latest code on Xiaomi Mi A1 with API level 28 stock android but I still can't reproduce. Are you testing the latest version?
![ezgif-1-1c2c1e1a3077](https://user-images.githubusercontent.com/30932899/56641212-75418f80-6692-11e9-9f4a-89f558f46665.gif)

**Comment by YevgeniyMovsesov** [comment] 2019-04-24 14:09
Madhur, as I stated in original description, this is "Commons app" ver. 2.10.2 on 
Samsung J7 with stock Android 8.1.0

App Version Name:  @2.10.2~66e1539a1
Network Type: wifi
Device manufacturer: samsung
Device model: j7y17lte
Android Version: 8.1.0

[CommonsAppLogs.zip](https://github.com/commons-app/apps-android-commons/files/3112649/CommonsAppLogs.zip)

**Comment by madhurgupta10** [comment] 2019-04-25 00:27
@YevgeniyMovsesov Hi, I tested it on Android Oreo 8.1 stock android on a Virtual Device with similar hardware (as of Samsung J7)
I request you to please try the latest build using Android Studio, try it on Virtual Device as well. If the problem continues, let us know :)
![screencast-Genymotion-2019-04-25_05 49 58 255](https://user-images.githubusercontent.com/30932899/56701860-b8494480-671e-11e9-8e23-0f5d54ade992.gif)

**Comment by YevgeniyMovsesov** [comment] 2019-04-25 06:06
Madhur, unfortunately I don't know how to work with Android Studio and virtual devices. I reported issue, using physical device with latest build from Google Play Store as a beta-tester. If you would so kind to provide apk-link to latest build, I will try to reproduce it...

**Comment by madhurgupta10** [comment] 2019-04-25 07:13
@YevgeniyMovsesov Hi, the beta version on respective app stores are released by the team. We continuously add new features and fix issues here on GitHub and later they are released. The last release was done on February 28 which I guess you are referring too, you can view the releases [here](https://github.com/commons-app/apps-android-commons/releases)

This issue has already been fixed and you can test the apk of the latest code (attached) please close this issue if it does not appear in this apk :)
[app-commons-v2.10.2-master-beta-debug.zip](https://github.com/commons-app/apps-android-commons/files/3115598/app-commons-v2.10.2-master-beta-debug.zip)

**Closed** 2022-03-11 04:14 UTC
