### ISSUE TITLE
Migrate from junit.framework to org.junit

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4647] opened 2021-09-23 14:13 UTC
**Summary:** 
Assert in `junit.framework` has been deprecated so we should migrate to `org.junit`

Link for help https://stackoverflow.com/questions/24013210/assert-in-junit-framework-has-been-deprecated-what-next-to-use

**Would you like to work on the issue?**
No

**Comment by BashCache** [comment] 2021-09-23 19:11
Hi, Can I work on this?

**Comment by madhurgupta10** [comment] 2021-09-24 02:31
@BashCache Sure :)

**Comment by BashCache** [comment] 2021-09-26 16:48
Hi, I have changed the import statements from junit.framework to org.junit. Should I create a separate branch and push the code?
When I tried building the project, I get this error "Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:" , could you please help me out on building the project? Thanks a lot :)

**Comment by madhurgupta10** [comment] 2021-09-27 02:54
Yes, you can create a new branch and open a PR. About the build issue you are facing, can you share the steps you performed while building the project? Make sure that your Android Studio, SDK and JDK are up to date.

**Comment by madhurgupta10** [comment] 2022-02-02 10:32
Sadly this issue has been reappeared

```
w: /home/runner/work/apps-android-commons/apps-android-commons/app/src/test/kotlin/fr/free/nrw/commons/review/ReviewControllerTest.kt: (15, 24): 'Assert' is deprecated. Deprecated in Java
w: /home/runner/work/apps-android-commons/apps-android-commons/app/src/test/kotlin/fr/free/nrw/commons/review/ReviewControllerTest.kt: (16, 24): 'Assert' is deprecated. Deprecated in Java
```

Maybe a good solution would be removing the deprecated dependency altogether from the Gradle file.

**Comment by BashCache** [comment] 2022-02-02 11:43
Hello @madhurgupta10 ,
Sure, I will work on this and make the fixes.

**Comment by bhavanagarlapati** [comment] 2022-12-06 08:35
Hi @nicolas-raoul Can I take this up?

**Comment by nicolas-raoul** [comment] 2022-12-07 08:51
@BashCache Any progress on this? :-)

@bhavanagarlapati Please take one issue at a time. Do not hesitate to come back to this one after sending a pull request for your currently assigned one. :-)

**Comment by BashCache** [comment] 2022-12-07 09:07
Hi @nicolas-raoul 
I am so sorry. I missed it. You can assign this to someone else. Apologies again

**Comment by nicolas-raoul** [comment] 2022-12-07 09:20
@BashCache No problem, thanks for letting us know. :-)

**Comment by cakepineapple** [comment] 2023-02-27 17:56
Hi @nicolas-raoul , Im willing to work on this if this is not assigned yet

**Comment by AnkitThakur98** [comment] 2023-07-03 20:20
Hey @nicolas-raoul , is this issue still open? I see a few more assertions that use junit.framework
Can I work upon them?

**Comment by nicolas-raoul** [comment] 2023-07-04 01:11
@AnkitThakur98 Yes thanks! Looking forward to your pull request :-)

**Closed** 2023-07-06 05:25 UTC
Labels: bug, good first issue
