### ISSUE TITLE
Pull down gesture to refresh nearby places 

### ISSUE THREAD

**Issue by 97balakrishnan** [commons-app/apps-android-commons#1153] opened 2018-02-15 12:22 UTC
**Summary:** 

I think that a pull down gesture in the nearby places activity to refresh the location will be better than the physical refresh button. And a progress bar or animation has to be added since there is a delay in loading nearby places.

 **Commons app version:** 

2.6.7

**Comment by misaochan** [comment] 2018-02-15 14:59
Good idea. :) It is a duplicate of #264 though. Please feel free to work on that, as the person who volunteered for it hasn't been back.

**Closed by misaochan** 2018-02-15 14:59 UTC
