### ISSUE TITLE
Help popup sometimes invisible in Achievements

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3434] opened 2020-02-25 07:34 UTC
All stats have a help button, except that one.
I guess it is just waiting for someone to add one.
The help text could be:

> In the app's home, tap the "Nearby" tab to show places around you that need a picture.

**Comment by TejaswiKarasani** [comment] 2020-02-25 18:29
@nicolas-raoul I would like to give a try . Could you able to assign me this issue?

**Comment by maskaravivek** [comment] 2020-02-25 18:31
Assigned to @TejaswiKarasani

**Comment by TejaswiKarasani** [comment] 2020-02-25 18:59
@maskaravivek I would like to confirm whether the interpretation of the task by myself is correct.

I had sketched the help link in the screenshot. Could you able to verify and let me know whether is that the case?

![IMG-20200226-WA0001](https://user-images.githubusercontent.com/46127128/75277889-e449c080-582e-11ea-8362-08215cc2d848.jpg)

**Comment by maskaravivek** [comment] 2020-02-25 19:04
Nope. The issue is about the achievements screen

**Comment by TejaswiKarasani** [comment] 2020-02-25 19:18
> Nope. The issue is about the achievements screen

It already had a pop message stating as below. Should I need to just replace the text to "In the app's home, tap the "Nearby" tab to show places around you that need a picture."

![Screenshot_20200226-004530](https://user-images.githubusercontent.com/46127128/75279421-97b3b480-5831-11ea-8f03-00410995e0d5.png)

**Comment by maskaravivek** [comment] 2020-02-25 19:55
Oh, then I guess it might be getting cut off on smaller devices. Can you test it on smaller devices?

**Comment by TejaswiKarasani** [comment] 2020-02-25 20:01
Ok I will test it and revert back!

**Comment by TejaswiKarasani** [comment] 2020-02-25 21:06
Rn, I don't have internet connection to download the virtual devices but asked one of my friends who uses a smaller device (Android Version 7)

Screenshot from his mobile
![IMG-20200226-WA0005](https://user-images.githubusercontent.com/46127128/75287634-b8373b00-5840-11ea-9597-da8d35796136.jpg)

**Comment by maskaravivek** [comment] 2020-02-26 05:45
Yup as you can see the (i) icon for "Nearby Places" is slightly cut from the right side. If its a even smaller device, it might be completely cut off.

**Comment by TejaswiKarasani** [comment] 2020-02-26 06:54
@maskaravivek so my task is to reduce size so that everything moves a little left , is it so?

**Comment by nicolas-raoul** [comment] 2020-02-26 06:55
Oh, I did not realize that. I guess it is completely cut off on my device.
The goal should be to make it always visible, then :-)

**Comment by nicolas-raoul** [comment] 2020-02-26 06:57
Here is what I see:
https://commons.wikimedia.org/wiki/File:Android_Commons_app-_Achievements_screen.jpg

**Comment by TejaswiKarasani** [comment] 2020-02-26 06:58
> Here is what I see:
> https://commons.wikimedia.org/wiki/File:Android_Commons_app-_Achievements_screen.jpg

Ok I will work towards it :)

**Comment by TejaswiKarasani** [comment] 2020-02-27 17:28
@maskaravivek @nicolas-raoul does this makes sense or should I reduce the size of other contents under stats as "Upload image near by places"

![image](https://user-images.githubusercontent.com/46127128/75469211-9fe82d00-59b4-11ea-852e-18489b3842c2.png)

**Comment by sivaraam** [comment] 2020-02-29 18:00
@TejaswiKarasani The reduction of size for that content alone does give an awkward look. My suggestion to fix the issue would be to totally change how the info pop-up is shown. Rather than having a separate "info" icon for each item that would show the information pop-up, we could show the pop-up when a user taps on the text for that item. For example, we could just show the help pop-up when a user taps on the "Feature Images" text. That should totally obviate the issue of info icon getting truncated.

To give an idea, here's the "Suggested edits" screen from the Wikipedia app where they do something similar.

1. **Info overlay shown when tapping on the contribution count**
    ![Screenshot_2020-02-29-22-16-06](https://user-images.githubusercontent.com/12448084/75612592-0bfc9980-5b4b-11ea-8205-539e50308303.png)

1. **Info overlay shown when tapping on the pageview count**
    ![Screenshot_2020-02-29-22-16-03](https://user-images.githubusercontent.com/12448084/75612616-4bc38100-5b4b-11ea-918e-b7eae44e904d.png)

**Comment by TejaswiKarasani** [comment] 2020-02-29 18:06
@sivaraam I get it. Should I proceed in the same way @maskaravivek ?

**Comment by maskaravivek** [comment] 2020-02-29 18:22
@sivaraam Thanks for your feedback. A complete design change could be a separate issue. I have created #3441 to discuss it. 

@TejaswiKarasani Lets not use a different text size just for one of the texts. 

Please use the following layout. 

- Divide the whole thing into 4 columns ie. icon, text, help icon and count
- Use layout weight to assign weights to all of these columns (https://developer.android.com/guide/topics/ui/layout/linear#Weight)
- Now that the linear layout has weights assigned to it, the text and icon will autofit or wrap. 

| Icon (20%)  | Text (40%)           | Help Icon (15%) | Count (25%)          |
| ------- | ---------------- | ---------------- | ---------------- |
| ...  | ... | ... | ... |
| ...  | ... | ... | ... |

**Comment by TejaswiKarasani** [comment] 2020-02-29 18:25
> @sivaraam Thanks for your feedback. A complete design change could be a separate issue. I have created #3441 to discuss it.
> 
> @TejaswiKarasani Lets not use a different text size just for one of the texts.
> 
> Please use the following layout.
> 
> * Divide the whole thing into 4 columns ie. icon, text, help icon and count
> * Use layout weight to assign weights to all of these columns (https://developer.android.com/guide/topics/ui/layout/linear#Weight)
> * Now that the linear layout has weights assigned to it, the text and icon will autofit or wrap.
> 
> Icon (20%)	Text (40%)	Help Icon (15%)	Count (25%)
> ...	...	...	...
> ...	...	...	...
> PS: Play with the weights to adjust it and use what looks the best.

Will follow👍

**Comment by sivaraam** [comment] 2020-02-29 18:36
> A complete design change could be a separate issue. I have created #3441 to discuss it.

Just wanted to clarify one thing as you mentioned "_complete_ design change", I was only proposing to show the help pop-up when tapping on the text rather than showing it via a separate information icon. I'm not sure how that counts as a "_complete_ design change".

I used the screenshots from the Wikipedia app only to illustrate how they were handling a similar help pop-up in their app. I wasn't suggesting to change the complete design of Achievements to make it look similar to the "Suggested edits" screen of the Wikipedia app. Just wanted to get that through. Apologies if that wasn't clear.

**Comment by maskaravivek** [comment] 2020-02-29 19:32
@sivaraam Apologies for not putting it clearly. I just meant it would be a change in behavior as compared to the current flow.

**Comment by nicolas-raoul** [comment] 2020-03-01 07:11
I was thinking about just making sure that the whole text (including the help button) wrap correctly to the next line when the screen is small. It should work even on very small screens where other items such as "Featured images (?)" are also wider than the screen.

**Comment by TejaswiKarasani** [comment] 2020-03-01 17:30
> I was thinking about just making sure that the whole text (including the help button) wrap correctly to the next line when the screen is small. It should work even on very small screens where other items such as "Featured images (?)" are also wider than the screen.

So @nicolas-raoul do you mean layout-weight doesn't work?

**Comment by sivaraam** [comment] 2020-03-01 17:46
> So @nicolas-raoul do you mean layout-weight doesn't work?

I cant speak for him but I suppose, he actually means the opposite 🙂 AFAIK if you get the layout weights right, the issue mentioned here shouldn't happen on smaller screens.

**Comment by TejaswiKarasani** [comment] 2020-03-01 17:51
> > So @nicolas-raoul do you mean layout-weight doesn't work?
> 
> I cant speak for him but I suppose, he actually means the opposite  AFAIK if you get the layout weights right, the issue mentioned here shouldn't happen.

If that's the case then cool :)

**Comment by arishta** [comment] 2020-08-27 16:45
My team and I were looking for issues to resolve and this seems like a good starting point. If this issue is unassigned, can it be assigned to us?

**Comment by nicolas-raoul** [comment] 2020-08-27 23:44
@TejaswiKarasani Are you still working on this? :-)

**Comment by TejaswiKarasani** [comment] 2020-08-28 02:13
Feel free to unassign it @nicolas-raoul :)

**Comment by nicolas-raoul** [comment] 2020-08-28 04:31
@TejaswiKarasani Thanks :-)
@arishta It is yours, please let us know about your progress every few days at least :-)

**Comment by anadi198** [comment] 2020-10-13 19:54
Hello, I'm new here and I was wondering if I could work on this issue..

**Comment by nicolas-raoul** [comment] 2020-10-14 01:06
@arishta Are you still working on this? Please let us know about your progress :-)

**Comment by arishta** [comment] 2020-10-14 12:26
@nicolas-raoul  My team and I are working on three issues of this app(including this) parallelly as part of our software development lab. We have completed the design phase of all the three issues, and are now proceeding towards the implementation part.

**Comment by nicolas-raoul** [comment] 2020-10-14 14:42
@arishta Wonderful! Would you mind posting the results of the design phase? (on each of the 3 issues)
Thanks!

**Comment by arishta** [comment] 2020-10-14 18:22
@nicolas-raoul 
So far we have completed the requirements gathering phase, the output of which is the SRS document attached here.
The next phase was the design and planning phase. Most of the discussion was summed up in forms, but we do have a high level design document that I have attached here.
[HLD.docx](https://github.com/commons-app/apps-android-commons/files/5380102/HLD.docx)
[SRS.pdf](https://github.com/commons-app/apps-android-commons/files/5380107/SRS.pdf)

**Comment by sivaraam** [comment] 2020-10-17 19:09
Hi @arishta, we don't require contributors to write those documents for fixing issues. So, you could get right into fixing the issue (similar to the "implementation" phase in your process) and asking for help in that regard. Thanks!

**Comment by arishta** [comment] 2020-10-17 19:39
@sivaraam Yes, I understand that. As I have said in the above comment, we have picked these issues as part of our software development lab in the ongoing semester, which requires us to follow all the steps in the given order, beginning from, requirements gathering phase to testing phase, mimicking how software development process actually happens in the real world. I posted the documents after @nicolas-raoul expressed interest in seeing them.

**Comment by arishta** [comment] 2020-11-08 19:35
This is the link to the PR from my team - isdl03
[link](https://github.com/commons-app/apps-android-commons/pull/4023)

**Comment by arishta** [comment] 2021-01-09 09:40
@sivaraam We have made the requested changes in the PR [#4023](https://github.com/commons-app/apps-android-commons/pull/4023). Kindly review the same.

**Comment by sivaraam** [comment] 2021-01-16 16:31
> 
> @sivaraam We have made the requested changes in the PR [#4023](https://github.com/commons-app/apps-android-commons/pull/4023). Kindly review the same.

Apologies for the delay. I was supposed to get around to this long ago but it slipped. Currently, I'm in lack of time due to a medical emergency in my family. I'll be sure to review when I find the time. We'll see if someone else could beat me to it, instead :)

**Comment by Ayan-10** [comment] 2021-03-31 11:19
Hi, @sivaraam @nicolas-raoul Is the issue still open? I would like to work on this issue.

**Comment by nicolas-raoul** [comment] 2021-04-01 14:11
@arishta Thanks for working on this! Are you planning to address https://github.com/commons-app/apps-android-commons/pull/4023#pullrequestreview-572388916 within a month? If not, would you mind letting Ayan continue your work? Cheers!

**Comment by arishta** [comment] 2021-04-01 14:58
Hello, @nicolas-raoul No, we will not be working on this. You can let Ayan continue the work.

**Comment by neslihanturan** [comment] 2021-04-01 15:32
Thanks for letting us know @arishta , you can go for it @Ayan-10 :)

**Comment by Ayan-10** [comment] 2021-04-01 19:15
Hey @neslihanturan , Thank you for assigning me.
I was thinking that In fragment_achievements.xml under the statistics section if we wrap each element with Constraint layout instead of Relative Layout and constrain it as needed we can prevent this issue.
I am attaching the original and updated screenshot of the app. Please have a look.

#### Original
<img src="https://user-images.githubusercontent.com/71203077/113342414-15f35c00-934c-11eb-98ab-48bb6eca63fc.png" width="300">

#### Updated
<img src="https://user-images.githubusercontent.com/71203077/113342691-67035000-934c-11eb-9fc6-b18e1b5fe4d3.png" width="300">

Should I move forward with this idea. Let me know your opinion.

**Comment by nicolas-raoul** [comment] 2021-04-02 05:51
@Ayan-10 For the updated version, could you please post a screenshot on a tiny screen? You can use the Android emulator to simulate any screen size. Thanks!

**Comment by Ayan-10** [comment] 2021-04-02 13:51
@nicolas-raoul , I test this issue in Nexus One 3.7' 480x800 API 26. This solution is not working help popup is getting overlapped with the count Textview. After that, I also tried in every possible way to solve this issue by organising fragment_ achievements.xml layout but this issue can't be solved.
I think now either we have to reduce the size of each TextView and ImageViews or we have to change the whole Statistics section that the help popup can be shown. Although I am still trying to solve the issue by maintaining this layout theme.
If you have any other idea or suggestion You can suggest me.

**Comment by nicolas-raoul** [comment] 2021-04-03 14:35
@Ayan-10 Thanks for testing! Unfortunately I am not sure what would work here... I still hope it is possible to achieve without changing the UI drastically, though.

**Comment by Ayan-10** [comment] 2021-04-03 15:31
Ok @nicolas-raoul, So I have got an idea. The in the layout the help icon is a little upper of the layout. So if we put the count textView a little lower and warp them with constrainlayout, For smaller screen size devices the count textView will come under the help icon instead of overlapping it. For a normal screen device, it will look as it is now ( not actually as it is. The count icon will come a little lower but not that much ). But in the smaller devices, it will come under the icon.
What is your opinion about this idea?

**Comment by nicolas-raoul** [comment] 2021-04-04 09:12
I am not a Android UI expert unfortunately...
Anyone able to check the strategy described in the post above? @madhurgupta10 maybe?

**Comment by madhurgupta10** [comment] 2021-04-04 09:17
IMO using constraint layout and setting 0dp for the TextView should work just fine for all devices.

**Comment by Ayan-10** [comment] 2021-04-04 10:05
@madhurgupta10 I tried that idea before but I think It didn't work for all devices. For small devices, the TextViews were getting overlapped. As you can see in early conversation I tested on **Nexus One 3.7' 480x800 API 26**. TextViews are getting overlapped as the text is large in size.

**Comment by Ayan-10** [comment] 2021-04-04 10:27
@madhurgupta10 @nicolas-raoul Till now I can think of two possible ideas. I am mentioning it below.

#### 1. Placing the count TextView under the help icon and reducing the size of the right margin of count TextView.
<table>
<tr>
<td> Device Size = Normal || Device = Pixel 3a</td>
<td> Device Size = Small || Device = Nexus One</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/71203077/113505376-16fad800-955c-11eb-8f4e-cf99cad6ca95.png"width="300"></td>
<td><img src="https://user-images.githubusercontent.com/71203077/113505381-1bbf8c00-955c-11eb-8b98-4026774e80cb.png"width="300"></td>
</tr>
</table>

> UI can still be improved

#### 2. The main problem is the text is very long and that's why it's creating problem and getting overlapped. So it we break the line into two parts and give a new line between those two parts. The problem can be solved and it will work for smallest devices I tested it on the smallest emulator **2.7" QVGA 240x320**
<table>
<tr>
<td> Device Size = Normal || Device = Pixel 3a</td>
<td> Device Size = Small || Device = Nexus One</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/71203077/113505625-b076b980-955d-11eb-8b50-92955e8b9a74.png"width="300"></td>
<td><img src="https://user-images.githubusercontent.com/71203077/113505618-aa80d880-955d-11eb-808b-804cb29b27f6.png"width="300"></td>
</tr>
</table>
<br></br>
I think 2nd solution looks better and Hope you like it. Let me know your thought on this.

**Comment by madhurgupta10** [comment] 2021-04-04 10:36
> @madhurgupta10 I tried that idea before but I think It didn't work for all devices. For small devices, the TextViews were getting overlapped. **As you can see in early conversation** I tested on **Nexus One 3.7' 480x800 API 26**. TextViews are getting overlapped as the text is large in size.

Could you share the code snippet?

**Comment by Ayan-10** [comment] 2021-04-04 10:52
> > @madhurgupta10 I tried that idea before but I think It didn't work for all devices. For small devices, the TextViews were getting overlapped. **As you can see in early conversation** I tested on **Nexus One 3.7' 480x800 API 26**. TextViews are getting overlapped as the text is large in size.
> 
> Could you share the code snippet?

When I was testing, It did not work out so I delete the branch. I will redo it and share the code snippet here ASAP.

**Comment by Ayan-10** [comment] 2021-04-04 12:36
Thank you @madhurgupta10 for suggesting.

After the suggestion while redoing it. I realized It can be actually possible to do.

#### I think the issue was solved. Here I am attaching the images of normal and small device screen.
<table>
<tr>
<td> Device Size = Normal || Device = Pixel 3a</td>
<td> Device Size = Small || Device = Nexus One</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/71203077/113508828-dad17280-956f-11eb-9b57-4e36bdc69ef2.png"width="300"></td>
<td><img src="https://user-images.githubusercontent.com/71203077/113508809-bf666780-956f-11eb-8e27-991f270fb252.png"width="300"></td>
</tr>
</table>

**Closed** 2021-04-06 12:41 UTC
Labels: achievements, assigned, bug, good first issue
