### ISSUE TITLE
Crash in Upload Wizard when changing Android font size

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5437] opened 2024-01-15 06:50 UTC
1. Start an upload
2. Change Android font size
3. Come back to the Commons app
4. Crash:
```
java.lang.NullPointerException: Attempt to invoke interface method 'int fr.free.nrw.commons.upload.UploadBaseFragment$Callback.getIndexInViewFlipper(fr.free.nrw.commons.upload.UploadBaseFragment)' on a null object reference
at fr.free.nrw.commons.upload.depicts.DepictsFragment.init(DepictsFragment.java:119)
at fr.free.nrw.commons.upload.depicts.DepictsFragment.onViewCreated(DepictsFragment.java:109)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
at android.app.Activity.performStart(Activity.java:8654)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3847)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2468)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
https://github.com/commons-app/apps-android-commons/assets/99590/a23b9d64-3795-410d-86d6-9ecef28d1f9a

**Comment by ShashwatKedia** [comment] 2024-01-15 14:59
> I am not able to reproduce this issue on my Physical Device Running Android 13, I can change fonts while uploading media without the app crashing.

Strange, I can reproduce this on my OnePlus Nord CE 2 Lite, running Android 11 and on emulator Pixel 7 pro. And this crash occurs only in upload wizard, not in any other activity/fragment

**Comment by psh** [comment] 2024-01-15 18:44
Changing the font size causes an Android _configuration change_ in the app. The Android system recreates the UI, cycling through the standard lifecycle.  Things like Intent arguments, Fragment arguments, and ViewModels are designed to persist across a _config change_ but if you look at the `callback` object we are using (from the stacktrace, `DepictsFragment.java` line `119`) it's `null` probably because the system dropped and recreated everything and never sets that back up, and honestly, it never should ... we do it in the `UploadActivity` (line `592`) as a one-time thing.  The root-cause of the bug / defect seems to me to be that we are not correctly handling config change.

**Comment by shashankiitbhu** [comment] 2024-01-17 19:46
I tried to save the calledback in onSaveInstanceState in UploadBaseFragment and restore it in onCreate, I was able to stop it from crashing and I think I'll be able to completely Fix the Issue by applying similar logic in other Fragments used in UploadActivity, Can you assign this to me?

**Comment by shashankiitbhu** [comment] 2024-01-18 10:09
@nicolas-raoul Fixed the Issue, Please Review the above PR

**Comment by shashankiitbhu** [comment] 2024-01-23 10:51
I believe #5466 Fixes this issue, please review it @nicolas-raoul

**Closed** 2024-01-24 09:30 UTC
Labels: bug
