### ISSUE TITLE
"archeology japan" does not find "Archeology in Japan"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#237] opened 2016-08-23 05:57 UTC
![screenshot_2016-04-11-23-07-54](https://cloud.githubusercontent.com/assets/99590/17881612/d6a3eada-6941-11e6-902a-f2442d2d85e4.png)
![screenshot_2016-04-11-23-07-42](https://cloud.githubusercontent.com/assets/99590/17881611/d69e54a8-6941-11e6-9135-e33927bbf048.png)

**Comment by jayvdb** [comment] 2016-08-23 06:15
The Wikimedia search has lots of bugs like this,nso that might be the cause.

**Comment by nicolas-raoul** [comment] 2016-08-23 06:27
@jayvdb : Indeed, like maybe of the issues in this category, the actual problem probably lies upstream, but better keep track of them here too because:
- Upstream tickets sometimes get deleted without a real solution
- We might switch to a different upstream if a better one appears
Cheers!

**Comment by jayvdb** [comment] 2016-08-23 06:59
Ok. Use an 'upstream' label for these?

**Comment by neslihanturan** [comment] 2019-03-11 11:32
Some inconsistencies about category suggestion happens. We are not sure if it is a backend issue or related with the implementation of the app. I think this should be considered as a bug and requires further investigation about root cause.

**Comment by nicolas-raoul** [comment] 2019-03-11 11:39
I have not seen this kind of problems too much, recently.

Actually, before investigating this issue,  #2519 should take priority I think, as it makes many searches show irrelevant results, independently from the backend.

**Comment by ashishkumar468** [comment] 2020-10-11 18:30
@nicolas-raoul  Do the latest releases still have this issue?

**Comment by nicolas-raoul** [comment] 2020-10-11 23:17
I just tried, and yes:
![Screenshot_20201012-081611_Commons](https://user-images.githubusercontent.com/99590/95692781-51498380-0c63-11eb-9a54-313dded604f6.jpg)

**Comment by sivaraam** [comment] 2024-05-13 13:42
For reference, as mentioned in https://github.com/commons-app/apps-android-commons/issues/5712#issuecomment-2107593881, this is due to our category search bringing only prefix matches. So, I'm closing this issue in favour of continuing the discussion at #3179 where we could discuss about fixing various scenarios related to category search. 

Feel free to re-open if I seem to have misunderstood the issue.

**Closed by sivaraam** 2024-05-13 13:42 UTC
Labels: bug, enhancement, categorization, upstream
