### ISSUE TITLE
Swiping campaign notification shows "You won't see campaigns anymore", but actually same notification comes back

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5288] opened 2023-09-11 04:13 UTC
Steps:
1. Swipe left the campaign notification.
2. A toast saying "You won't see campaigns anymore" appears.
3. Problem: A few days later when opening the app I see the notification again.

Same for the **nearby** notification, with "You won't see the nearest place that needs picture anymore" but coming again at the same time as the campaign notification.

**Comment by Kwong-Yu-Zhou** [comment] 2023-10-04 00:29
Hi @nicolas-raoul, I'm new to OSS and would like to work on this as my first issue. May I take this one?

**Comment by nicolas-raoul** [comment] 2023-10-04 03:57
@Kwong-Yu-Zhou It is yours, thanks! Please let us know about your progress at least every week or so. :-)

**Comment by Kwong-Yu-Zhou** [comment] 2023-10-09 06:14
Hello @nicolas-raoul,

I hope this message finds you well. I wanted to discuss the approach I've been working on to resolve the issue. My proposal involves implementing a notification filtering mechanism using _BroadcastReceiver_ to manage user interactions (notification swipes). During the course of my work, I encountered a few challenges. I would greatly appreciate your guidance regarding some questions I have. 

1. Firstly, I'm curious about the specific scenarios in which a user would receive a notification.   

2. Secondly, I'm keen to understand the process of notification generation. If possible, could you kindly point me to the relevant classes associated with this task?

Your assistance would be invaluable to me in resolving these queries.

**Comment by nicolas-raoul** [comment] 2023-10-09 11:29
To get the nearby notification, use the Fake GPS app (or emulator) to pretend you are right at the center of the Eiffel Tower.

1 year ago this bug was not present so I would suggest you use Git to build an older version of the app and place breakpoints in the code to find out where the code is. Then compare witg the current code.

**Comment by Kwong-Yu-Zhou** [comment] 2023-10-18 05:31
Sorry @nicolas-raoul, I just recovered from a bad cold. I changed the location to the Eiffel Tower as you told me, and I have understood the idea of the issue. 

A problem is that for choosing the 1-year-ago version, I have tried V4.0.0 to V4.0.5, however, there is always an error: "_Execution failed for task ':app:kaptBetaDebugKotlin'_", which cause failure on building. 

<img width="998" alt="截屏2023-10-18 下午4 22 39" src="https://github.com/commons-app/apps-android-commons/assets/110373865/1df4cdd3-6f9a-4aa8-a2d3-c1158370bdb1">

Could you please give me some advice for solving this problem?

**Comment by nicolas-raoul** [comment] 2023-10-18 05:48
How about 6 months ago?
You may need to try several different commits to find one that works.

**Comment by Kwong-Yu-Zhou** [comment] 2023-10-21 03:54
Hey @nicolas-raoul, after analysing some related classes, I think that the problem is caused by the _onSwipe_ function itself: The _campaignpreference_ is switched to False after swiping, however, CAMPAIGNS_DEFAULT_PREFERENCE is the only one to be checked in fetchCampaigns. In the PR, I changed the _onSwipe_ function so now it will switch the CAMPAIGNS_DEFAULT_PREFERENCE, making the two functions consistent.

**Comment by Kwong-Yu-Zhou** [comment] 2023-10-21 04:06
By the way, the OnSwipe function hasn't been changed since at least V3.1.1. 
I saw that there is a new update of about 50 lines in the class **_ContributionsFragment_** (between V4.0.5 and V4.2), including the _nearbyLocationPermissionLauncher_ function, which may have led to the exposure of the problem mentioned above. 🤔

**Comment by rohit9625** [comment] 2024-01-06 05:48
Any updates on this issue?
@Kwong-Yu-Zhou

**Comment by edu-kalel** [comment] 2024-01-10 21:21
Hey everyone! Could I get assigned to this issue? I would love to give it a try

**Comment by nicolas-raoul** [comment] 2024-01-12 08:22
No news from Kwong, @edu-kalel it is yours, please let us know about your progress every week or so. :-)

**Comment by edu-kalel** [comment] 2024-01-25 06:37
Hi @nicolas-raoul , sorry for the radio silence, I was buried with school work the past weeks.

I was reviewing the progress made by Kwong, and while he definitely seems to be on to something, I can't seem to reproduce the issue :( have you been able to reproduce it?

**Comment by nicolas-raoul** [comment] 2024-01-25 07:08
@edu-kalel Maybe because there is actually no on-going campaign right... there will be one from 2024-02-15 though.
If you find a Wikimedia Commons-related campaign which is currently happening, feel free to add it to the JSON. :-)

**Comment by nicolas-raoul** [comment] 2024-01-26 00:16
Ah yes!
After you swipe it, it never reappears?
If yes then I guess the issue is solved. 🙂

**Comment by edu-kalel** [comment] 2024-02-07 04:46
Hi @nicolas-raoul 
So, just in case, I wanted to wait a few days to see if the notifications reappeared (maybe it was a time-bound issue?) but they didn't, I was testing both on an Android Virtual Device and my own Android Device.
So, if the issue is going to be marked as solve, can I take a look at another one? I already got familiar with the project, and would like to still contribute :D

**Comment by nicolas-raoul** [comment] 2024-02-07 13:53
@edu-kalel Sure, feel free to work on another issue!
I will test in prod with the campaign that starts from 2024-02-15. Thanks! :-)

**Closed** 2024-02-14 21:23 UTC
Labels: bug, good first issue, notifications
