### ISSUE TITLE
Some categories hidden at top of Upload Wizard suggestions, need to manually scroll up

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5344] opened 2023-10-17 10:54 UTC
https://github.com/commons-app/apps-android-commons/assets/99590/37cf02ab-366d-4094-9311-7ed4aaa31db2

**Comment by HNYDDDTONY-ANU** [comment] 2023-10-17 15:02
Can you assign it to me? I am interested in attempting to complete this issue.

**Comment by Jasson-Hsu** [comment] 2023-10-22 05:00
I can not reproduce this issue. Could you explain further how you encountered this issue?

**Comment by nicolas-raoul** [comment] 2023-10-22 06:55
@Jasson-Hsu Have you tried uploading a picture? If the bug does not happen, please post a screencast and I will try to spot the difference. Thanks!

**Comment by HNYDDDTONY-ANU** [comment] 2023-10-24 17:56
I tested it on Android Studio, and the matched categories automatically jump to the top of the list while the other categories move down. It seems to be working fine. Here is a screen recording:

https://github.com/commons-app/apps-android-commons/assets/140160683/bcdf1c74-a778-43db-a399-bf5010a8327e

**Comment by nicolas-raoul** [comment] 2023-10-25 00:50
This is probably because you don't have enough suggested categories to make the list take several pages. Search and select 20 random categories to add them to the history, then try a new upload. Thanks! 🙂

**Closed** 2023-11-01 13:25 UTC
