### ISSUE TITLE
IndexOutOfBoundsException at SearchActivity, when editing item search string

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3743] opened 2020-05-11 13:29 UTC
I can't reproduce it, but on the search screen for items I got this crash immediately after typing a new character at the end of a word:
```
APP_VERSION_CODE=699
APP_VERSION_NAME=2.12.3.699
ANDROID_VERSION=9
PHONE_MODEL=SM-G970F
STACK_TRACE=java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{cd5b575 position=0 id=-1, oldPos=0, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{9886189 VFED.V... ......ID 0,12-1080,786 #7f090128 app:id/imagesListBox}, adapter:com.pedrogomez.renderers.RVRendererAdapter@3b44c62, layout:androidx.recyclerview.widget.LinearLayoutManager@8d691f3, context:fr.free.nrw.commons.explore.SearchActivity@baf0467
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5815)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5998)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5958)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5954)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3941)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3705)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4260)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3343)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2807)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1853)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8476)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7032)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by macgills** [comment] 2020-05-11 14:26
Duplicate of #3140 or at least the solution is the same

**Closed by macgills** 2020-05-11 14:26 UTC
Labels: bug, explore, structured-data
