### ISSUE TITLE
Case sensitive search for category

### ISSUE THREAD

**Issue by DiFronzo** [commons-app/apps-android-commons#3585] opened 2020-03-25 14:07 UTC
**Summary:** 

The search is way to sensitive on uppercase and lowercase categories. Should show both lowercase and uppercase results.

**Steps to reproduce:** 

1. the latest master
2. Start uploading any image (you can abort afterwards)
3. When the category search activity appears, type "covid-19 pandemic"
4. You get no results, even though [Category:COVID-19 pandemic](https://commons.wikimedia.org/wiki/Category:COVID-19_pandemic) exist.

**Device and Android version:** 

Samsung s8 edge
Android 9
Stock version
 
**Commons app version:** 

Commons 2.12.3~dc08a5e88

**Screen-shots:** 

![2020-03-25 15 00 51](https://user-images.githubusercontent.com/30557582/77544577-7a621c80-6ea9-11ea-82fa-40a2a8f3fe03.jpg)
![2020-03-25 15 01 23](https://user-images.githubusercontent.com/30557582/77544609-84841b00-6ea9-11ea-9dbf-dfc37dbd8947.jpg)

**Comment by vvijayalakshmi21** [comment] 2020-03-28 07:06
Hi, Is this issue similar to #3179 ?

**Comment by dafnith** [comment] 2020-03-28 11:42
Can I work on this issue?
(Is it possible for my colleague @johnnyrevithis to be an assignee as well?)

**Comment by sivaraam** [comment] 2020-03-28 15:28
@vvijayalakshmi21 You're right. This is a duplicate of #3179 (which has been re-opened).

@dafnith I'm closing this as this is a dupe. You can take up #3179 if you're interested or take a look at other issues. 🙂

**Closed by sivaraam** 2020-03-28 15:28 UTC
Labels: bug, categorization
