### ISSUE TITLE
Fix lint issues in project

### ISSUE THREAD

**Issue by anirudh24seven** [commons-app/apps-android-commons#316] opened 2016-10-31 05:42 UTC
Tracking GitHub issue for Lint issues in project.

This is the current output when 'Inspect Code' action is run within Android Studio.

![androidcommonslint](https://cloud.githubusercontent.com/assets/617443/19845238/e3a5ee6e-9f5a-11e6-9572-abb863646ef0.PNG)

**Comment by domdomegg** [comment] 2017-03-08 23:17
Possible duplicate of #171?

**Comment by misaochan** [comment] 2017-03-09 08:08
Yep, I'll close this, please refer to 171.

**Closed by misaochan** 2017-03-09 08:08 UTC
Labels: bug
