### ISSUE TITLE
[Bug]: "copy the wikitext to the clipboard" produces different results depending on timing

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5315] opened 2023-09-27 04:21 UTC
### Summary

Pressing the button `copy the wikitext to the clipboard` produces a different result depending if the upload is still in progress (wrong result), or whether the upload has finished (correct result).

### Steps to reproduce

1. have a slow network connection
2. add new picture, fill metadata and submit
3. while the picture is still uploading (i.e. a progress bar is being shown), click on the `copy the wikitext to the clipboard` button and paste the result somewhere
4. wait until the upload finishes
5. click on the `copy the wikitext to the clipboard` button again and paste the result somewhere

### Expected behaviour

the first and second value copied are the same.

### Actual behaviour

The first and second results differ. For example, for this file: https://commons.wikimedia.org/wiki/File:Knafel%C4%8Deva_markacija_na_odrezanoj_grani,_Prvi%C4%87.jpg the first copy/paste produces:

```
[[Knafelčeva markacija na odrezanoj grani, Prvić.jpg|thumb|]]
```
(which is wrong) while the second copy/paste produces (correct!):

```
[[File:Knafelčeva markacija na odrezanoj grani, Prvić.jpg|thumb|]]
```

i.e. the first one misses `File:` (which then makes problems when one pastes it to the app that expects standard commons format, like e.g. [EveryDoor](https://wiki.openstreetmap.org/wiki/Every_Door)). Especially annoying when the mobile internet is slow, as one is forced to either wait a long time, or manually fix every image name.

### Device name

Huawei P30Pro

### Android version

Android 10 (EMUI 12)

### Commons app version

4.1.0 (latest f-droid)

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/156656/71de16af-e770-4aeb-961f-eadd9d19228d

### Would you like to work on the issue?

None

**Comment by Kshitiz-Mhto** [comment] 2023-09-28 11:58
hello @nicolas-raoul, i am new to the project and exploring the project. Since it is a good-first-issue, can i give it a try?

**Comment by nicolas-raoul** [comment] 2023-09-28 14:10
@Kshitiz-Mhto It is yours, thanks! Please let us knfw about your progress every few days. 🙂

**Comment by Kshitiz-Mhto** [comment] 2023-10-01 08:56
actually my exams are ongoing ryt now, so i am giveing as much as free time i have on this. so my response might be delay hope you understand.

i did find this code that casing the issue, i m workng on it. thanks you

file -> ` fr.free.nrw.commons.media.MediaDetailFragment`

![Screenshot from 2023-10-01 14-39-26](https://github.com/commons-app/apps-android-commons/assets/102871719/f9d3b086-fa01-4db1-b071-f65224d5e95c)

**Comment by nicolas-raoul** [comment] 2023-10-01 10:12
@Kshitiz-Mhto Sure no worries, please focus on your exams, letting us know every 2 weeks is fine. :-)

**Comment by TaiHaDev** [comment] 2023-10-15 08:40
@Kshitiz-Mhto are you still working on this? @nicolas-raoul  Can I please give this a try? I would be able to finish this within two weeks 😄

**Comment by nicolas-raoul** [comment] 2023-10-15 09:06
@TaiHaDev How about #5263? :-)

**Comment by TaiHaDev** [comment] 2023-10-15 10:12
Hi @nicolas-raoul, I had a look at the issue but I couldn't reproduce but I found an interesting one #5212 . Can I give it a try?😁 I will regularly update my progress. Thank you!

**Comment by nicolas-raoul** [comment] 2023-10-15 11:20
@TaiHaDev Sure! Please comment there, as I can't assign you unless you comment. Thanks! :-)

**Comment by Kshitiz-Mhto** [comment] 2023-10-16 03:57
my exam r over now, i m all good to go now, i will finish this as soon as i can. thank u!

**Comment by mnalis** [comment] 2023-11-09 23:17
Any luck @Kshitiz-Mhto ?

**Comment by axelthepony27** [comment] 2023-12-26 17:26
Hello! I'm new to the open source community and exploring the project. I saw this is a good first issue. Could I give it a try?

**Comment by annuk123** [comment] 2023-12-26 17:58
Hello! I'm new to the Open Source Contribution

**Comment by nicolas-raoul** [comment] 2023-12-27 06:12
@axelthepony27 It is yours, please let us know about your progress every week or so, thanks! 🙂

**Comment by nicolas-raoul** [comment] 2023-12-27 06:16
@annuk123 How about https://github.com/commons-app/apps-android-commons/issues/5194 for instance? 🙂

**Comment by axelthepony27** [comment] 2023-12-27 19:43
@nicolas-raoul Thanks! I forked the repo and cloned it to my locale, but the file `fr.free.nrw.commons.media.MediaDetailFragment` appears to have an import that doesn't exist. Is this a problem of mine, or do you know what else could be causing this?
<img width="617" alt="image" src="https://github.com/commons-app/apps-android-commons/assets/72633332/f7168401-3a30-48c8-9d85-7059df7f4331">

**Comment by mnalis** [comment] 2023-12-28 00:49
@axelthepony27 And what happens when you [try to compile](https://github.com/commons-app/commons-app-documentation/blob/master/android/Quick-start-guide-for-Developers.md)? Do you get some error, or does it just work?

For me, GitHub workflow seems to compile latest `main` just fine, e.g. https://github.com/mnalis/apps-android-commons/actions/runs/7343113966/job/19993280163)

**Comment by axelthepony27** [comment] 2023-12-28 04:25
@mnalis When I try to build, I get this error. Perhaps I missed a step in the configuration? Is there something else I should do? I followed the steps described in the quick guide verbatim (at least to my knowledge).
<img width="917" alt="image" src="https://github.com/commons-app/apps-android-commons/assets/72633332/3df73d46-b838-4ea7-a787-5e333bb2f29b">

**Comment by mnalis** [comment] 2023-12-28 12:12
@axelthepony27 well, I don't really know (I don't even have local Android SDK installed - I just use GitHub to build it). 

But:
- the _"failed to find Platform SDK with path"_ (which is the **real** error) seems to me unrelated to the originally reported error (_"missing fr.free.nrw.commons.BuildConfig"_, which seems to be a [red herring](https://en.wikipedia.org/wiki/Red_herring))
- it seems related to your build toolkit, not to Commons app itself. Have you been successfully building any other Android projects on that setup?
- my first guess would be that the _**"platforms;android-33"**_ part of the error might indicate you need to **download that correct platform**? e.g. via `menu > Tools > SDK Manager` ? As shown in screenshot [here](https://stackoverflow.com/a/54892049/2600099)
- if that doesn't help, I'd try [searching the web for the web for similar errors](https://duckduckgo.com/?t=ftsa&q=%22failed+to+find+Platform+SDK+with+path%22&ia=web)

**Comment by axelthepony27** [comment] 2023-12-28 15:48
@mnalis Thanks! I did as you recommended and indeed, I had to download and install the correct SDK. I has able to build it with no errors. However, the original error(?) I posted remains; the code still can't find that import. Do I just ignore it, or do you think it's imperative that I solve it?

**Comment by axelthepony27** [comment] 2023-12-28 16:17
@mnalis Thanks! Indeed, the problem was solved by installing the correct SDK. I'll get to work on the issue now, i does appear to the the fragment of code that @Kshitiz-Mhto mentioned.

**Comment by axelthepony27** [comment] 2023-12-29 18:45
Doing some tests, I found out that the "description" metadata also changes if copied during upload. Do we know if this is expected, or is it also part of the issue?
In the following SS, the first line of text was copied during upload, and the second one once it was done. We can noties that, indeed, the `File:` substring is missing, but there are also some dangling `{}` and `en|1=` that aren't present in the expected result.
<img width="417" alt="image" src="https://github.com/commons-app/apps-android-commons/assets/72633332/2b1b5722-83e2-4ab3-9ef1-fa42b493e99e">

**Comment by nicolas-raoul** [comment] 2023-12-29 22:08
Great finding!

Ideally File: should be present even when copied during upload.

**Comment by annuk123** [comment] 2023-12-31 08:48
> @annuk123 How about #5194 for instance? 🙂

Thanks 😇

**Comment by nicolas-raoul** [comment] 2023-12-31 12:15
@annuk123 That one got taken quickly, but how about https://github.com/commons-app/apps-android-commons/issues/5413 ?

**Comment by axelthepony27** [comment] 2024-01-02 20:30
Well, doing som tests, I determined the problem lies on the `media.getFilename()` and `media.getFallbackDescription()` methods. Something happens between when the upload is in progress and when it is done that changes the ouputs of those methods. I, however, was unable to locate where, as those attributes com from the file `Media.kt`, and don't have explicit getters. Does some have any idea where the problem might originate? Perhaps on the code that manages the upload of files.

**Comment by mnalis** [comment] 2024-01-20 01:54
@axelthepony27 perhaps you can add the debug code around places where this gets called to get more precise idea when and where exactly the value changes? That should be instructional to finding the cause of the issue (and thus, the fix).

**Comment by axelthepony27** [comment] 2024-01-23 17:31
@mnalis Thanks, I'll try that. I went on vacation for a couple of weeks, but I'll retake the issue this week

**Comment by axelthepony27** [comment] 2024-01-23 18:47
Doing some more tests, I noticed that, while an image is still uploading, the "Description" field presents the text in the wrong format, like this: 
![image](https://github.com/commons-app/apps-android-commons/assets/72633332/b8b719d8-e1a8-4979-91cc-15a03f5e3f00)

However, after the image has finished uploading, the description text is correct:
![image](https://github.com/commons-app/apps-android-commons/assets/72633332/a5c3408c-1b89-42bb-9586-50a0a3449ae5)

This leads me to believe that the error doesn't lie in the copy method itself, `onCopyWikicodeClicked()`, as originally thought, but rather on something else: perhaps the the code that generates the text fields on the image's card in the first place. Does anyone know where that happens, so that I could have a better-guided debugging? I can't seem to find where it happends, or another good place to look for the bug.

**Comment by axelthepony27** [comment] 2024-01-23 20:43
Well, I found the bit of code that formats the "Description" part only. It seems to happen during upload. The upload process formats the filename and description of an upload differently than when an upload is done. I think after an upload has finished, the details panel pulls the filename and description from some other place. However, I'm unable to find where exactly. In any case, what might be happening could be fixed by one of two ways:

1. Find when and from where the filename and description fields pull the text, and agree them so that they pull the text from only one place (the correct one). I still, however, would need to find when and where it happens exactly.
2. Agree the formats both during upload and when the upload is done. This, however, doesn't seem like a good solution, as the description of method `formatDescriptions()` in class `Contribution.kt` says it _"Formats the list of descriptions into the format Commons requires for uploads."_

![image](https://github.com/commons-app/apps-android-commons/assets/72633332/1f9cceb8-be0f-4c1b-b06d-138995c9e520)

Testing it, this method definitively is where the "wrong" format takes place:
![image](https://github.com/commons-app/apps-android-commons/assets/72633332/fe0218e4-e000-4ae4-a75b-356127033324)

I would like a little more guidance on how to proceed, if anyone could lend me a hand.

**Comment by Get4nik** [comment] 2024-02-02 13:17
Hi @nicolas-raoul , I just started to look for issues so that I can contribute, since it is a good first issue can i give it a try

**Comment by axelthepony27** [comment] 2024-02-27 17:32
Hi, @nicolas-raoul @mnalis. Just following up on this, did you have the chance to check out my questions?

**Comment by mnalis** [comment] 2024-03-09 16:29
@axelthepony27 I have too little experience with Commons codebase, so I can't give any specific pointers. If I did have more, I would've taken on the issue myself :smiley: 

Regarding your dilemma in where to fix the code, I think it is way too premature way of thinking.
Because, one shouldn't try to fix bug the **first**. 

That would be the [kludge](https://en.wikipedia.org/wiki/Kludge), and could be done anywhere alongside the path -- e.g. one could then simply check the description in any function before the description is shown to users, and prepend `File:` before filename if it is missing. Violla, problem solved -- well, sidestepped anyway. 

But that is **not** very good solution. It sometimes _might_ be better than nothing (i.e. it fixes the immediate problem) but codebase maintainers might be unhappy about it (and with good reason: fixing the **manifestations** of bugs instead of bugs **themselves** might likely lead to even harder to fix bugs in the future and less readable/understandable codebase -- and even when kludge might be accepted, it should have big bug comment block explaining what is being done in dirty way, and why wasn't it done in better way).

---

But to really **solve** the bug, one must:

- first be able to **reproduce** the bug at will. That is often the hardest part, and luckily for us, it seems it is 100% reproducible for this bug, only somewhat time-dependent. That is second-best type of the bug! (the best bug being the one which always happens and does not depend on anything).
- then one must find **where** the bug is happening. That takes one of the following models, depending on the nature of specific bug:
   - the data is non-existent in program memory, and then (sometimes good, and sometimes bad) data is loaded in program memory (from network, from file, from user input, etc). One should find exact function which does that, and what are its input parameters when it is producing good output, and what are its input parameters when it is producing bad output. Or,
   - the data is existent in program memory in good form (i.e. has `File:` prefix in one variable) at one place, but then (in some or all cases) at some later time at some other place the data is seen wrong (i.e. it loses `File:` prefix). One should find exact line of code where such transformation happens. Or,
   - the data is existing in program memory in bad form (i.e. without `File:` prefix) at one place, but then at the later time at other place it is (sometimes but not always) changed to good form (i.e. with `File:`) prefix.  One should find exact line of code where such transformation happens.

  Here are few ways to how to find _where_ that is happening:

  - I've [already suggested](https://github.com/commons-app/apps-android-commons/issues/5315#issuecomment-1901583742) one method: using debug logging at various places in the code and then checking the [logcat](https://developer.android.com/tools/logcat) debug output. I don't know if you tried it -- if you did, you should share your findings - i.e. at which line exactly does incorrect data (filename without `File:`) becomes correct (i.e. has `File:`). 
  - There are other methods which may be more comfortable to you, like using the debugger - e.g. see https://developer.android.com/studio/debug/

  In any case, that should be your fist task - find **WHERE** the bug happens. That is usually the **_most time consuming part_** of chasing reproducible bugs... 
  You say: _"However, I'm unable to find where exactly"_ -- why is that the case? Have you been able to find single place in the code where the value is correct? Have you been able to find single place in the code where the value is incorrect? If you did find those two, have you tried to narrow it down, that is, find other places where value is still correct but closer to place where it is incorrect, or vice versa? **_Can you detail exactly at what point in this process have you become stuck?_** I.e. which parts you've managed to do, and at which part of the process have you stuck? If you share that in enough detail, perhaps someone can give _specific_ advice how to overcome that _specific_ obstacle.   

- **_after_** one has found out _where_ does the bug happen, next task should be to determine **WHY** the bug happens. Looking at the inputs and outputs and code logic, determine what code path is taken when the output is correct, and what other code path is taken when output is incorrect. Compare them and get understanding what is different and why. If needed, write small example code snippets that replicate what those code paths in simple and short manner if looking at the whole of the code is too complex. That is actually often the easier part to do, when you already know *where exactly* the bug happens.  
- Only after **where** and **why** are known, can one try to ponder what would be the best **way to FIX** it. Sometimes it is simple coding error which needs fixing in already existing code (e.g. _some "if" statement might have used "or" instead of "and"_), sometimes it is adding some special case handling depending on the input (e.g. _if the data has not yet been fully received, wait until it is_), and sometimes it needs deeper refactoring (e.g. _this class is being used for two different purposes, and it is only suitable for one. So new classes should be made, each which inherits most of the code of the base class, but has special code for its distinct purposes_). But we can't know what is best / correct _way to fix it_ until we know _where_ and _why_ is the bug happening.


Anyway, sorry for the length, but I tried to detail it in small and individually understandable pieces to make it easier for you to tackle the problem. Let me know if something is unclear and I can try to explain it better! (Hopefully the effort that went into it can be reused for other usecases, as bug hunting process is often quite similar)

**Comment by mnalis** [comment] 2024-04-13 22:38
Hi @axelthepony27 have you made any progress? Are you still intending to work on this?

**Comment by mnalis** [comment] 2024-05-11 22:32
@axelthepony27 are you still interested in working on this Commons app issue, or would you prefer to be unassigned?

**Comment by mnalis** [comment] 2024-06-23 03:14
@nicolas-raoul: As @axelthepony27 seems MIA (please respond if you're still interested in working on this!), perhaps they could be unassigned so someone else might give it a try ?

**Comment by nicolas-raoul** [comment] 2024-06-25 13:23
@axelthepony27 feel free to ask to be re-assigned if you are still working on this. Thanks! :-)

**Comment by parneet-guraya** [comment] 2024-10-09 17:25
Hi :wave:, I was trying to reproduce this issue, but on-going uploads does not show in the main screen anymore (just like shown in the issue description) instead they are in a separate screen (accessed from top bar). But, in that, the list item doesn't do anything on the click. I guess it was recently changed. Is it intentional to not show details or is this a `TODO`?  In any case I couldn't reproduce this issue, more details below ->

I'm on latest `main`  and tried on default `betaDebug` flavor.

### Uploads screen doesn't show on-going upload.
![photo_6069042467652615958_y](https://github.com/user-attachments/assets/feac7dd7-14d6-45b8-bb53-5259309c95e6)

### This is the uploads screen
https://github.com/user-attachments/assets/3ba2a35c-9575-42b2-9f35-7ebea0b4077d

**Comment by nicolas-raoul** [comment] 2024-10-10 00:15
Thanks a lot @parneet-guraya for checking this!

Since there is no discrepancy anymore, this can be closed.

If there is anything to improve in the remaining wikitext generation, please anyone create a new issub, thanks! 🙂

**Closed** 2024-10-10 00:15 UTC
Labels: bug, good first issue

**Comment by parneet-guraya** [comment] 2024-10-10 00:30
Not sure, if it is notified after being closed. Anyways, should we also implement showing details of an on-going upload on tapping on it?

Thanks!

**Comment by nicolas-raoul** [comment] 2024-10-10 01:25
I don't think there is any strong need for media details while uploading. At least not enough to justify the complexity.

In particular, I don't think many people start adding wikicode for an image while it is still uploading.

**Comment by parneet-guraya** [comment] 2024-10-10 09:19
Makes sense 👍
