### ISSUE TITLE
"No location found" popup appears twice, when uploading with existing caption (title)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5286] opened 2023-09-08 09:10 UTC
Steps to reproduce:

1. Upload a JPG picture with any caption, let's say `XYZ`. It gets uploaded as XYZ.jpg
2. Start the wizard to upload a JPG picture that has no EXIF location.
3. The popup `No location` found appears. Tap `Skip`.
4. Problem: The exact same popup as in step 3 appears again.

The duplicate popup does not happen when wording a unique caption (or more exactly: when no file on Commons has that title).

**Comment by Qiuyang-Shen** [comment] 2023-10-09 02:25
Hi Nicolas, can I try to fix this issue?

**Comment by nicolas-raoul** [comment] 2023-10-09 11:33
@Qiuyang-Shen It is yours, thanks! 🙂

**Comment by Qiuyang-Shen** [comment] 2023-10-09 11:37
Cool! I'll try my best to solve it! 😁👍

**Comment by nicolas-raoul** [comment] 2023-10-12 14:44
The issue always happens in these circumstances, and I have observed it at least 1000 times, so it can't be a coincidental network error.

To reproduce, use the prodDebug build flavor, and upload several sets of pictures all with the same caption. If you need encyclopedia-worth pictures to upload, let me know. 🙂

**Comment by nicolas-raoul** [comment] 2023-10-16 09:56
Would you mind linking to one of your uploads? It may help me realize what is different. You can find the link at the top-right of an uploaded picture's details activity.

**Comment by Qiuyang-Shen** [comment] 2023-10-16 10:00
Sure, I guess you mean this: https://commons.wikimedia.org/wiki/File:Fossil_77.jpg
I uploaded all the pics using Fossil caption. I'll remove them when everything is done

**Comment by nicolas-raoul** [comment] 2023-10-16 10:18
Your pic looks very similar to mines in terms of metadata... 🤔

I use Android 14 on Pixel7Pro, if that matters.

Thank you for your persistence!

**Comment by Qiuyang-Shen** [comment] 2023-10-16 10:20
Got it. I'll try this on the platform you use and see whether this is the cause. 👍

**Comment by nicolas-raoul** [comment] 2023-10-16 10:24
https://github.com/commons-app/apps-android-commons/assets/99590/dc2f9908-315b-4b5d-888b-8cffa1c4022f

**Comment by nicolas-raoul** [comment] 2023-10-16 10:59
Full example, from reset app:

https://github.com/commons-app/apps-android-commons/assets/99590/d662c0c8-eec3-418e-87f7-d0097f87df3b

**Comment by Qiuyang-Shen** [comment] 2023-10-16 11:38
I just used the same caption "March 2007, boat in Valetta" on a Pixel 7 Pro emulator and it shows the bug which is exactly same as your given example. Then I changed to Pixel 2 which is the platform I working on so far it still doesnt reflect that bug: 
(the first pic with caption 'March 2007, boat in Valetta' is already uploaded)
https://github.com/commons-app/apps-android-commons/assets/141684967/245cb63c-cf50-491f-8cfe-0a27de5dd82f

**Comment by Qiuyang-Shen** [comment] 2023-10-16 11:53
Yeah I also tried to do the same operation on my XIAOMI 11, which has Android 13 and still, shows no problem. 🤔

**Comment by nicolas-raoul** [comment] 2023-10-16 13:28
If I understand correctly, you are able to reproduce the issue on your Pixel7Pro emulator? Then inserting breakpoints and running in debug mode will probably lead to the issue. 🙂

**Comment by Qiuyang-Shen** [comment] 2023-10-16 22:33
Yeah I can reproducet the issue on my Pixel7pro emulator. Sorry for making confusion. So I guess the bug only occurs on developer's side due to the debug mode? Unfortunately I can't choose to run the release version on Android Studio though I just cloned the latest version of the project. Should the breakpoints or relatetd stuff be removed for fixing this bug? Or just leave them their to avoid unexpect effects?

**Comment by nicolas-raoul** [comment] 2023-10-17 00:18
If for some reasons you can't use breakpoints, then you can investigate by outputting log lines.

**Comment by Qiuyang-Shen** [comment] 2023-10-17 01:59
Sorry Nicolas what I wonder is that whether we can conclude that this bug is caused by some unique device model, since so far we only observed the problem occurs on Pixel 7 pro. Should I try to use this device as emulator to see which part goes wrong? Since if this bug is caused by particular mobile phone models we actually cant do much for solving it. Or maybe we have to call google check what's the problem with their product design... 😂

**Comment by nicolas-raoul** [comment] 2023-10-17 03:35
Even if it only happens on a single model, still we must fix it. 🙂

**Comment by Qiuyang-Shen** [comment] 2023-10-17 06:12
Sure! I'll move on this way and see what I can do for it!

**Comment by nicolas-raoul** [comment] 2024-01-13 08:06
@Qiuyang-Shen Any progress to share? :-)

**Comment by Qiuyang-Shen** [comment] 2024-01-13 09:13
Sorry Nicolas for haven't share the progress for months.. Anyway my friends and I tried to discuss the problem with some teachers in our university, but unfortunately they didnt provided useful information about this problem as well. In this way, I'm really sorry to say that I've tried my best and others may have better understanding about this. 😭

**Comment by nicolas-raoul** [comment] 2024-01-13 09:53
@Qiuyang-Shen No problem! I will unassign this one, but do not hesitate to try again on a different issue. :-)

**Comment by ShashwatKedia** [comment] 2024-03-24 03:06
@nicolas-raoul, I believe this issue is the same as mentioned in point 3 of #5511 and is resolved by #5527, so this could be closed?

**Closed** 2024-03-27 07:34 UTC
Labels: bug
