### ISSUE TITLE
use of OpenStreetMap data without attribution (attributed to Mapbox in master version)

### ISSUE THREAD

**Issue by matkoniecz** [commons-app/apps-android-commons#3766] opened 2020-05-21 18:29 UTC
**Summary:** 

OpenStreetMap data requires attribution to be used and this attribution is missing, at least on my phone. 

**Steps to reproduce:** 

Start app, switch to "nearby" tab with map without attribution.

Attribution hidden in settings also would be insufficient, but not even that is done.

Data is clearly from OpenStreetMap (with contour lines added) as confirmed by looking at data unique to OSM and not appearing elsewhere.

See https://www.openstreetmap.org/copyright

**System logs:**

Not attempted, will add if missing attribution is something device-specific.

**Device and Android version:** 

Mi A2 Lite, running stock Android Zero, in Android 9 version.

**Commons app version:** 

2.12.3~dc08a5e88

**Screen-shots:** 

Will add if problem will turn out to be device-specific.

**Would you like to work on the issue?**

I am not planning to do this, I have already more OpenStreetMap related plans that I am able to do and this is something that users of data are legally obligated to do.

**More info**

You are using OpenStreetMap data for displaying maps. Great and thanks for using this map data!

It is nice to see that you use what I (and thousands of other mappers) collected. But you are doing it without a required attribution, that according to the licence must be clearly visible to all users.

This is quite embarrassing, given that Wikimedia Commons community is generally excellent at respecting copyright and copyright like restrictions.

**Comment by maskaravivek** [comment] 2020-05-21 19:10
Yes, unfortunately, the current production version of the app doesn't have attribution. It seems that the attribution got removed sometime before the last release. 

It was present in the previous versions of the app. A lot of changes were done recently on the maps page because of which it might have got missed. See #2911 for reference. 

Our latest master has the attribution present and I believe it would be released soon to production. cc @misaochan 

Screenshots from latest master: 

<img width="364" alt="Screen Shot 2020-05-21 at 11 52 56 AM" src="https://user-images.githubusercontent.com/3069373/82596370-05832a00-9b5c-11ea-8238-59ef2798d30b.png">
<img width="360" alt="Screen Shot 2020-05-21 at 11 53 22 AM" src="https://user-images.githubusercontent.com/3069373/82596382-09af4780-9b5c-11ea-966b-703192a563bd.png">

**Comment by matkoniecz** [comment] 2020-05-21 19:59
It is great that it is better in master version.

But note that you are using OpenStreetMap data, hosted and styled by Mapbox. 

Mapbox may have their own additional requirements. 

But https://www.openstreetmap.org/copyright requires notice associated with the map reasonably calculated to make **any** Person that views the map aware that content was obtained from the OpenStreetMap database.

It is requirement that cannot be modified or changed by Mapbox, and showing "Mapbox" is not fulfilling it. It must be attributed to OpenStreetMap (though Mapbox may be additionally credited for map styling and hosting).

Note section 4.3 of the [Open Database License](https://www.opendatacommons.org/licenses/odbl/1.0/) used by OpenStreetMap:

> "include
> a notice associated with the Produced Work reasonably calculated to
> make any Person that uses, views, accesses, interacts with, or is
> otherwise exposed to the Produced Work aware that Content was
> obtained from the Database, Derivative Database, or the Database as
> part of a Collective Database, and that it is available under this
> License."

I know that what you show in this images it is apparently standard attribution proposed by Mapbox. But I hope that at least in this case proper attribution will be used (yes, I know that Moovit, Mapbox, FB, Snapchat are also hiding attribution and using OSM data anyway and describing maps in way suggesting that they collected data on their own).

**Comment by matkoniecz** [comment] 2020-05-21 20:03
Using OpenStreetMap data and using "Mapbox" as an attribution is like taking Wikimedia Commons image (on license requiring attribution) and using "author: internet" or "author: me, I found it with google" as an attribution.

**Comment by maskaravivek** [comment] 2020-05-22 02:12
Thanks for the detailed explanation @matkoniecz. We will fix it as soon as possible. 

Currently when the (i) icon is clicked on the map, a dialog box appears as shown above. It shows (c) OpenStreetMap. Is it not the right way of attributing OpenStreetMap? Should the attribution be in the text on the map itself? As shown in this screenshot from the https://www.openstreetmap.org/copyright page. 

<img width="216" alt="Screen Shot 2020-05-21 at 7 08 25 PM" src="https://user-images.githubusercontent.com/3069373/82624262-f7063400-9b96-11ea-9cab-179adc8c2ea2.png">


Tagging @neslihanturan as she is our designer. She might have ideas on how we could display proper attribution.

**Comment by matkoniecz** [comment] 2020-05-22 09:55
> (i) icon is clicked on the map, a dialog box appears as shown above. It shows (c) OpenStreetMap. Is it not the right way of attributing OpenStreetMap?

The problem is that 

* it requires clicking on (i) icon while license requires attribution to be "reasonably calculated to make any Person that views the map aware"
  - and it is quite obvious that normal user will not click on every icon and therefore will never see it
* there is a big Mapbox logo and popup lists (c) Mapbox first
  - So normal user will see solely Mapbox attribution and even popup window is not clarifying situation
  - it is done in way suggesting that data is from Mapbox. As hosting is not copyright protected sole copyrightable work by Mapbox is map styling. All map data is (c) OpenStreetMap.

"(c) OpenStreetMap" is attribution fulfilling license. "(c) OpenStreetMap contributors" is suggested, but not required by license. For 100% compliance either linking to full license or mentioning ODBL would be nice.

But the major and fundamental problem is that OpenStreetMap attribution is effectively hidden, while clear Mapbox attribution is shown.

Note that you may be required to show Mapbox logo by their terms of service, so you may need to show both

* "(c) OpenStreetMap (ODBL)", "[(c) OpenStreetMap](https://www.openstreetmap.org/copyright)", "[(c) OpenStreetMap contributors](https://www.openstreetmap.org/copyright)"  or other **clearly visible** attribution fulfilling license. This part must not be affected by Mapbox terms (though their design decision may make more complicated to apply proper attribution)
* Mapbox logo (one of perks of more expensive plan is that Mapbox is not requiring you to show Mapbox logo - note that Mapbox is unable to waive OSM license)

disclaimer: I am not a lawyer, I am biased toward OSM attribution as an OSM mapper.

But I am pretty sure that "Mapbox" with hidden "(c) Mapbox (c) OpenStreetMap" is not making clear that all data is from OSM.

And "reasonably calculated to make any Person that views the map aware (...)" is nor fulfilled by attribution hidden behind icon that normal user will never click.

**Comment by matkoniecz** [comment] 2020-05-22 09:57
BTW, thanks for very quick reaction made by actual humans - unlike to some major corporations using OSM data without any attribution (or extremely poor one, designed to mislead user).

**Comment by matkoniecz** [comment] 2020-06-04 16:22
I added this app to page listing entities using OpenStreetMap data without attribution - in https://wiki.openstreetmap.org/w/index.php?title=Lacking_proper_attribution&type=revision&diff=1997453&oldid=1997351

**Comment by maskaravivek** [comment] 2020-06-04 17:28
Thanks for the detailed explanation. I will bump up this issue internally. 

> But the major and fundamental problem is that OpenStreetMap attribution is effectively hidden, while clear Mapbox attribution is shown.

Would you be able to point us to any app/website that correctly shows the Mapbox and OpenStreetMap attributions? I am requesting this from you with the assumption that you might have come across quite a few open source app that are using these maps. 

Tagging few of our collaborators here: 
@misaochan @nicolas-raoul @neslihanturan @sivaraam

**Comment by sivaraam** [comment] 2020-06-04 17:43
> Would you be able to point us to any app/website that correctly shows the Mapbox and OpenStreetMap attributions?

I think the info in the following page is a good start: https://wiki.openstreetmap.org/wiki/They_are_using_OpenStreetMap

I'll let you know if I find something better.

**Comment by sivaraam** [comment] 2020-06-04 17:46
> I think the info in the following page is a good start: https://wiki.openstreetmap.org/wiki/They_are_using_OpenStreetMap

Mentioning the source, for the sake of completeness:

> See also [They are using OpenStreetMap](https://wiki.openstreetmap.org/wiki/They_are_using_OpenStreetMap) for rather correct attribution examples. 

[Source](https://wiki.openstreetmap.org/wiki/Lacking_proper_attribution#List_of_usages_lacking_proper_attribution)

**Comment by maskaravivek** [comment] 2020-06-04 17:50
> https://wiki.openstreetmap.org/wiki/They_are_using_OpenStreetMap

Thanks @sivaraam. It would be great if someone could check a few apps from this list and share a screenshot here of the map page from apps with proper attribution. It would be easier for anyone to pick up the fix that way.

**Comment by matkoniecz** [comment] 2020-06-04 17:52
> Would you be able to point us to any app/website that correctly shows the Mapbox and OpenStreetMap attributions? I am requesting this from you with the assumption that you might have come across quite a few open source app that are using these maps.

https://nuclearsecrecy.com/nukemap/ (though I admit that phone styling suffers from too small text everywhere - but as it is not applied to just attribution I am OK with that, also for some reason wrong license is given).

Part applicable here with a fixed license would be "Map data © OpenStreetMap contributors (ODBL), Imagery © Mapbox"

**Comment by misaochan** [comment] 2020-06-04 18:12
If the format at https://foursquare.com/explore?mode=url&near=Gda%C5%84sk%2C%20Poland&nearGeoId=72057594041027370 is acceptable, that would be my preference. On mobile screens there is very little space.

**Comment by matkoniecz** [comment] 2020-06-04 18:17
"© Mapbox © OpenStreetMap" in always visible text, with `Mapbox` linking to whatever Mapbox requires and `OpenStreetMap` linking to https://www.openstreetmap.org/copyright should be OK.

Or "© Mapbox © OpenStreetMap (ODBL)" for version without links.

Disclaimer: I am not a lawyer, it is what I think that license requires and would be enough to keep me happy.

**Comment by misaochan** [comment] 2020-06-11 09:30
Interesting, it does say that "You may not otherwise alter the Mapbox wordmark or text attribution notice", so if we made this change we would be breaching Mapbox's terms.

@matkoniecz Any chance you can take this up with Mapbox themselves?

**Comment by sivaraam** [comment] 2020-06-11 12:09
> Interesting, it does say that "You may not otherwise alter the Mapbox wordmark or text attribution notice", so it seems to me that if we made this change we would be breaching Mapbox's terms.

Yes. But they also [say this](https://docs.mapbox.com/help/how-mapbox-works/attribution/#mapbox-maps-sdk-for-android):

> By default, the Mapbox wordmark and information button are located on the bottom left of the map. You may move these elements to a different position, but they must stay on the map view. For display options, see the API documentation for the UiSettings class. You may also reposition these elements within the activity’s XML layout.
>
> Mapbox includes this built-in information button for your convenience. If you decide not to use it, you must include attribution on the map in a text format. The attribution must include © Mapbox as a link to https://www.mapbox.com/about/maps/, "© OpenStreetMap" as a link to http://www.openstreetmap.org/copyright, and "Improve this map" as a link to https://www.mapbox.com/map-feedback/. If you choose to use one of our Satellite styles, you must also include © DigitalGlobe as a link to https://www.digitalglobe.com/. Note that in the future, Mapbox may update the information on the attribution panel and require additional attribution to our suppliers.

Observe how the second paragraph provides us with an option to include on the map in a text format which is exactly in the format that OSM requires (in addition to some Mapbox requirements).

I guess the problem is they don't say _how_ that could be done 🤔

**Comment by matkoniecz** [comment] 2020-06-11 16:42
> @matkoniecz Any chance you can take this up with Mapbox themselves?

I can try, but Mapbox is remarkably slow where it comes to topic of attributing OpenStreetMap.

**Comment by misaochan** [comment] 2020-07-01 10:20
Hi @matkoniecz , any luck with Mapbox? I feel like it will be much more beneficial to your cause for Mapbox to support this in their SDK. Otherwise all the apps that are using the Mapbox Android SDK will be stuck looking for lengthy, potentially hack-ish workarounds since they have not exposed methods to modify the attribution.

**Comment by matkoniecz** [comment] 2020-07-01 10:49
Not from Mapbox (their response time on topic of attribution is in months, in some cases more than year) but I got some info on Telegram channel (OpenStreetMap dev):

> By default attribution with the information button is included in the sdk. You can adjust it with XML or go into the UiSettings object

I have not tested it so far.

**Comment by ashishkumar468** [comment] 2020-07-01 11:01
I have opened an [issue](https://github.com/mapbox/mapbox-gl-native-android/issues/447) in the Mapbox's repo raising the concern, hopefully we will get some clarity from over there.

**Comment by sivaraam** [comment] 2020-07-18 18:26
> I guess the problem is they don't say _how_ that could be done.

Some time ago, I happened to contact Mapbox support about this with hope of getting something useful. This is what they say:

> You can put the text attribution on the map instead of using our UISetting, but you would still need to link to the attribution links https://www.mapbox.com/about/maps/ and http://www.openstreetmap.org/copyright somehow, such as in the menu, or by adding a TextView on the map. In addition to the attribution links, you will need to put the [telemetry opt-out](https://docs.mapbox.com/android/maps/overview/#telemetry-opt-out) button somewhere, such as in your settings.

The only hint is that they mention adding a `TextView` on the map.

**Comment by misaochan** [comment] 2020-07-22 10:08
@ashishkumar468 just informed me that his workstation is down and repairs will take a while due to the Covid situation where he is. We will look into this further when he is able to come back.

**Comment by sivaraam** [comment] 2020-07-24 07:57
> Some time ago, I happened to contact [Mapbox support](https://support.mapbox.com/hc/en-us) about this with hope of getting something useful.

Just an update about this.

<details>
<summary>I asked them for an example/specific instructions on how to achieve this.</summary>

Thanks for the response. I'll look into and let you know if we could find a way to add a TextView on the map. In the meantime, if you could share specific instructions/examples of how to achieve this that would be great.
</details>

This is the response that I got:

> Because this is not a standard use of our attribution text, the implementation will be up to you.

So, hopes there.

**Comment by ashishkumar468** [comment] 2020-08-13 18:27
This is fixed on 2.13, closing this PR, the changes should be visible in the next release.

**Closed by ashishkumar468** 2020-08-13 18:27 UTC
Labels: bug

**Comment by misaochan** [comment] 2020-08-31 15:45
Hi @matkoniecz , this should be out in our current beta release, v2.13.1. Could you please register for beta testing and let us know if it works for you? Thanks!

**Comment by matkoniecz** [comment] 2021-03-12 22:20
Sorry for delay! I see that it is now fixed, thanks!
![Screenshot_20210312-173148](https://user-images.githubusercontent.com/899988/111004370-3b162f80-8389-11eb-93c5-5c3764389172.png)

**Comment by misaochan** [comment] 2021-03-17 12:34
Happy to hear that, @matkoniecz ! Any chance of updating your Google Play review? ;)

**Comment by matkoniecz** [comment] 2021-03-17 12:38
Thanks for a reminder, also fixed! (now also response should be changed, currently it is quite funny :) )

**Comment by misaochan** [comment] 2021-03-17 12:50
Hmm, I can't seem to find my old response, I guess it might be automatically hidden when the review is updated? Anyway, thanks a lot @matkoniecz . :)

**Comment by matkoniecz** [comment] 2021-03-17 12:55
![screen04](https://user-images.githubusercontent.com/899988/111470709-7073a200-8728-11eb-98c9-d9206258b551.png)

I guess that I will edit it to include original complaint.
