### ISSUE TITLE
Wikidata items repeated in Explore

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3137] opened 2019-08-22 13:05 UTC
1. Go to Explore
2. Type "apple"
3. Tap "Items"
4. Scroll
5. Notice that some items appear several times, for instance "apple cultivar"

**Comment by vanshikaarora** [comment] 2019-08-24 08:54
@nicolas-raoul I noticed that only some values are repeated and not all of them. I used breakpoints and checked for the offset value while calling the APIs. They seem to be perfect. I am not sure, but it might be an issue with the API

**Comment by nicolas-raoul** [comment] 2019-08-24 09:18
can you please output all thumbnail urls to logcat?

**Comment by vanshikaarora** [comment] 2019-08-24 09:20
okay

**Comment by Rui-Zhang1997** [comment] 2019-10-27 00:39
May I be assigned this issue?

**Comment by nicolas-raoul** [comment] 2019-11-06 13:14
@Rui-Zhang1997 Yes, thank you, and sorry for the late reply! Please let us know about your progress :-)

**Comment by nicolas-raoul** [comment] 2020-01-27 04:36
@Rui-Zhang1997 Are you still working on this? Feel free to post any findings or code, even if incomplete :-)

**Comment by nicolas-raoul** [comment] 2020-03-16 13:57
Still happening.

**Comment by vvijayalakshmi21** [comment] 2020-04-03 06:37
Hi @nicolas-raoul I checked this and I believe after the second set of 25 items are fetched, they're simply repeating. From the attached screenshots we can see that after pyrus item the first item of the second 25 fetched is displayed. This keeps happening upon scrolling further down. 
A couple of reasons I could think of for this issue are:
1. We're not properly requesting the next page
2. Not updating the UI even though the data fetched from the server are right.

I will debug further and share my analysis here

**Comment by vvijayalakshmi21** [comment] 2020-04-03 06:44
![Screenshot_20200403-115735](https://user-images.githubusercontent.com/34595292/78331482-bed57280-75a3-11ea-9416-357c6dd19702.png)
This shows the last item displayed from the first call. (British Rock band)
![Screenshot_20200403-121149](https://user-images.githubusercontent.com/34595292/78331766-5935b600-75a4-11ea-824a-3696fe5536a1.png)
This shows the first few items of the second 25 call.

![Screenshot_20200403-115749](https://user-images.githubusercontent.com/34595292/78331557-f0e6d480-75a3-11ea-839c-01465ac9db11.png)
This shows the last item in the second 25 call. (Pyrus)

![Screenshot_20200403-115758](https://user-images.githubusercontent.com/34595292/78331834-7b2f3880-75a4-11ea-960b-fd6d5bb65035.png)

Then the first item of the second call repeats

**Comment by vvijayalakshmi21** [comment] 2020-04-04 03:49
If we slow-scroll down the items or debug the code, the issue does not occur. The item list is properly updated without repetitions. It is only when the user keeps scrolling down the items without allowing the call to the server to finish, we see the issue. 
The below code snippet gets executed more times than once when the user scrolls down faster resulting in the list being displayed with repeated items.

![image](https://user-images.githubusercontent.com/34595292/78417964-426f7d80-75fd-11ea-8b50-323541683695.png)

**Comment by vvijayalakshmi21** [comment] 2020-04-04 04:49
On further analysis I can see that when a user scrolls down faster, the firstVisibleItemPosition and visibleItemCount variables change rapidly and in a way that the above if condition is satisfied. Please find attached the variable values when we slow-scroll or Debug and fast-scroll the items.
We can clearly see that we are making more than one call with the same offset value 25.

[fast scroll.txt](https://github.com/commons-app/apps-android-commons/files/4430767/fast.scroll.txt)
[slow scroll.txt](https://github.com/commons-app/apps-android-commons/files/4430768/slow.scroll.txt)

**Comment by vvijayalakshmi21** [comment] 2020-04-04 16:57
The problem seems to be with isLoading variable not being updated when there is a call in progress. This results in duplicate calls (ie with same offset id). If we update this variable, then we can avoid the call and subsequently the duplication of items in the list.

**Comment by vvijayalakshmi21** [comment] 2020-04-04 17:20
I made some changes and tested quickly. I can see that now there is no repetition of items irrespective of the speed of scroll. Attaching the logs I wrote to output the variable values 
[logs_isloading_updated.txt](https://github.com/commons-app/apps-android-commons/files/4432032/logs_isloading_updated.txt)

**Comment by nicolas-raoul** [comment] 2020-04-05 08:58
@vvijayalakshmi21 Wonderful! :-)

**Comment by macgills** [comment] 2020-04-10 10:35
The linked PR does resolve the issue but the root cause of these inconsistencies should be addressed in #3462  which currently has a too wide scope given how many paginated endpoints there are, perhaps individual tickets for the list + endpoint pairs

**Comment by nicolas-raoul** [comment] 2020-04-10 10:46
@macgills Thanks for reviewing the PR! :-)

**Closed** 2020-04-21 10:27 UTC
Labels: bug, structured-data
