### ISSUE TITLE
Nearby Tab Accessible Without Location Permission

### ISSUE THREAD

**Issue by nathanmeade** [commons-app/apps-android-commons#3732] opened 2020-05-05 22:09 UTC
**Summary:** 
When the user has not granted permission for location, the nearby tab can still be accessed when performing the appropriate steps - displaying the nearby tab and map without any results. To prevent the displaying of the nearby tab without any results in this case, the edge cases that allow for the user selecting the nearby tab without the location permission (no location data) need to be fixed.

This issue was discovered when attempting to reproduce the blank nearby list issue (#3727) @neslihanturan 

**Steps to reproduce:** 

1. Make sure the app does not have the location permission
2. While logged in, select the "Nearby" tab of the "Home" screen
3. Deny the access to location
4. Select "No" to the permission request dialog
5. Select the "Nearby" tab again
6. Tap away from the dialog to make it disappear
7. Observe that there are no results

 
**Screen-shots:** 
No results map screenshot:
![nearbyNoResultsMapScreenshot](https://user-images.githubusercontent.com/9450306/81120452-bf428f80-8efa-11ea-8a0b-44d537725cfa.jpg)

No results list screenshot:
![nearbyNoResultsListScreenshot](https://user-images.githubusercontent.com/9450306/81120491-d2edf600-8efa-11ea-8e7a-7f6e4437cde9.jpg)

**Would you like to work on the issue?**

I would like to work on this issue.

**Comment by neslihanturan** [comment] 2020-05-06 13:32
Yes @nathanmeade , you understood the issue right. User should never see this empty map at all.

**Comment by gerardolgvr** [comment] 2020-06-11 04:41
Hello! Is this fixed? 

I was thinking about some possible solutions to this problem: 
- Add an extra message telling the reason why is location permission important (using shouldShowRequestPermissionRationale). I found this useful information (https://stackoverflow.com/questions/30719047/android-m-check-runtime-permission-how-to-determine-if-the-user-checked-nev) 
- If the user doesn't grant permission we can replace the map fragment with another fragment and inside place a button to have quick access to grant the permission for location.

Let me know your thoughts, have a nice day

**Comment by neslihanturan** [comment] 2020-06-11 10:00
Thank you for suggestions @gerardolgvr , the issue is still not fixed. You can work on this one. I think ideal solution is sending the user back to contributons fragment when permission is not given.

**Comment by gerardolgvr** [comment] 2020-06-11 14:54
oh yeah, sounds a great idea @neslihanturan 

Seems well to you a Toast to give information why user is returned to contributions fragment? In order let know the user what's happening 

Example "Location permission is required" -> the text is an example

**Comment by nathanmeade** [comment] 2020-06-12 14:02
@neslihanturan @gerardolgvr I have not been able to get to this fix yet. Feel free to reassign this as you see fit.

**Comment by Anyrob** [comment] 2020-06-12 18:46
Hi! I would like to take it if you don't mind, I already have thought a solution, just waiting for you, to give me green light :) @neslihanturan @gerardolgvr

**Comment by neslihanturan** [comment] 2020-06-12 18:48
Please go for it @Anyrob :)

**Comment by neslihanturan** [comment] 2020-06-12 18:48
Thank you @nathanmeade for your time and reporting your unavailability.

**Comment by Anyrob** [comment] 2020-06-12 18:49
Thank you!! @neslihanturan

**Comment by gerardolgvr** [comment] 2020-06-12 18:50
Go ahead @Anyrob ! :D

**Comment by Anyrob** [comment] 2020-07-02 15:45
Hi, @neslihanturan! I was wondering if you have had a chance to check my pull request. This time, I was trying to add some test but I ran into a lot of problems since other tests are broken even though I try different ways (even with espresso which also helped me discover another bug in the application) I did not find a way to perform the test in any way other than manual, do you have any recommendations for me?

**Comment by sivaraam** [comment] 2020-07-02 17:52
> I think ideal solution is sending the user back to contributons fragment when permission is not given.

I doubt whether that's an ideal solution given that we have a "Search this area" feature. I wonder why there should be a hard requirement on the location permission when Nearby could be used to browse places even without the location permission, as I understand it. 🤔

**Comment by misaochan** [comment] 2020-07-03 10:35
> I wonder why there should be a hard requirement on the location permission when Nearby could be used to browse places even without the location permission, as I understand it

I'm not sure if the Mapbox SDK itself requires location permissions to function, but if it doesn't, that could be a possibility. However, which section of the globe should we display initially to the user if we don't know where they are? ;)

**Comment by sivaraam** [comment] 2020-07-03 17:56
> I'm not sure if the Mapbox SDK itself requires location permissions to function, but if it doesn't, that could be a possibility. 

Sounds great!

> However, which section of the globe should we display initially to the user if we don't know where they are? ;)

I think we already know the answer to that, "Tower of London":
![Screenshot_2020-07-03-23-07-47](https://user-images.githubusercontent.com/12448084/86489713-ca8f2b80-bd82-11ea-9386-7052e2b1953d.png)


This is location that the app shows now before it gets the actual location of the user (i.e. when the GPS is turned off, GPS is triangulating user's location etc.). Alternatively, we could follow what the Wikipedia app did in this case when it had the Nearby feature which, to the best of my memory, is showing the zoomed-out globe view ;-)

**Comment by Pratham2305** [comment] 2021-02-05 13:52
Hi! I would like to work on this.
I agree with @sivaraam,  I think we can initially show a zoomed out map and if the user allows the permission then we can zoom to the user's location otherwise, we can still enable the "search this area" button and allow the user to use it and upload images.

**Comment by misaochan** [comment] 2021-02-17 11:55
Hi @Pratham2305 , sorry for the slow response! Are you still interested in working on this?

I agree with you and @sivaraam , the "search this area" button should be allowed regardless, and pins should still be loaded. For the initial area to display, I'm OK with either a zoomed out view, or a random location, or even the Tower of London ;). But if we go with a zoomed out view, we do have a limit on the number of pins that can be loaded, so we will not be able to display all the pins in a zoomed out area. 

Also, I just realized that #4198 is a duplicate of the discussion here, so I will close that.

**Comment by Pratham2305** [comment] 2021-02-17 20:15
@misaochan Yes, I would love to work on this one.

**Comment by misaochan** [comment] 2021-02-18 16:37
@Pratham2305 It is yours. :) Please keep us updated on your progress.

**Comment by Ayan-10** [comment] 2021-09-04 13:38
@misaochan @nicolas-raoul I think this issue is not resolved yet. Nearby is still not working without location permission and it also not working if GPS is turned off. Nearby just do nothing if location permission is not there and GPS is not turned on. See this video.

https://user-images.githubusercontent.com/71203077/113769242-639e0900-973e-11eb-9c44-a589def192f9.mp4

(The video is a little old but I tested the app on latest master it behaves the same with a endless progressbar)

Tested latest master betaDebug on Samsung J2 API 23 and Pixel 2 emulator API 30

**Comment by nicolas-raoul** [comment] 2021-09-04 20:14
I haven't tried on master, but I just tried on 3.1.0~b41882639:

1. Remove the app's location permission (in Android apps settings)
2. Open the Commons app
3. Tap the Nearby tap
4. Dialog `Requesting Location Permission` appears, tap `cancel` to deny
5. Spinner spins
6. I am shown the items nearby London's Tower Bridge

In other words, it seems to work as intended for me.

@Ayan-10 would you mind detailing the steps you are using?

**Comment by Ayan-10** [comment] 2021-09-05 04:07
@nicolas-raoul I tested on both Samsung J2 API 23 and Pixel 2 emulator API 30 devices. 

**On master**

1. Remove the app's location permission (in Android apps settings)
2. Open the Commons app
3. Tap the Nearby tap
4. Dialog `Requesting Location Permission` appears, tap `cancel` to deny
5. Spinner spins for endless time and nothing is shown.

I waited for 10 minutes but Nearby only showing a spinner spinning.

Also, I noticed that If GPS is turned off It behaves the same way. Only spinner spinning nothing happens.
1. Make sure the permission is turned on
2. Turn off GPS
3. Tap the Nearby tap. (Don't turn on GPS)
4. A toast popped up saying `Nearby might not work properly, Location not available.`
5. Spinner spins for endless time and nothing is shown.

**Comment by Ayan-10** [comment] 2021-09-05 06:55
@nicolas-raoul So what are expecting from Nearby? I think Nearby should work without location permission and GPS and also Users can add images in any place without location permission and GPS. Users only need to give location permission and GPS when they want to locate themself. 

Am I right? Please correct me if I am wrong.

Thanks.

**Comment by nicolas-raoul** [comment] 2021-09-05 14:52
_Nearby should work without location permission_ -> yes

_Users can add images in any place without location permission and GPS_ -> yes

Users who do not have a GPS or do not want to give permission should be allowed to unzoom/pan/zoom to the place they want, and tap `Search this area` to see places.

**Comment by Ayan-10** [comment] 2021-09-07 21:02
It seems that `mapbox` is getting null somehow. That's why it's not working without permission.

**Comment by sivaraam** [comment] 2022-01-23 11:21
@Ayan-10 Just trying to figure out what the precise problem you're observing is. Do you see the "Search this area" button when you choose a particular location in the map? If you do see it, do you see no pins even when you zoom to a particular location and use "Search this area" button ? 

I'm asking this as Nearby would likely do nothing by default without the location permission when you don't use the "Search this area" button.

> Users who do not have a GPS or do not want to give permission should be allowed to unzoom/pan/zoom to the place they want, and tap Search this area to see places.

I tested this on  a OnePlus Nord and it appears to be working for me.

**Comment by Ayan-10** [comment] 2022-01-23 18:39
@sivaraam It seems **some of the issues** that I mentioned here are not occurring now. You can check [this comment](https://github.com/commons-app/apps-android-commons/issues/3732#issuecomment-913082506) where I mentioned the issues that were occurring at that time and way of reproducing them in detail.

In the current master, "the nearby tab is not working at all without permission and the spinner just spins" this issue seems to be fixed. Now nearby tab is working as expected (By default it's showing the Tower of London and the pins of the location around that area).

However, "the nearby tab is not working at all without GPS enabled" this issue is still occurring. When I opened the nearby tab without GPS enabled it shows a toast by saying "Nearby might to work properly, Location not available" and after that nothing happens, I can zoom and pan to any place but no pins are showing, no search button is showing. 

I hope it should not work like that. Even without the GPS enabled I should be allowed to tap Search this area to see places and see all the location pins in a specific area, and it should already be zoomed to the Tower of London for the first time I open the nearby by default. Moreover, it should work the same as the way nearby is working without permission.

**Steps to reproduce the issue**
1. Make sure the permission is turned on
2. Turn off GPS
3. Open commons
5. Tap the Nearby tap. (Don't turn on GPS)
6. A toast popped up saying Nearby might not work properly, Location not available.
7. Nearby is not working at all

Can you reproduce it in the same way? I tested the latest master prodDebug on Realme GT master API 30 and the GPS issue is occurring for me.

Thanks

**Comment by sivaraam** [comment] 2022-01-24 17:20
> Can you reproduce it in the same way? I tested the latest master prodDebug on Realme GT master API 30 and the GPS issue is occurring for me.

Yeah. With the steps you mention, I do reproduce the issue where the "Search this area" button is not being shown. This is with 3.1.1~1c9267ca0.

So, looks like the app works fine when the location permission itself is not available but fails to show the "Search this area" button if the permission is available but GPS is turned off. Nice catch.

**Comment by Ayan-10** [comment] 2022-01-26 07:19
@sivaraam @nicolas-raoul I have fixed the issue. Can I make the PR?

**Comment by nicolas-raoul** [comment] 2022-01-26 08:17
@Pratham2305 Are you still working on this? I see you are currently assigned. Thanks! :-)

**Comment by nicolas-raoul** [comment] 2022-01-27 04:25
@Pratham2305 Thanks for your sportsmanship!

**Closed** 2022-02-05 15:46 UTC
Labels: enhancement, assigned
