### ISSUE TITLE
User unable to select camera or gallery button

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3917] opened 2020-09-01 14:17 UTC
From our google groups forum:

> After logout and login in, I am not able to select the image or camera button. After clicking on button nothing happens.

-- Technical information --
API level: 29
Android version: 10
Device manufacturer: Xiaomi
Device model: POCO F1
Device: beryllium
Network type: wifi
App version name: 2.12.3~dc08a5e88

![IMG_20200901_164422](https://user-images.githubusercontent.com/3611199/91862619-8e5c4680-ecb1-11ea-8e73-d1d9bfac21a0.jpg)

From the screenshot it seems like his contributions are not loading either (it says he has 110 but none are displayed in the list).

**Comment by shabar-shab** [comment] 2020-12-24 06:19
@nicolas-raoul can I work on this?

**Comment by nicolas-raoul** [comment] 2020-12-24 08:08
@shabar-shab Is the issue reproduced on your device (or emulator)?

**Comment by asraman9792** [comment] 2021-01-20 14:42
@nicolas-raoul Sir can i work on this issue as my first issue ?

**Comment by nicolas-raoul** [comment] 2021-01-20 14:52
@asraman9792 Did you manage to reproduce the issue? That's the hardest part actually, as it does not happen on all devices I have tried.

**Comment by asraman9792** [comment] 2021-01-20 14:56
@nicolas-raoul Sir I have MI k20 pro as it does not happen with it will check with the other devices I have

**Comment by mrudultora** [comment] 2021-02-23 03:40
I tired this in many devices but was unable to reproduce. May be resolved ?

**Comment by nicolas-raoul** [comment] 2021-02-23 04:45
@mrudultora It might be resolved, but most probably it does not happen on your devices because it only happens on a very limited number of device types.

**Comment by nicolas-raoul** [comment] 2021-02-23 04:45
Anyone with a Xiaomi POCO F1? If yes, are you able to reproduce this issue? Thanks a lot :-)

**Comment by misaochan** [comment] 2021-02-24 12:02
The closest device that I have access to is a RedMi Note 7 (same manufacturer) and I cannot reproduce the issue with that. :/

**Comment by mrudultora** [comment] 2021-02-24 12:08
@misaochan Same, I am using Redmi Note 7S and not able to reproduce in that. Infact, I tried in Redmi 5A and Redmi Note 5, but was unable to reproduce in them also.

**Comment by Rishavgupta12345** [comment] 2022-03-01 06:30
@nicolas-raoul  THIS issue is pretty old and now we can easily select camera/gallery. So there is no such bug and we can close this issue safely

**Closed** 2022-03-01 06:35 UTC
Labels: bug, gallery
