### ISSUE TITLE
[Bug]: on `Edit` button, there is `+` sign overlayed over letter `E`

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5388] opened 2023-11-17 12:49 UTC
### Summary

In `Step 1/4: Media Details` part of the upload, the `EDIT IMAGE` button shown at bottom left has `+` sign overlayed over letter `E`.

### Steps to reproduce

1. open the app
2. click on `+` button and choose gallery
3. select some picture

### Expected behaviour

window that opens should have normal text `EDIT IMAGE` without any `+` sign overlayed (or, if there is some extra functionality being offered by that `+` sign, it should be separate and clickable). 

### Actual behaviour

`EDIT IMAGE` is shown with `+` over letter `E`, making it unreadable

### Device name

Huawei P30Pro

### Android version

Android 10 (EMUI 12)

### Commons app version

4.2.1 ~14b6c455b (latest f-droid)

### Screen-shots

![Screenshot_20231117_134256_fr free nrw commons](https://github.com/commons-app/apps-android-commons/assets/156656/0043982d-7e4c-4edf-8003-de01d21823b2)

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment] 2023-11-17 13:34
Thanks for reporting!
I can reproduce this bug by increasing font size in the Android settings:

![Screenshot_20231117-223247.png](https://github.com/commons-app/apps-android-commons/assets/99590/75ee7be2-fbad-489b-8724-cdcfb61e64ae)

**Comment by chsaikumar445** [comment] 2023-12-11 10:21
I tried to reproduce it but I am not getting that can you try to post more details on how to reproduce

**Comment by kanahia1** [comment] 2024-01-15 04:52
Hi @nicolas-raoul , Kindly :-) asking do we really need to work on this issue. Since we are moving `+` sign in design as discussed on https://github.com/commons-app/apps-android-commons/issues/5404

**Comment by nicolas-raoul** [comment] 2024-01-15 07:13
@kanahia1 Well you are right that sounds like a better place for the `+`... @ShashwatKedia sorry for not connecting the dots but I think at the right of the first language is a more intuitive place for the `+`... would you mind moving it there? That would solve the overlapping issue.

**Comment by kanahia1** [comment] 2024-01-15 08:35
@ShashwatKedia We can work together on new design of upload activity 🫂 _if you agree_

**Comment by ShashwatKedia** [comment] 2024-01-15 10:12
> @ShashwatKedia We can work together on new design of upload activity 🫂 _if you agree_

@kanahia1 sure, would love to do that. We can discuss further proceedings through Zulip if you want, I've pinged you there

**Closed** 2024-01-23 14:03 UTC
Labels: bug
