### ISSUE TITLE
Author field sometimes shows HTML tags

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [commons-app/apps-android-commons#5050] opened 2022-09-10 10:06 UTC
### Summary

In many image instead of Author name, Html Tags are displayed.

### Steps to reproduce

1. Open the app
2. Open some random images ( featured section )

### Expected behaviour

Show Author name

### Actual behaviour

Showing Html tags

### Device name

Samsung m21 2021

### Android version

Android 12 ( stock version )

### Commons app version

4.0.5

### Screen-shots

![Screenshot_20220910-151811_Commons](https://user-images.githubusercontent.com/91469717/189478510-574b9291-df06-4bd8-8b55-e36ec9be1377.jpg)
![Screenshot_20220910-151739_Commons](https://user-images.githubusercontent.com/91469717/189478511-77f916bf-aaf5-4d3e-a28b-8fada550d1ed.jpg)
![Screenshot_20220910-151340_Commons](https://user-images.githubusercontent.com/91469717/189478514-2dc2ef0a-a2f8-487d-8a53-95fbfd8db8b0.jpg)
![Screenshot_20220910-151313_Commons](https://user-images.githubusercontent.com/91469717/189478516-9e8d6d4d-086b-4097-b37e-7783e1aa3544.jpg)
![Screenshot_20220910-151306_Commons](https://user-images.githubusercontent.com/91469717/189478518-b598d8a6-e622-4fae-bf73-6522563484da.jpg)
![Screenshot_20220910-151256_Commons](https://user-images.githubusercontent.com/91469717/189478520-8a18e70d-54cb-4002-969e-27c77e42824b.jpg)
![Screenshot_20220910-151250_Commons](https://user-images.githubusercontent.com/91469717/189478523-ef2d42cc-d31f-4db5-bab5-8536d33ccbc4.jpg)

**Comment by nicolas-raoul** [comment] 2022-09-19 04:46
That's true, especially with customized author names.
Pull requests welcome!

**Comment by nicolas-raoul** [comment] 2022-09-19 05:15
Actually this seems to be a duplicate of #5030?

**Closed by nicolas-raoul** 2022-09-19 05:15 UTC
Labels: bug, media details
