### ISSUE TITLE
Showing not-so nearby places

### ISSUE THREAD

**Issue by nextLane** [commons-app/apps-android-commons#375] opened 2017-03-03 15:39 UTC
I am operating the app from India and the places I am shown are no where close to me.
A possible approach can be:
1.  Fixing on a radius that can be called nearby, and pick the places geographical coordinates of which lie in this circle with the location at the center.
2. If there is no such place found, we can prompt the user to be the first one to upload something from their place :)

**Comment by misaochan** [comment] 2017-03-03 15:48
Do you mean the Nearby function doesn't show you places that are nearby? Could you post a screenshot please? Thanks!

**Comment by tobias47n9e** [comment] 2017-03-03 16:50
I don't really understand how Android handles locations, but I do think that there is some caching going on somewhere. It will sometimes take a few restarts until a new location is used in the nearby lookup. I also have the suspicion that without GPS the location is just a guess within a 200 km radius. Is that maybe from the WLAN triangulation or from the internet provider?

**Comment by nextLane** [comment] 2017-03-03 19:01
![screenshot_20170303-215625 1](https://cloud.githubusercontent.com/assets/8895985/23564949/bba281a2-0071-11e7-8d80-49713849116d.png)
![screenshot_20170303-215625 2](https://cloud.githubusercontent.com/assets/8895985/23564988/e1e62328-0071-11e7-9aaf-c46004e42556.png)

**Comment by misaochan** [comment] 2017-03-03 19:04
Hmm, okay, thanks. Was your GPS turned on the first time you loaded that? If I recall correctly we haven't yet implemented a refresh option, (and we really should).

**Comment by nextLane** [comment] 2017-03-04 17:54
@misaochan I get it, no the GPS was not on, that's why it showed me this. I believe on refreshing we should not re-fetch and parse the CSV. For now I guess we can make fetching of CSV a periodic background service rather than one that triggers everytime one opens/refreshes that activity What say?

**Comment by misaochan** [comment] 2017-03-05 16:26
I honestly don't think it would be worth putting more effort into the CSV when we are planning to scrap the CSV in favour of a Wikidata query in the near future anyway, and I'm not sure how happy users would be about us periodically downloading a large file on their behalf. :) But I am open to different opinions.

**Comment by VojtechDostal** [comment] 2017-03-07 07:23
@nextLane Hello Nextlane, the screenshot you posted is exactly (exactly!) what I also sometimes get when calling the Nearby function from my phone. This happened to me some time ago and now again. I don't know what happened in between. Will try to do some research on this using Android studio.
![17149057_10210266079947048_1532124762_o](https://cloud.githubusercontent.com/assets/21329813/23646002/30afffac-030f-11e7-80ba-0ef263d59302.png)

**Comment by nextLane** [comment] 2017-03-07 15:45
@VojtechDostal Yes, it's happening here too, it seems it throws it is unable to register location and defaults out to this view. I am looking into it too and hope to fix this too while improvising over the PR that adds refresh option to the nearby view.

**Comment by misaochan** [comment] 2017-03-08 07:17
@nextLane Your PR that adds a refresh option would definitely be a huge help. :) I am happy to merge once the Gradle update has been separated into a different PR.

**Comment by nextLane** [comment] 2017-03-11 19:12
@misaochan  Updated the PR. However, the behavior for NearBy seems inconsistent at times as in it's unable to pick up any location at times, it seems there is a problem with the location listener.

**Comment by nextLane** [comment] 2017-03-15 16:03
@VojtechDostal  It seems, this appears when the mLatestLocation and curLatLon are null, thought the csv has been fetched. Can anyone please point out to what part of code is exactly helping us get the location of the user initially, at the first time, when the location has not yet been changed?

**Comment by VojtechDostal** [comment] 2017-03-15 16:34
I don't have an idea what leads to this problem but I am adding another screenshot from yesterday. It shows that somehow the app knows that I am in Prague but it nevertheless displays far-away items.
![screenshot_2017-03-14-18-05-49](https://cloud.githubusercontent.com/assets/21329813/23959446/80fc05b8-09a5-11e7-945e-40672b93d90b.png)

**Comment by misaochan** [comment] 2017-03-15 16:48
@nextLane It's been a while since I wrote it, but if I recall correctly the initial location is obtained via `Location location = locationManager.getLastKnownLocation(provider);` in NearbyActivity.java. There are several reasons that method would return null, though it would help if you could post logs.

@VojtechDostal Your issue is caused by incomplete loading of the CSV, I think. If you go to Nearby and then leave the activity, and come back later, it will display all the results that were loaded up to that point. Those results are unlikely to actually be nearby. There are a few ways to mitigate this issue, possibly including the Refresh solution (thanks for resolving the conflicts @nextLane , one of us will try and test your PR and merge ASAP!).

**Comment by misaochan** [comment] 2017-03-15 17:08
@nextLane Have you tried the suggestions at http://stackoverflow.com/questions/23906926/locationmanager-getlastknownlocation-return-null ?

**Comment by misaochan** [comment] 2017-04-20 10:27
Is this still an issue?

**Closed** 2018-05-03 16:32 UTC
Labels: nearby
