### ISSUE TITLE
Issue with collecting stats needed for IEG final report

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3078] opened 2019-07-17 10:10 UTC
After 2.11 is released (very soon), I will need to collect the final metrics of success for our last IEG. There are two metrics remaining to be collected:

- Less than 10% of images uploaded via the app are unusable (deleted)
- Overwrite incidents are reduced to <0.5% of all uploads

Normally we use https://github.com/whym/commons-app-stats for this, however, it has been broken for the last month+. I have pinged the maintainer twice on this, first at https://github.com/whym/commons-app-stats/issues/12 and then at https://github.com/whym/commons-app-stats/issues/13 , but did not get any response, so I think he might be busy.

@VojtechDostal @urbanecm @nicolas-raoul Any idea what we should do about this? If anyone is familiar with collecting stats from Commons, we could set up a new script perhaps? Or we can fork the original if preferred.

**Comment by nicolas-raoul** [comment] 2019-07-17 11:41
I see SQL requests from that line: https://github.com/whym/commons-app-stats/blob/master/local/bin/plot_batch.py#L36

Maybe it is possible to run it from the SQL web interface we used the other day? And add a `COUNT(` at the right place?

**Comment by misaochan** [comment] 2019-08-01 09:16
I think we can't rely on the current SQL query in that repo - it's not just the histogram that's broken, but the data obtained is faulty (the CSV file is wrong too). Maybe I could try to fork it and set up the dev env on tools.wmflabs.org, then revert to past commits and see if that works. But it might be a change on the server side that is causing the problem, and not necessarily a client side code change... :(

**Comment by urbanecm** [comment] 2019-08-01 09:27
I've reviewed both queries, and I don't see anything that should prevent the query from running. However, I might've overseen something :-). I'd still try to run the two queries and see if it works.

You say on whym/commons-app-stats#13 that the CSV "shows 'NoName' and 'NoTitle' for everything". That would mean the try-except structure in plot_batch.py was triggered by an exception, see https://github.com/whym/commons-app-stats/blob/master/local/bin/plot_batch.py#L145 and https://github.com/whym/commons-app-stats/blob/master/local/bin/plot_batch.py#L131. If you ran the script, could you please share the exception traceback, so we see clearly what the error is?

If you don't run the script, how do you access the data?

**Comment by misaochan** [comment] 2019-08-01 09:29
I have never run the script manually, haha... I usually access the data at https://tools.wmflabs.org/commons-app-stats/ (which also contains the links to the raw CSV). :)

**Comment by urbanecm** [comment] 2019-08-01 09:33
Well, at least I tried that ;). I've looked into logs available under `/data/project/commons-app-stats`, but it seems that logs that I'd need are readable only for tools maintainers. I'll try to email Whym and request maintainer permission, so I can look into the issue. 

Theoretically, I can either write a new script from scratch, but it's possible that the issue is a very little problem and if you have a tool that works for you, it would be a waste of time to develop another one.

**Comment by misaochan** [comment] 2019-08-01 09:38
Thank you so much for the help, @urbanecm ! Yeah, I'm quite unfamiliar with tools unfortunately... :) 

> Theoretically, I can either write a new script from scratch, but it's possible that the issue is a very little problem and if you have a tool that works for you, it would be a waste of time to develop another one.

I agree, that makes sense.

**Comment by whym** [comment] 2019-08-05 12:22
Sorry for the delay! I think what's needed is the quarterly chart. But since when? In the current state of the script, a 2018Q4-to-2019Q2 chart takes 0.5-1.0 day to produce, and it'll probably increase linearly as we take a longer period.

(I think the slowness is partly because I wrote worse code than I should, but partly due to the increased data itself - recently there are much more mobile contributions than when I first wrote it.)

I posted details in https://github.com/whym/commons-app-stats/issues/13 .

**Comment by misaochan** [comment] 2019-08-06 13:37
Hi @whym , thanks for looking into this! :) Yes, what is needed is the quarterly chart - the weekly chart is pretty cool, but I have never actually used it for stats collection. I also use the CSVs to obtain raw numbers and exact percentage (i.e. for deletions). For the time span, the ideal start would be 2015 since that is when the community-maintained app began, but if that poses a big problem, the last 2 years at least would be needed.

>  In the current state of the script, a 2018Q4-to-2019Q2 chart takes 0.5-1.0 day to produce, and it'll probably increase linearly as we take a longer period. (I think the slowness is partly because I wrote worse code than I should, but partly due to the increased data itself - recently there are much more mobile contributions than when I first wrote it.)

This is really interesting. I guess it can be termed as a "good problem to have" for us, but it is certainly still a problem. Do you know which part of the data collection causes the bottleneck?

**Comment by whym** [comment] 2019-08-07 08:08
Issues have been cleared up as far as I can see. The chart now looks like this.
![image](https://user-images.githubusercontent.com/10674/62602944-d6cef680-b92f-11e9-945d-92e8ef2f1e37.png)

> Do you know which part of the data collection causes the bottleneck?

Short answer is SQL. More on this is in: https://github.com/whym/commons-app-stats/issues/13#issuecomment-518981863

There is another thing I meant to change but forgot before. Instead of stacking up edits and uploads in one bar, it makes sense to have one bar for edits and another for uploads, right? If you like this, I can prepare the quarterly chart in the new format. If you don't, the old format works, too. Example: 
![image](https://user-images.githubusercontent.com/10674/62603012-f8c87900-b92f-11e9-9584-bb9dbfcb9cb3.png)

**Comment by misaochan** [comment] 2019-08-09 17:13
Thank you so much, @whym ! Yes, the new format looks great, it definitely makes sense to have the edits in a separate bar. :) It seems like we hit our upload peak in 2018 Q2, which is interesting. Still, it looks like deletions have decreased, so I'm not complaining, haha.

One additional question: I downloaded the CSVs to do my calculations... it looks like there are 5 types of actions in the spreadsheet instead of 4 (as in the histogram). The additional action is `5. edit (new)`, is there a reason for this?

**Comment by whym** [comment] 2019-08-10 12:17
> The additional action is 5. edit (new), is there a reason for this?

I thought it was redundant. "edit (new)" is in effect a duplicate of "upload (new)", with some rare exceptions when upload fails but page creation succeeds, perhaps. (I didn't exclude it from the CSV because it might be useful when investing upload failures etc.) If I sort the CSV by date it looks like this:

![image](https://user-images.githubusercontent.com/10674/62821664-633d1b80-bbb3-11e9-8914-fc544f2c18e5.png)

I though it was especially misleading to include it when all was stacked into one bar. But now that we have two separate bars, I'm rather indifferent whether we include it or not. What do you think?

**Comment by misaochan** [comment] 2019-08-12 12:30
> I thought it was especially misleading to include it when all was stacked into one bar. But now that we have two separate bars, I'm rather indifferent whether we include it or not. What do you think?

Ah, OK! Yeah, I think it is best to leave it out of the histogram entirely if it is a duplicate (although it may be interesting to investigate further - if a disparity is indeed an indicator of failed uploads, that would be a very good way for us to get stats on failed uploads).

**Comment by maskaravivek** [comment] 2020-01-13 01:22
Closing this issue as our final report has been submitted.

**Closed by maskaravivek** 2020-01-13 01:22 UTC
Labels: IEG
