### ISSUE TITLE
Changing orientation in SearchActivity crashes app

### ISSUE THREAD

**Issue by Szymon20000** [commons-app/apps-android-commons#2125] opened 2018-12-15 19:24 UTC
Device: SM-N910C
Android: 6.0.1

**Would you like to work on the issue?**

Yes

**Comment by maskaravivek** [comment] 2018-12-16 05:44
@Szymon20000 Feel free to take up this issue. :)

**Comment by Szymon20000** [comment] 2018-12-16 14:30
@maskaravivek I think I fix it.

**Comment by domdomegg** [comment] 2018-12-16 15:33
Ah okay managed to recreate now. I did not realise you had to type something into the search bar before. Will check #2129 fixes it for me too and merge.

Wanted to check it solved the issue - agreed would make change anyways but didn't want to close this if issue not actually closed :)

Thanks for your work on this! :+1:

**Comment by Szymon20000** [comment] 2018-12-16 15:39
Probably the issue is still present. There are other things which can force activity to recreate.
Why this activity is not just saving its state?

**Comment by domdomegg** [comment] 2018-12-16 18:16
Some more info. This is API level specific, and cannot be recreated on API level 28. It can be recreated on levels 23 and 25.

Logs on API 23:
```
12-16 18:15:11.298 4592-4592/fr.free.nrw.commons E/ACRA: ACRA caught a OnErrorNotImplementedException for fr.free.nrw.commons
    io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at fr.free.nrw.commons.utils.NetworkUtils.isInternetConnectionEstablished(NetworkUtils.java:12)
        at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList(SearchImageFragment.java:133)
        at fr.free.nrw.commons.explore.SearchActivity.lambda$setTabs$1$SearchActivity(SearchActivity.java:113)
        at fr.free.nrw.commons.explore.SearchActivity$$Lambda$1.accept(Unknown Source)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252) 
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by domdomegg** [comment] 2018-12-16 19:04
Reopening to try to deal with underlying issue

**Comment by domdomegg** [comment] 2018-12-16 19:30
More logs:

```
12-16 19:28:25.670 5037-5037/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 5037
    io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at fr.free.nrw.commons.utils.NetworkUtils.isInternetConnectionEstablished(NetworkUtils.java:12)
        at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList(SearchImageFragment.java:133)
        at fr.free.nrw.commons.explore.SearchActivity.lambda$setTabs$1$SearchActivity(SearchActivity.java:114)
        at fr.free.nrw.commons.explore.SearchActivity$$Lambda$1.accept(Unknown Source)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252) 
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

```
12-16 19:29:30.734 5105-5105/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 5105
    io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at fr.free.nrw.commons.utils.NetworkUtils.isInternetConnectionEstablished(NetworkUtils.java:12)
        at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList(SearchImageFragment.java:133)
        at fr.free.nrw.commons.explore.SearchActivity.lambda$setTabs$1$SearchActivity(SearchActivity.java:114)
        at fr.free.nrw.commons.explore.SearchActivity$$Lambda$1.accept(Unknown Source)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252) 
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

```
12-16 19:30:03.294 5273-5273/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 5273
    io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at fr.free.nrw.commons.utils.NetworkUtils.isInternetConnectionEstablished(NetworkUtils.java:12)
        at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList(SearchImageFragment.java:133)
        at fr.free.nrw.commons.explore.SearchActivity.lambda$setTabs$1$SearchActivity(SearchActivity.java:114)
        at fr.free.nrw.commons.explore.SearchActivity$$Lambda$1.accept(Unknown Source)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252) 
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by domdomegg** [comment] 2018-12-17 00:33
I refactored `SearchActivity` quite a bit but still couldn't figure out why `getContext()` returns null in the fragment methods after recreation.

In case it helps, what currently seems to happen when opening search, typing a query, then rotating:
- `SearchMediaFragment` `A` attached
- *QUERY ENTERED*
- `updateImageList` called on `SearchMediaFragment` `A`, works fine
- *ROTATION*
- `SearchMediaFragment` `B` attached
- `updateImageList` called on `SearchMediaFragment` `C`, crashes as no context

Not sure at which point `C` is created as it is never attached. No idea why it even exists.

Refactored code at https://github.com/domdomegg/apps-android-commons/commit/38067fcee74f52ed9e7a7f6279a71d5dd3785a31

**Comment by ashishkumar468** [comment] 2020-08-14 09:17
Not able to reproduce this on latest commits, closing the issue

**Closed by ashishkumar468** 2020-08-14 09:17 UTC
Labels: bug, code-quality, explore
