### ISSUE TITLE
App crashes when an upload is retried

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#1750] opened 2018-07-26 18:30 UTC
**Summary:** 

I just opened my emulator and saw that there was a failed upload. I clicked on retry button and the app crashes. 

**Add System logs:**

```
2018-07-26 23:58:32.275 3004-3004/fr.free.nrw.commons.debug D/ContributionsActivity: Restarting for fr.free.nrw.commons.contributions.Contribution@3c770c
    
    --------- beginning of system
2018-07-26 23:58:32.276 3004-3028/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: UploadService
    Process: fr.free.nrw.commons.debug, PID: 3004
    java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{c92d88d 3004:fr.free.nrw.commons.debug/u0a126} (pid=3004, uid=10126) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4199)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:5476)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2239)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1517)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1131)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:984)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:704)
        at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:196)
        at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:138)
        at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:48)
        at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:26)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```
 
 **Commons app version:** 

branch 2.8-release

**Comment by albendz** [comment] 2018-08-01 04:34
Mind if I work on this one?

**Comment by nicolas-raoul** [comment] 2018-08-01 04:43
@albendz This issue is yours, looking forward to your pull request!
If it takes time please let us know here about the situation at least every 5 days, thanks :-)

**Comment by albendz** [comment] 2018-08-05 19:06
Update: Still in progress.

Does anyone know what this comment refers to: https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/upload/UploadService.java#L133 ?

I've repro'd the bug and I'm trying to track down whether it's a permissions issue or whether the temporary files don't exist anymore.

Is there a way to delete a failed upload to retry later for the user?

**Comment by maskaravivek** [comment] 2018-08-05 20:38
It refers to an issue where the content provider returned by google photos was not working correctly. 
@misaochan might know about it.

**Comment by misaochan** [comment] 2018-08-06 08:12
There was an issue with security exceptions when users uploaded via Google Photos. Looks similar to the exception being mentioned here. Unfortunately I can't recall off the top of my head what exactly the issue was caused by.

I am actually hoping that this should have been fixed with the merging of #1749  in `2.8-release` as that modifies the flow of the upload. Could you please test `2.8-release` now and see if this still happens?

> Is there a way to delete a failed upload to retry later for the user?

Sorry, not clear what you mean by that?

**Comment by neslihanturan** [comment] 2018-08-06 11:28
@maskaravivek says it happens on 2.8-release branch:/ I can be the right person to answer your questions and help debug @albendz , since lately I had a really close relationship:)

**Comment by neslihanturan** [comment] 2018-08-06 11:48
> Is there a way to delete a failed upload to retry later for the user?
You can click cancel instead of retry.

Second think, to make sure if temp file is still there, you can check emulator file system. 
1- Open android studio emulator
2- Tools->Android->Android Device Monitor-> file explorer -> storage-> emulated-> 0-> UploadingByCommonsApp and you reached our temp cache directory.

While you upload some image, file will be under that directory. If fails, it should still be there. If you cancel failed upload attempt, it shouldn't be there anymore. If you retry, it should retry with the file in mentioned directory.

**Comment by albendz** [comment] 2018-08-08 23:31
I've done the same repo steps on 2.8 and there's no crash because there's a check to see if a file is present. Is this the fix I needed to verify?

**Comment by albendz** [comment] 2018-08-08 23:47
Repro steps that cause a crash on master but not 2.8-release:

1. Install App
2. Use App to upload a Single photo
3. Put phone in airplane mode
4. Name photo
5. Try to upload
6. Close app (really close it not just remove focus)
7. Turn off airplane mode
8. Open app
9. Click failed upload
10. Hit back either in app or via phone
2.8-release - no crash
master - crash

**Comment by albendz** [comment] 2018-08-09 22:25
@nicolas-raoul My last merge from master was July 30th. After pulling today, the crash no longer happens.

**Closed** 2018-08-10 02:43 UTC
Labels: assigned, bug
