### ISSUE TITLE
Back button goes to main page in ''neaby''

### ISSUE THREAD

**Issue by athatsakk** [commons-app/apps-android-commons#2260] opened 2019-01-01 23:06 UTC
**Summary:** 

When pressing 'back' button in ''neaby'' after pressing the button on right top, it goes straight to the main page. I should expect that it would just close that tab , and continue searching on map.

**Steps to reproduce:** 

At main page , go to ''neaby''
Press the button on right top , to show a list with places
Press back button

 
**Commons app version:** 

2.9

**Screen-shots:** 

![screenshot_5](https://user-images.githubusercontent.com/32622637/50577149-432dc880-0e2a-11e9-82c6-8eef2e515a7f.jpg)
![screenshot_4](https://user-images.githubusercontent.com/32622637/50577150-45902280-0e2a-11e9-8198-d26348956219.jpg)

**Comment by domdomegg** [comment] 2019-01-02 16:16
Is this not a duplicate of #2245?

**Comment by athatsakk** [comment] 2019-01-02 23:58
in fact is the same issue but this is version 2.9 , and that was 2.8.5

**Comment by domdomegg** [comment] 2019-01-03 00:31
Okay in that case I'm going to close this issue in favour of #2245, given it's the same issue reported for different versions - there simply has not been a fix released yet.

If you think this should stay open please do reopen/comment for me to reopen.

**Closed by domdomegg** 2019-01-03 00:31 UTC
