### ISSUE TITLE
Revamp the Settings page

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1039] opened 2018-01-01 18:58 UTC
- [ ] Categorize the items so that user is able to get what he wants quickly. Possible categories for the currently available content are *Appearance, General, Feedback*
 - [ ] Clarify why disabling "Use Wikidata" would cause huge data consumption. This could be done possibly by using a 'Learn more' link to a page that explains the reason.
 - [ ] The heading 'License' isn't clear enough. 'Default license' would possibly be better
 - [ ] Use [toggle buttons](https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons) instead of [checkboxes](https://material.io/guidelines/components/selection-controls.html#selection-controls-checkbox) as toggle buttons are more suitable for two state settings like "Night mode".

It would be nice if the [material design guidelines for Settings](https://material.io/guidelines/patterns/settings.html) was considered while doing this. I find their suggestion to be one that aims for an intuitive interface.

**Comment by misaochan** [comment] 2018-01-02 12:17
Agreed completely with the revamp, especially with using material design guidelines and categorization of items.

**Comment by afswift** [comment] 2018-01-20 23:00
If this issue isn't being worked on currently, I would love to tackle this issue. I've been working with android studio for a few months now. 

If this is needed for parsing through:

I start working on this

**Comment by misaochan** [comment] 2018-01-21 09:21
@afswift Go for it. :)

**Comment by sivaraam** [comment] 2018-01-21 16:21
@misaochan Sorry for the off-topic question. Why do you actually use the #assigned tag instead assigning the task to the concerned person?

**Comment by misaochan** [comment] 2018-01-21 17:36
@sivaraam Because GitHub doesn't allow us to assign tasks to someone who hasn't yet contributed to the repo I believe. The option just isn't available.

**Comment by madhurgupta10** [comment] 2018-03-03 16:25
Hi, if the issue is still not resolved, may I please work on it?

**Comment by misaochan** [comment] 2018-03-03 17:47
@madhurgupta10 I think you can go for it, as @afswift hasn't been around for a couple months now. :)

**Comment by madhurgupta10** [comment] 2018-03-03 17:49
@misaochan on it

**Comment by madhurgupta10** [comment] 2018-03-04 16:29
@sivaraam Hi, could you please provide me the link for "Learn More" to "Use Wikidata" would cause huge data consumption

**Comment by misaochan** [comment] 2018-03-04 17:28
Actually, I think "use Wikidata" can be removed entirely. We have migrated completely to Wikidata and do not even use the CSV anymore.(see #981 ).

**Comment by misaochan** [comment] 2018-03-04 17:31
I noticed that you are missing "become a beta tester" and "send log file" - are they present but just not in your screenshot?

**Comment by madhurgupta10** [comment] 2018-03-04 18:28
@misaochan It is present, but not in the screenshot

**Comment by madhurgupta10** [comment] 2018-03-04 18:35
@misaochan Is there any code apart from the one in **preference.xml** which is related to "use Wikidata", that should be removed?

**Comment by nicolas-raoul** [comment] 2018-03-05 04:00
@madhurgupta10 I guess all CSV code has been removed, but f you find any such code please remove it, thanks :-)

**Comment by madhurgupta10** [comment] 2018-03-05 04:08
@nicolas-raoul I made the necessary changes but one of the tests is failing, could you please help me debug!

**Comment by maskaravivek** [comment] 2018-03-10 19:27
@madhurgupta10's PR fixes all the issues listed in @sivaraam's opening comment. Closing this issue. Thanks everyone for participating in the discussion and helping us improve our UI. :)

**Closed by maskaravivek** 2018-03-10 19:27 UTC
Labels: UX - user experience, assigned, beginner friendly, enhancement
