### ISSUE TITLE
Nearby not working as intended

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5461] opened 2024-01-21 08:19 UTC
### Summary

Nearby used to display pins on the map. They are no longer visible. So, I can't initiate any uploads from Nearby. Moreover, the following features are also not working:

- Search this area button
- The list button at the top right corner

Moreover, the app often crashes or stops responding while trying the above features. 

### Steps to reproduce

1. Open the app and switch to Nearby tab
2. Wait for the pins to load or navigate to other areas to search for them using "Search this area" button
3. Tap the list icon at the top right corner

### Expected behaviour

The nearby pins should load, "Search this area" should load pins on other areas on Earth and tapping the list icon should show a list of nearby places.

### Actual behaviour

Nearby pins do not load, nor do the "Search this area" button or the list icon work.

### Device name

Redmi 5A

### Android version

8.1.0

### Commons app version

main and prodDebug

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment] 2024-01-21 09:20
Interesting, this is working fine on my Android 14 device.
Anyone who wants to work on this, please first make sure you can reproduce, using an emulator if needed.

**Comment by RitikaPahwa4444** [comment] 2024-01-21 09:23
https://github.com/commons-app/apps-android-commons/assets/83745993/51052c04-b51c-4cd1-a387-a5920b03c6ed

This has been partly fixed by PR[#5418 ](https://github.com/commons-app/apps-android-commons/pull/5418#issue-2064061764), I'll just highlight the differences with the app available on Play Store.

**Comment by ShashwatKedia** [comment] 2024-01-21 09:44
@RitikaPahwa4444 the problem here is that the app is asking for location permission but does not ask to turn on the location services (which it should do directly after permission is given, if they are off). I reported this in another issue as well, https://github.com/commons-app/apps-android-commons/issues/5255#issuecomment-1884209590. Does this happen even when the location services are on?

**Comment by RitikaPahwa4444** [comment] 2024-01-21 09:48
This is a bit different from the one highlighted in that comment. I'll share for all the cases I can think of.

**Comment by ShashwatKedia** [comment] 2024-01-21 10:02
> This issue is a bit different from the one highlighted in that comment. 

I think you are right, it's not dependant on whether the location services are on/off, because for my device it's working irrespective of the state of location services. I'll try to reproduce this on some other device / emulator

**Comment by RitikaPahwa4444** [comment] 2024-01-21 13:57
Differences:

| Case | App on Play Store (Oct 2023 version) | main branch | PR#5418 |
| ---- | ---- | --- | --- |
App does not have location access + location (GPS) turned off | Pins visible. Search this area button and list icon are working. No crash on target icon. [Screencast](https://drive.google.com/file/d/12bgKHUKiMHS64NMeuUtQudw0bONRgq2-/view?usp=sharing) | Pins not visible. Search this area button and list icon are not working. No crash on target icon. [Screencast](https://drive.google.com/file/d/135GGDnGMqLHDI5Pd2d7brcRSpvvJaN1-/view?usp=sharing) | Pins not visible. Search this area button and list icon are not working. No crash on target icon. [Screencast](https://drive.google.com/file/d/12caIEFWE76UgFBBno5K32JHvaDhg0vq_/view?usp=drive_link) |
App has location access + location (GPS) turned off | Pins visible. Search this area button and list icon are working. No crash on target icon.  [Screencast](https://drive.google.com/file/d/12eDEnqoAtRGkFL7Tf5504_Iij2xxD-8J/view?usp=sharing) | Pins not visible. Search this area button and list icon are not working. Crash on target icon. [Screencast](https://drive.google.com/file/d/1327SiJoiQQKuLegw_-aUmvEuRf4Tkx7s/view?usp=sharing) | Pins not visible. Search this area button and list icon are not working. No crash on target icon. Pins appear after using the target icon. [Screencast](https://drive.google.com/file/d/12hUr_itaEhKZbCNjAJhoCX16GCmeCT5T/view?usp=sharing) |

There might be a few more, I'll share if I find them.

**Comment by ShashwatKedia** [comment] 2024-01-27 07:35
@RitikaPahwa4444 After a lot of digging, I found that in the cases you mentioned, the onclicklistener for SearchThisArea button was not being set, so no operations were being performed. I'll fix this and send a PR soon, to resolve this.

**Comment by sivaraam** [comment] 2024-01-28 09:01
> @RitikaPahwa4444 After a lot of digging, I found that in the cases you mentioned, the onclicklistener for SearchThisArea button was not being set, so no operations were being performed. I'll fix this and send a PR soon, to resolve this.

Great. Thanks for taking the time to figure this out, @ShashwatKedia 🙂

**Comment by ShashwatKedia** [comment] 2024-01-29 13:47
@RitikaPahwa4444 could you confirm that the above PR works on your device as well, since you were the one who found this issue out ;)

**Comment by RitikaPahwa4444** [comment] 2024-02-03 09:19
Hi @ShashwatKedia, thanks for the PR. I'm testing that branch, working great so far :)

**Comment by nicolas-raoul** [comment] 2024-03-30 14:41
@RitikaPahwa4444 As the original reporter, do you think the PR is worth merging? :-)

**Comment by RitikaPahwa4444** [comment] 2024-03-30 14:55
I'd tested that branch over a month ago and approved too, since it fixed this issue back then (I can test again if required) and we agreed on opening a separate ticket for a minor popup related issue (#5549).

**Comment by sivaraam** [comment] 2024-03-30 15:06
> @RitikaPahwa4444 As the original reporter, do you think the PR is worth merging? :-)

I could understand the PR has been long standing. If you're asking this since you plan on merging this, could you wait for the last two comments to be resolved? We could take the rest as fixes on top, as needed

**Comment by sivaraam** [comment] 2024-04-28 06:33
Closing this as #5494 has been merged.

Feel free to reopen if I missed something that's left to be done. 🙂

**Closed by sivaraam** 2024-04-28 06:33 UTC
Labels: bug, nearby
