### ISSUE TITLE
"No categories found" message inconsistancy?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2236] opened 2018-12-27 06:45 UTC
I got this message displayed even though there were some results.
There is no exact match but the app successfully found similar categories, so I think it should not have shown that message.
Adding then removing a space makes that message disappear.
![screenshot_20181227-115924](https://user-images.githubusercontent.com/99590/50469066-c8385e00-09a2-11e9-9f96-27f42cbdaff3.png)
![screenshot_20181227-115941](https://user-images.githubusercontent.com/99590/50469112-f453df00-09a2-11e9-89bd-503027f4fcd4.png)

**Comment by ShridharGoel** [comment] 2018-12-27 07:02
May I work on this?

**Comment by ShridharGoel** [comment] 2018-12-27 07:55
Not able to reproduce the issue. Can you provide some more details like the app version?

**Comment by albendz** [comment] 2019-01-20 21:02
@ShridharGoel Are you still working on this?

**Comment by nicolas-raoul** [comment] 2019-02-05 10:43
@albendz Do you want to give it a try? First thing would be to manage to reproduce the issue, which is not easy.

**Comment by ashishkumar468** [comment] 2020-08-14 09:19
Could not reproduce this on the latest commits, closing this issue for now. Feel free to re-open if someone manages to reproduce this :)

**Closed by ashishkumar468** 2020-08-14 09:19 UTC
Labels: bug, categorization
