### ISSUE TITLE
Location template has not been added

### ISSUE THREAD

**Issue by Aschroet** [commons-app/apps-android-commons#534] opened 2017-04-25 06:00 UTC
Although a foto that i uploaded with the app contained the GPS position the location template has not been added:

https://commons.wikimedia.org/w/index.php?title=File:Klo%C3%9Fpommes_-_1.jpg&oldid=241916033

**Comment by whym** [comment] 2017-06-10 00:59
Which version of Android were you using? How did you select the picture to upload? (Did you use the in-app camera button or the gallery button?)

I was able to reproduce the issue when using API 23 emulator and sharing from the gallery.

**Comment by Aschroet** [comment] 2017-06-10 06:10
I am using Android 6.0.1. I definitely did not use the camera button. But I am not sure if used the gallery button or if I selected files from the gallery and selected share it with Commons app.

PS: The described issue happened again with my last uploads: https://commons.wikimedia.org/wiki/File:Memorial_near_Hallerangeralm_-_3.jpg

**Comment by whym** [comment] 2017-06-11 06:43
Good, Android 6.0 is API 23, so I'm pretty sure it's this issue which I believe specific to that version of Android.

I'm working on it as part of #727.

**Comment by whym** [comment] 2017-07-22 01:34
#727 should have solved it. At least it did for me. e.g. https://commons.wikimedia.org/wiki/File:CommonsAppTesting_9.jpg (note that since this is a test upload it will eventually be deleted)

It's not released in the Play Store, though. Please keep an eye on the coming releases of the app, and feel free to re-open this if the problem persists after then.

**Closed by whym** 2017-07-22 01:34 UTC
Labels: bug, metadata
