### ISSUE TITLE
When uploading several files at once the date is missing

### ISSUE THREAD

**Issue by Yannf** [commons-app/apps-android-commons#1854] opened 2018-08-24 16:05 UTC
When uploading several files at once the date is missing. 

Also sometimes wrong.
The App added the upload date, instead of the date " according to Exif data".
https://commons.wikimedia.org/w/index.php?title=File:View_of_Leh_from_Tsemo_castle,_Ladakh.jpg&oldid=315035923
https://commons.wikimedia.org/w/index.php?title=File:View_of_Leh_from_Tsemo_castle,_Ladakh_,_2.jpg&oldid=315036119

**Device and Android version:** 

Samsung J510FM
Android 7.1.1
 
 **Commons app version:** 

2.8.1

**Would you like to work on the issue?**

No.

**Comment by whym** [comment] 2018-08-26 13:02
Just checking, did it happen only when you uploaded multiple files at once? If so we should probably include that into the issue title.

For the "View_of_Leh_from_Tsemo_castle,_Ladakh" set, both [File 1](https://commons.wikimedia.org/w/index.php?title=File:View_of_Leh_from_Tsemo_castle,_Ladakh.jpg&oldid=315035923) and [File 2](https://commons.wikimedia.org/w/index.php?title=File:View_of_Leh_from_Tsemo_castle,_Ladakh_,_2.jpg&oldid=315036119) seemed to have the dates wrong (upload dates instead of EXIF dates), indeed.

**Comment by Aschroet** [comment] 2018-09-18 06:05
I can confirm that for all my uploads the date is missing. This happens for single uploads such as https://commons.wikimedia.org/wiki/File:Grab_Hackpf%C3%BCffel.jpg and batch uploads https://commons.wikimedia.org/wiki/File:Kirche_Hackpf%C3%BCffel_-_1.jpg.

**Comment by misaochan** [comment] 2018-09-18 07:51
@neslihanturan Do you think this could have been caused by our recent upload change at #1720 ?

**Comment by neslihanturan** [comment] 2018-09-19 05:19
Maybe @misaochan , I will try to check this on Monday.

**Comment by misaochan** [comment] 2018-11-01 09:33
Just talked to @ashishkumar468 about the potential cause of this bug. It seems that the temp file URI changes made at #1749 to fix a different bug, may have caused this.

It isn't limited to just date, but much of the Exif metadata would have been omitted as well, unfortunately. For instance, see the difference between https://commons.wikimedia.org/wiki/File:Miss_Claudes_creperie_in_Brisbane.jpg and https://commons.wikimedia.org/wiki/File:Nepalese_pagoda_in_south_bank_Brisbane.jpeg

Fortunately, this should be fixed soon. :) Thanks for your patience everyone.

**Comment by misaochan** [comment] 2018-11-27 16:59
Hi @Yannf , we just released this bugfix with v2.9 in beta. Could you please let us know if the problem is solved for you?

**Comment by domdomegg** [comment] 2018-12-21 01:07
Fixed in https://github.com/maskaravivek/apps-android-commons/pull/1 and #1968

**Closed by domdomegg** 2018-12-21 01:07 UTC
Labels: bug, high priority
