### ISSUE TITLE
Some fields are missing on activity_login layout

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1919] opened 2018-10-09 15:10 UTC
**Summary:** 

Some fields are missing on activity_login.xml landscape and lanscape large versions. They are only added to portrait mode xml file. Thus, it gives NPE when you try to run app on landscape mode.

**Steps to reproduce:** 

Run the app on landscape mode. Ie, "skipLogin" field is missing. I think there may be some other missing fields too, needs to be checked.

**Comment by neslihanturan** [comment] 2018-10-09 15:11
This issue is quite beginner friendly, if someone interests:)

**Comment by spelka** [comment] 2018-10-10 02:51
Hi, I'm new to the project and would like to take a look. I wanted to make some open source contributions for Hacktoberfest but my skills are really rusty. Hoping to refresh my Java skills.

I am able to reproduce the issue with the released version in the google play store on my phone.

I'm unable to reproduce this issue with the android emulator; the "skip" field seems to be showing up correctly. Additionally, I had a look at the layout files and they all contain the correct HtmlTextView "skipLogin" element. 

Is there a more reliable way that the android commons team uses to reproduce issues? I don't know how reliable the emulators can be.

**Comment by neslihanturan** [comment] 2018-10-10 07:29
Hi @spelka , welcome:) You need to make a first time run when layout is landscape to reprocude this issue. And there are 3 activity_login.xml files, if you open the cıde on android studio, you will see. Only one of them includes skipLogin currently. So I think on every API and devices it should crash. 

Which branch did you checked and said all layout files conrain correct skipLogin element?

**Comment by spelka** [comment] 2018-10-10 15:53
Hi @neslihanturan 

I think maybe I am looking at the wrong files. Just to be 100% sure, can you confirm these files are the ones we want to investigate:

https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/res/layout-land/activity_login.xml
https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/res/layout-xlarge/activity_login.xml

I checked the commit history for these files and it looks like the elements you requested were added to these files in this commit:
https://github.com/commons-app/apps-android-commons/commit/92a8b5e37cc97c05087326b47413f604c6badf61

I must be misunderstanding something... can you clarify for me?

**Comment by misaochan** [comment] 2018-10-10 16:03
I think this would be already fixed in master. The bugfix just hasn't made its way to a release yet, hence the buggy Play Store version. It should be out in v2.9 soon hopefully.

**Comment by spelka** [comment] 2018-10-10 16:06
@misaochan So this issue has no work to be done, is that correct?

**Comment by misaochan** [comment] 2018-10-10 16:20
Perhaps @ashishkumar468 who wrote that commit can confirm, but that is my understanding.

**Comment by neslihanturan** [comment] 2018-10-10 16:44
Yes, my bad. I am sorry @spelka , my master wasn't up to date and apparently I missed this fix. Sorry for making you busy. If you have questions about another beginner friendly task, please don't hesitate to ask.

**Closed** 2018-10-10 19:31 UTC
Labels: beginner friendly, bug
