### ISSUE TITLE
During upload, searching for "Fruit shops in Japan" does not show existing category

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3582] opened 2020-03-25 00:44 UTC
Steps to reproduce:
1. Run the latest master
2. Start uploading any image (you can abort afterwards)
3. When the category search activity appears, type "Fruit shops in "
4. The choices below appear, among them you can see [Fruit shops in Japan](https://commons.wikimedia.org/wiki/Category:Fruit_shops_in_Japan):

![Screenshot_20200325-093526_Commons](https://user-images.githubusercontent.com/99590/77489706-49b7be00-6e7c-11ea-8475-5dc1566645cf.jpg)

5. Now complete the name by typing "Japan".
6. Expected: "Fruit shops in Japan" choice stays. Actually: "No Categories found"

![Screenshot_20200325-093544_Commons](https://user-images.githubusercontent.com/99590/77489878-b92dad80-6e7c-11ea-8e44-8456ed4da0e9.jpg)

Possibly related issue: #3179

**Comment by 318anushka** [comment] 2020-03-25 09:47
I am able to reproduce this issue 
when i searched for flowers in... and type any name that appears in the suggestions below, it shows no categories found.
![Screenshot_20200325-150319](https://user-images.githubusercontent.com/45694892/77523076-35d78080-6eab-11ea-8257-4f89c17a8200.jpg)
![Screenshot_20200325-150340](https://user-images.githubusercontent.com/45694892/77523080-36701700-6eab-11ea-91ea-2a481b0940fb.jpg)

while if i type something other than the choices below it worked just fine 
like this:
![Screenshot_20200325-150411](https://user-images.githubusercontent.com/45694892/77523239-746d3b00-6eab-11ea-9661-925d0b819757.jpg)

I'll look at the code how values are stored and displayed once received and start working on it!!

**Comment by nicolas-raoul** [comment] 2020-03-25 09:56
Thanks!
First I suggest looking at the HTTP search request in `adb logcat`, to see whether the request has a problem or not.

**Comment by sivaraam** [comment] 2020-03-28 16:11
I believe this issue is due to the fix for #3179. See https://github.com/commons-app/apps-android-commons/issues/3179#issuecomment-605466529

@318anushka Apologies, in my free flow of exploration which started at #3585, I ended up finding the cause of this issue without intending to 😅

FYI: Bhardwaj has mentioned that he'll look into the issue mentioned at #3179.

**Comment by 318anushka** [comment] 2020-03-28 17:00
oh okay, I just started looking into the issue so no problem.
Incase, no one is working i'll get back to it :-)

**Comment by sivaraam** [comment] 2020-03-28 17:33
@318anushka Sure. You can keep a watch of #3179. In the meanwhile, feel free to look at other tasks :)

I'm closing this in favour of #3179.

**Closed by sivaraam** 2020-03-28 17:33 UTC
Labels: assigned, bug, categorization
