### ISSUE TITLE
Crash on clicking back from a failed media detail page

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#966] opened 2017-11-17 18:57 UTC
I tried uploading an image which failed because of some reason. From the media detail view when i click the back arrow in the toolbar, the app crashes. 

```
FATAL EXCEPTION: UploadService
Process: fr.free.nrw.commons, PID: 3801
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{2507df2 3801:fr.free.nrw.commons/u0a88} (pid=3801, uid=10088) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
at android.os.Parcel.readException(Parcel.java:1599)
at android.os.Parcel.readException(Parcel.java:1552)
at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1088)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:191)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:130)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:38)
at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:25)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
11-18 00:26:03.589 3801-3851/fr.free.nrw.commons E/Surface: getSlotFromBufferLocked: unknown buffer: 0xe02a27e0```

**Comment by tanvidadu** [comment] 2018-02-07 06:21
I am unable to replicate the error. Please help with this so I can go ahead with fixing it. Thanks :)

**Comment by maskaravivek** [comment] 2018-02-07 08:50
Must be happening when the required permissions are not provided.

**Comment by Mansi449** [comment] 2018-03-22 12:02
@maskaravivek I too am not able to replicate the error. I removed all the granted permissions and tried again but still clicking the back button works perfectly fine

**Comment by ashishkumar468** [comment] 2020-08-17 10:31
As the issue is very old and we have had major refactors post this. I am not able to reproduce this in the latest commits, closing this issue

**Closed by ashishkumar468** 2020-08-17 10:31 UTC
Labels: bug
