### ISSUE TITLE
Add remove button for media descriptions on upload page

### ISSUE THREAD

**Issue by AntSYau** [commons-app/apps-android-commons#3565] opened 2020-03-22 07:59 UTC
**Summary:** 

When I upload a media, I can choose to write media description in different languages, however, it is impossible to delete languages. I feel there should be a remove button for unwanted ones.

**Steps to reproduce:** 

- Log in
- Click + button and choose a photo
- Add media description in two languages (reference #3561)
- Try to remove one language

**System logs:**

N/A

**Device and Android version:** 

OnePlus 5, Android 9.0
 
**Commons app version:** 

structured-data branch on prodDebug variant

**Screen-shots:** 

![Screenshot_20200322-154833](https://user-images.githubusercontent.com/10476297/77244903-54dcd500-6c55-11ea-879a-528e9917ab14.jpg)

**Would you like to work on the issue?**

No

**Comment by chao19991005** [comment] 2020-03-22 08:05
May I try to work on this issue？

**Comment by sivaraam** [comment] 2020-03-22 14:55
This is a duplicate of #2810 which itself is being fixed in PR #3504. So, closing this :)

**Closed by sivaraam** 2020-03-22 14:55 UTC
