### ISSUE TITLE
Tutorial display unicode error in french

### ISSUE THREAD

**Issue by PetitPotiron** [commons-app/apps-android-commons#5821] opened 2024-09-07 15:31 UTC
### Summary

When displaying the tutorial in the french version of the app, the bullet lists don't show well : `•&#32;` instead of `• ` is shown.

See the screenshots for more information.

### Steps to reproduce

1. Change the app user interface language to french in the settings
2. Quit the settings and open the tutorial
3. Slide right and observe

### Expected behaviour

Only a bullet is shown : `• `

### Actual behaviour

A bullet and some other caracters are shown : `• &#32;`

### Device name

Samsung A40

### Android version

Android 11

### Commons app version

4.2.1

### Screen-shots

![Screenshot_20240907-172204_Commons](https://github.com/user-attachments/assets/2ca277db-b75c-4eb9-94fe-2be928f247a4)
![Screenshot_20240907-172536_Commons](https://github.com/user-attachments/assets/e61de4e2-5ae0-4183-bc51-eecc6f8d1610)

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment] 2024-09-08 00:12
Could anyone please check whether the problem comes from the French localization on TranslateWiki?

**Comment by rohit9625** [comment] 2024-09-09 05:54
The issue is not from TranslateWiki but in the localization file for bullet points. Linking a PR :)

**Comment by nicolas-raoul** [comment] 2024-09-09 08:26
Very strangely I can't find `bullet` in TranslateWiki:

<img width="374" alt="Screenshot 2024-09-09 at 17 22 05" src="https://github.com/user-attachments/assets/e6530625-0cc5-4964-ae88-97a3cfce1b31">

... despite the source XML file (English) being:
```
  <string name="preference_category_feedback">Feedback</string>
  <string name="preference_category_privacy">Privacy</string>
  <string name="app_name">Commons</string>
  <string name="bullet">&#8226;</string>
  <string name="menu_settings">Settings</string>
  <string name="intent_share_upload_label">Upload to Commons</string>
  <string name="upload_in_progress">Upload in progress</string>
```

It does not seem to be an ordering issue, I don't find this bullet anywhere in the TranslateWiki list. If anyone finds it please let us know. :-)
It seems to have been localized to various forms:
```
$ grep -R bullet app/src/main/res/values*
app/src/main/res/values/strings.xml:  <string name="bullet">&#8226;</string>
app/src/main/res/values-ar/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-as/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ast/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-b+roa+tara/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-b+sr+Latn/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ba/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ban/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-bg/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-bn/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-br/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-cs/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-cy/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-da/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-de/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-diq/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-el/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-eo/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-es/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-eu/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-fa/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-fi/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-fr/strings.xml:  <string name="bullet">•&#32;</string>
app/src/main/res/values-gl/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-hi/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-hr/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-hu/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-in/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-is/strings.xml:  <string name="bullet">•  \\</string>
app/src/main/res/values-it/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-iw/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ja/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ji/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-jv/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ka/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ko/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ko-rKP/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ku/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-kum/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-lb/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-li/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-lt/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-lv/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-mk/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-mni/strings.xml:  <string name="bullet">꯫</string>
app/src/main/res/values-mnw/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-mr/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-my/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-nb/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ne/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-nl/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-pl/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-pms/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ps/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-pt/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-pt-rBR/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ro/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ru/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-sd/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-sk/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-skr/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-sl/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-sr/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-su/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-sv/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ta/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-tcy/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-te/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-th/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-tr/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-ug/strings.xml:  <string name="bullet">.</string>
app/src/main/res/values-uk/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-vi/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-zgh/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-zh/strings.xml:  <string name="bullet">•</string>
app/src/main/res/values-zh-rTW/strings.xml:  <string name="bullet">•</string>
```

**Comment by rohit9625** [comment] 2024-09-09 08:47
I found this bullet resource marked as optional on the Gerrit:
![image](https://github.com/user-attachments/assets/87c53e55-4fdf-4083-9a9d-9a7553dd901a)

**Comment by nicolas-raoul** [comment] 2024-09-09 08:53
Very interesting!
I am honestly not sure what it means or why it was added there... does Gerrit history say something about that line?

**Comment by rohit9625** [comment] 2024-09-09 09:00
This is the PR that added that bullet resource as optional and said it's not an English-specific resource because bullet points are the same in every language. 

https://gerrit.wikimedia.org/r/c/translatewiki/+/491958

**Comment by rohit9625** [comment] 2024-09-09 15:10
Should I remove all bullet string resources and hard code them where they are needed?

**Comment by nicolas-raoul** [comment] 2024-09-10 01:07
@rohit9625 Yes 🙂

**Comment by rohit9625** [comment] 2024-09-10 05:18
Done Mr. @nicolas-raoul

**Closed** 2024-09-10 08:41 UTC
Labels: bug
