### ISSUE TITLE
Replace static summary in custom author name with actual value

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3536] opened 2020-03-17 13:14 UTC
**Summary:** 

Continuing the discussion from [thread](https://github.com/commons-app/apps-android-commons/pull/3521#issuecomment-600058029)

Currently, a static summary is set which is somewhat repetition of the above switchpref

![76859067-db11a980-6858-11ea-9898-1b8e9bf5d382](https://user-images.githubusercontent.com/30932899/76859363-79057400-6859-11ea-9e54-576459aec7ed.png)

According to me, it would be better to show **Not Set** or the actual value.
![Screenshot_1584450599](https://user-images.githubusercontent.com/30932899/76859387-87ec2680-6859-11ea-9f78-fb8a1190ab99.png)

![Screenshot_1584450593](https://user-images.githubusercontent.com/30932899/76859383-86226300-6859-11ea-82a4-324d41081c44.png)

**Would you like to work on the issue?**
Yes, I already have a PR for this

**Comment by madhurgupta10** [comment] 2020-03-17 13:15
Pinging @misaochan @macgills for inputs.

**Comment by macgills** [comment] 2020-03-17 13:24
I am in favour of it and androidx supports the functionality well

**Comment by madhurgupta10** [comment] 2020-03-17 13:43
I have linked my PR and we can Merge/Close as per the discussion. :)

**Comment by sivaraam** [comment] 2020-03-17 14:40
Just wondering, isn't this a duplicate of #3415 in a way? :thinking:

**Comment by macgills** [comment] 2020-03-17 14:55
Absolutely but after skimming and scrolling to the end what did that ticket end up being about?

**Comment by sivaraam** [comment] 2020-03-17 15:16
I'm not sure the issue ever reached a consensus. If memory serves, the consensus was forming around keeping the two options as it is and just fixing the summary issue. But then the discussion stopped.

In case it's not clear, I pointed to that issue just to ensure you close that too when the PR #3537 gets merged. Nothing else 🙂

**Comment by macgills** [comment] 2020-03-17 15:29
superb.

**Comment by macgills** [comment] 2020-03-18 10:14
@misaochan with your approval of this feature I will merge the linked PR

**Comment by misaochan** [comment] 2020-03-18 16:03
Looks good to me, thanks @madhurgupta10 and @macgills . :)

**Closed** 2020-03-19 08:39 UTC
