### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [commons-app/apps-android-commons#4163] opened 2021-01-12 14:13 UTC
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by madhurgupta10** [comment] 2021-01-16 17:05
@mondlicht-und-sterne Closing this issue as it is a duplicate of https://github.com/commons-app/apps-android-commons/issues/4150

Feel free to discuss it on https://github.com/commons-app/apps-android-commons/issues/4150

**Closed by madhurgupta10** 2021-01-16 17:05 UTC
