### ISSUE TITLE
Problem with installing app on old android(6.0.1)

### ISSUE THREAD

**Issue by Szymon20000** [commons-app/apps-android-commons#2093] opened 2018-12-09 08:42 UTC
**Summary:** 

Recently I tried to install app on my phone. However, I came across the following error: 
```Error:FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:transformClassesWithInstantRunForBetaDebug'. > com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for com/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 2s```

device : SM-N910C
Android: 6.0.1

The problem can be related with https://github.com/mapbox/mapbox-navigation-android/issues/512.

I solved the issue locally by adding 'implementation "com.mapzen.android:lost:3.0.2' line in build.gradle.

**Comment by domdomegg** [comment] 2018-12-16 14:54
Duplicate of #1941

**Closed by domdomegg** 2018-12-16 14:54 UTC
