### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4849] opened 2022-02-24 07:56 UTC
Per https://github.com/github/renaming

Context: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by Rishavgupta12345** [comment] 2022-02-25 13:58
i would like to work on this please assign me

**Comment by nicolas-raoul** [comment] 2022-02-25 14:01
I am pretty sure admin rights are needed for this.

**Comment by Rishavgupta12345** [comment] 2022-02-25 14:05
> I am pretty sure admin rights are needed for this.

then I think you should solve this issue yourself 🥲

**Comment by nicolas-raoul** [comment] 2022-02-25 14:07
Such a big change must be discussed before. You can see that this issue is not marked as bug nor enhancement. It is in discussion phase :-)

**Comment by nicolas-raoul** [comment] 2023-09-13 09:10
Now is a good time for this, due to seasonal low contribution activity.
@sivaraam OK for me to do it?

**Comment by sivaraam** [comment] 2023-09-13 16:56
Sure, Nicolas.

Just to think out loud, what are the places that could be affected by the rename and need correction?

Do our GitHub pipelines need to be adjusted ? I suppose TranslateWiki bot might need some tweak. Who to contact regarding this?

Are there other things that we need to consider that I'm missing?

**Comment by nicolas-raoul** [comment] 2023-09-14 00:45
For TranslateWiki we can send a patch, but actually it might work without, as there is supposed to be a sort of redirect.

**Comment by sivaraam** [comment] 2023-09-14 04:13
> For TranslateWiki we can send a patch, but actually it might work without, as there is supposed to be a sort of redirect.

I was thinking the redirection works for the UI only. If it works for Git push too, that's great 🙂

**Comment by nicolas-raoul** [comment] 2023-09-14 05:26
Actually there is no branch name referenced at https://gerrit.wikimedia.org/r/plugins/gitiles/translatewiki/+/refs/heads/master/groups/Wikimedia/CommonsAndroid.yaml I guess TranslateWiki takes the default branch.

**Comment by nicolas-raoul** [comment] 2023-09-14 07:51
Pinned and keeping this open for a while in case there are unforeseen problems.

**Comment by Nikerabbit** [comment] 2023-09-14 09:44
Caused https://phabricator.wikimedia.org/T346314. We default to `master`. To my knowledge git doesn't really have a concept of "default branch" that we could easily use.

**Comment by whym** [comment] 2023-09-14 11:41
@Nikerabbit Apologies for not informing earlier. What would have been the correct way to do it? Coordinating the timing and making the two changes (here and TWN) more or less at the same time?

**Comment by nicolas-raoul** [comment] 2023-09-15 07:03
Very sorry for thinking there would be no issue!
We currently do not have a particularly pressing need for the latest localizations, and several contributors have cloned our GitHub since the switch, so unless the errors are penalizing for the TranslateWiki team, I suggest we let the branch like this and wait for repoconfig.yaml to be amended. Thanks a lot and apologies for the trouble!

**Comment by Nikerabbit** [comment] 2023-09-15 07:46
There is no urgency on this (apart from us admins getting error reports on every sync). We do appreciate heads ups to avoid the need to investigate what was the cause.

**Comment by whym** [comment] 2023-09-15 09:25
It sounds like we are in no hurry, but I submitted this anyway: https://gerrit.wikimedia.org/r/c/translatewiki/+/957841/

**Comment by nicolas-raoul** [comment] 2023-09-17 06:55
[TranslateWiki] Thanks a lot Whym for fixing and Nikerabbit for merging! :-)

**Comment by nicolas-raoul** [comment] 2023-09-26 07:22
We used to receive TranslateWiki commits every 3~4 days with great regularity, but the last one was on August 31, a few days before I renamed "master" to "main". I wonder whether some piece of the puzzle is missing. 🤔
https://github.com/commons-app/apps-android-commons/commits/main

**Comment by Nikerabbit** [comment] 2023-09-26 08:24
We are investigating this.

**Comment by Nikerabbit** [comment] 2023-09-26 14:25
This project is stuck in a "manual import review" state (even though there are no changes to import). To protect data integrity, translation updates are skipped for projects which are not fully synchronized. This is hopefully fixed by next automatic update on Thursday. We are still trying to understand the root cause.

**Comment by Nikerabbit** [comment] 2023-09-28 11:59
Things are flowing again: 8d604a25fa356974ac16b12cfcfb21d50a24ef5b

**Comment by sivaraam** [comment] 2023-11-23 17:42
Given that we're past some time after the rename. Can we close this one ?

**Closed** 2023-11-23 21:57 UTC
Labels: discussion
