### ISSUE TITLE
[Bug]: Tap to view your upload, has not worked for me for a long time 

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5779] opened 2024-07-25 12:11 UTC
### Summary

Tap to view your upload, has not worked for me for a long time 

### Steps to reproduce

every time

### Expected behaviour

not worked

### Actual behaviour

See my upload 

### Device name

Google Pixel 7 pro

### Android version

Android 14

### Commons app version

5.0.2~05ffd123e

### Screen-shots

https://commons.wikimedia.org/wiki/File:20240725_xl_1353-Commons_App,_Screenshot,_Tippe,_um_Dein_Upload_anzusehen.png

### Would you like to work on the issue?

None

**Comment by mnalis** [comment] 2024-08-17 20:05
It's hard to say without proper "steps to reproduce" and "expected behaviour", but I think it is a duplicate of https://github.com/commons-app/apps-android-commons/issues/5083 ?

can you confirm @OpenGreenStreet ?

**Comment by OpenGreenStreet** [comment] 2024-08-18 12:10
@mnalis 
Yes, I also think this is a duplicate.

I tap on the Commons app message in the push notifications. No matter how I press, nothing happens. The strange thing is that it does work in very rare cases. But I have no idea under what circumstances it works and when it doesn't.

**Comment by nicolas-raoul** [comment] 2024-08-18 12:44
> The strange thing is that it does work in very rare cases.

Interesting, would you mind adding this to the existing issue report linked by mnalis? Thanks! :-)

**Closed by nicolas-raoul** 2024-08-18 12:44 UTC
Labels: bug
