### ISSUE TITLE
Issue with underscore being inserted into username

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1901] opened 2018-09-18 05:55 UTC
From a user on our google groups forum on 13 Sep:

> Hi,
> 
> thanks for your great app.
> 
> Since some days, the app doesn't add, the date of the picture into the template. Is this my fault (wrong settings) or is this a problem with the app?
> 
> And the app puts an underscore into my username. Normally it is “Z thomas“. But since two days it is turned into “Z_thomas“

Very strange bug! I don't recall making any changes in 2.8.3 or 2.8.2 that should affect usernames? @maskaravivek @neslihanturan

**Comment by misaochan** [comment] 2018-09-18 07:49
Oops, I just realized that we already had an issue for the date at #1854 . I'll modify this issue to make it solely about the underscore.

**Comment by VojtechDostal** [comment] 2018-09-18 14:42
For me, this issue started between 4th and 13th August - see my contribs at https://commons.wikimedia.org/wiki/Special:ListFiles/Vojt%C4%9Bch_Dost%C3%A1l

**Comment by hoplite390** [comment] 2018-10-15 02:28
@misaochan @VojtechDostal Hi guys, the underscore issue should have been present from 15 Jun 2017. Older posts from @VojtechDostal are with underscore as well. I did not check all of them but it seems to be isolated to his pictures with "Uploaded using Commons Mobile App" in detail. Oldest one from them is [https://commons.wikimedia.org/wiki/File:N%C3%A1m%C4%9Bst%C3%AD_Jana_Pernera_2018.jpg](url). 
My guess is that issue is caused by "String username = canonicializeUsername(usernameEdit.getText().toString());" canonicializeUsername replace space with "_" . I can probably fix that, however i cant predict if that will cause more errors, because there might be some reason why the Author of PageTitle.java normalized usernames like that.

**Comment by domdomegg** [comment] 2018-12-17 11:46
Fixed in #1982

**Closed by domdomegg** 2018-12-17 11:46 UTC
Labels: bug
