### ISSUE TITLE
Telemetry opt-out setting needs to be reworded.


### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3988] opened 2020-10-25 03:42 UTC
The Telemetry opt-out setting is confusing. It needs to be reworded.

So if we turn the setting on, then we are opting out. Then the words describing the setting should be reworded, otherwise it seems we are choosing opposite.

**Comment by sivaraam** [comment] 2020-10-27 18:59
Thanks. This is a duplicate of #3946, though. So, closing this.

**Closed by sivaraam** 2020-10-27 18:59 UTC
