### ISSUE TITLE
GPS category suggestions are not displayed [current master]

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3029] opened 2019-06-20 08:26 UTC
**Summary:** 

Photos taken at a location that I know have categories associated with it (due to having uploaded almost the same photo previously), have no GPS category suggestions. Title-based category suggestions are shown, though.

**Steps to reproduce:** 

Take a photo at a well-known place (or test the upload with the Play Store version to see what categories you get), and then test it with current master (with a long or gibberish title). No category suggestions are displayed when the search field is empty.

**Device and Android version:** 

Samsung Galaxy s9 Android 8.1

**Commons app version:** 

Current master (alpha testing on Play Store)

**Comment by ashishkumar468** [comment] 2019-06-26 17:32
Hi @misaochan , I just tried to upload an image on the current master prodDebug, and I was able to see the GPS based categories as well, attaching the api response for categories with Gps coordinates 
Attaching the screenshot for the same.
![device-2019-06-26-225751](https://user-images.githubusercontent.com/17375274/60201588-384a7280-9866-11e9-9ee9-ad23bb7816dc.png)

Can you confirm that the version was not beta and the image had a lat long (Images uploaded via Google photos donot give us the lat long from the EXIF and this is a know issue, so for those images, gps based categories are not shown)

**Comment by neslihanturan** [comment] 2019-06-27 09:10
I tested images from here: https://github.com/ianare/exif-samples/tree/master/jpg/gps . I used DSCN0010.jpg and DSCN0042.jpg from the list. I confirmed that they have GPS EXIF:
![Screenshot from 2019-06-27 12-05-25](https://user-images.githubusercontent.com/3127881/60253071-230c2d00-98d4-11e9-8b36-c4ac43f9d12c.png)
![Screenshot from 2019-06-27 12-04-57](https://user-images.githubusercontent.com/3127881/60253072-230c2d00-98d4-11e9-85a4-55ac506fbf20.png)

Sorry for my double window screenshot:/

I used random title and descriptions to prevent title based categories, as result both category suggestions was empty. 
![Screenshot from 2019-06-27 12-03-43](https://user-images.githubusercontent.com/3127881/60253149-4a62fa00-98d4-11e9-9794-16f69ff04c41.png)

**Comment by ashishkumar468** [comment] 2020-08-14 08:57
Seems to be working on current master/2.13, closing this one, feel free to re-open this if someone is able to re-produce it :)

**Closed by ashishkumar468** 2020-08-14 08:57 UTC
Labels: bug
