### ISSUE TITLE
App crashes on trying to upload a media directly from camera.

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4238] opened 2021-02-17 10:17 UTC
**Summary:** 

On selecting a image clicked from the camera for upload, the app crashes.

**Steps to reproduce:** 

• Click on the **+** (floating action button) icon in contributions tab.
• Select camera from there.
• Click a photo and select that photo.
• App will crash there.

**System logs:**

```
2021-02-17 15:44:31.801 16499-16499/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 16499
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String fr.free.nrw.commons.contributions.MainActivity$ActiveFragment.name()' on a null object reference
        at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:238)
        at android.app.Activity.performSaveInstanceState(Activity.java:2088)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1486)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5419)
```

**Device and Android version:** 
Redmi Note 7S (Android 10)

**Commons app version:** 
betaDebug master (3.0.0-debug-master~7cb5ff916)

**Screenshots**

https://user-images.githubusercontent.com/65870389/108192667-8f3b4480-713a-11eb-9e13-d450de27d5a1.mp4

**Would you like to work on the issue?**
**Yes**, I want to work on this issue.

**Comment by nicolas-raoul** [comment] 2021-02-20 15:22
I can't reproduce on latest master... is this still happening for you on latest master?

**Comment by mrudultora** [comment] 2021-02-20 15:48
@nicolas-raoul Yes, I am facing it on latest master. Tested just now for confirmation and getting the same exception °-°

**Comment by neslihanturan** [comment] 2021-06-29 07:49
Anyone who feel interested with this issue please make sure you followed the discussions at #4239

**Comment by 4D17Y4** [comment] 2021-08-18 08:38
Closing as this can't be reproduced on the current master.

If there is a specific procedure to reproduce this on the current master
Please feel free to reopen this @mrudultora.

**Closed by 4D17Y4** 2021-08-18 08:38 UTC
