### ISSUE TITLE
[2.13-release] Logout does not work 

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3921] opened 2020-09-10 17:37 UTC
**Summary:** 

Tapping "Logout > Yes" does not actually log me out now. 

More specifically, it seems like I am technically "logged out" but it is not reflected in the UI. Instead of being brought back to LoginActivity I am in Contributions still, with a bunch of images that are not mine.

**Device and Android version:** 

Android 10, Samsung Galaxy s9
 
**Commons app version:** 

2.13-release

**Comment by sivaraam** [comment] 2020-09-11 07:50
Possible duplicate of #3547

**Closed** 2020-09-24 13:46 UTC
Labels: bug
