### ISSUE TITLE
[structured data] "i" icon is too wide in structured data caption field

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3691] opened 2020-04-21 15:08 UTC
**Summary:** 

The "i" tooltip icon in the captions field covers too much space, it is very hard to edit the caption especially on a smaller screen.

For instance on the screenshot below, even tapping the "w" in "wharf" to edit pulls up the tooltip instead.

![Screenshot_1587481242](https://user-images.githubusercontent.com/3611199/79881926-3117d500-8435-11ea-83c3-414888ea586f.png)

**Steps to reproduce:** 

Load structured-data on a small screen device, upload via Nearby to get an autofilled caption, then try to edit it

**Device and Android version:** 

Nexus S API 27 emulator
 
**Commons app version:** 

structured-data, prodDebug

**Would you like to work on the issue?**

No

**Comment by macgills** [comment] 2020-04-21 15:13
duplicate of #3680

**Closed by macgills** 2020-04-21 15:13 UTC
Labels: bug, structured-data
