### ISSUE TITLE
Cancel nearby upload -> Next upload gets the same title/description

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2803] opened 2019-03-29 01:33 UTC
**Steps to reproduce:** 

1. Go to Nearby
2. Select an pin (in my case a nearby research foundation)
3. Click `+` and the camera icon
4. Change your mind and leave the app
5. Open the app from its launcher icon
6. In the Home activity, press `+` and choose an unrelated picture (in my case a picture of flowers)

Expected: Blank fields appear, for me to enter the name and description of the flower
Actual: The fields are pre-filled with details of the research foundation

**Commons app version:** 
2.10.1.356

**Screen-shots:** 
![Screenshot_20190329-095806](https://user-images.githubusercontent.com/99590/55203150-c4b8ab00-520d-11e9-8340-2db717efefe3.png)

**Comment by vanshikaarora** [comment] 2019-03-29 14:23
Hey, I can look into this :)

**Comment by nicolas-raoul** [comment] 2019-04-01 04:13
It is yours @vanshikaarora :-)

**Comment by nicolas-raoul** [comment] 2019-12-04 11:26
@vanshikaarora I guess you are not working on this one anymore? :-) Feel free to share anything you have found out about the issue though.

**Comment by SamuelleMollard** [comment] 2019-12-05 15:12
I would like to work on this issue, though I just can not get in 'Nearby'. I mean, I can, but I only have a blue screen, and pressing the only button there is makes the app crash
Does anyone have any information about that ? Otherwise I will open a new issue since that is kind of a problematic bug, and I have not found any other issue about that.

**Comment by SamuelleMollard** [comment] 2019-12-05 15:44
OK, I didn't unnderstand how 'nearby' works, I was just not located anywhere and ended up in the ocean and I didn't understand that. After I got that to work, the button still makes the app crash, and uploading any picture at any location makes the app crash as well. I will investigate that a bit more later

**Comment by misaochan** [comment] 2019-12-06 09:04
Hi @SamuelleMollard , 

> I was just not located anywhere and ended up in the ocean and I didn't understand that. 

This issue seems to be related to the recent bug #3231 . If you could provide further details of your investigations there, that would be great! 

Also, logs of your crashes would be fantastic (you can either use the app option to send it to our private mailing list, or post them here).

**Comment by nicolas-raoul** [comment] 2019-12-06 09:44
Also, please make sure you are working on the latest source code. I think
one of these crashes has been fixed very recently.

By any chance, is the map in the sea near Punta Arenas?

**Comment by SamuelleMollard** [comment] 2019-12-09 08:36
Indeed I am not working on the latest source code, I'm fixing that

**Comment by neslihanturan** [comment] 2019-12-09 08:42
Puntas Areas PR is up #3271 but not merged yet, it should be merged today.

**Comment by SamuelleMollard** [comment] 2019-12-09 09:30
OK, I have updated the code, and I have tried to replicate the bug. However, I jut can't click on any place. I don't understand how I am supposed to 'select' a pin. I don't know if I don't understand the workflow or if it is  bug

**Comment by SamuelleMollard** [comment] 2019-12-09 09:33
I have discovered a 'list' button, but it opens an empty menu

**Comment by SamuelleMollard** [comment] 2019-12-09 09:44
And yes, I am located near Pontanas Area, and the crash no longer happens

**Comment by neslihanturan** [comment] 2019-12-09 09:56
Hey @SamuelleMollard selecting any pin means selecting one marker(place) from the map. Pontas area still exists on the master, this is expected since the PR is not merged yet. If you want to avoid from that issue and see pins, you can pull my changes from #3271 and work on top of them.

**Comment by SamuelleMollard** [comment] 2019-12-10 09:45
The thing is, I don't really see any kind of markers, I have tried to click on places on the map where there are names of places, but it did not trigger anything

**Comment by SamuelleMollard** [comment] 2019-12-10 10:06
Ok, for some reason I now see the pins

**Comment by SamuelleMollard** [comment] 2019-12-10 10:16
I got the workflow to work, but I can't reproduce the bug. Can someone confirm me they can reproduce it ?
I tried the steps given above but I do get blank fields, whether I input 'next' once or not

**Comment by SamuelleMollard** [comment] 2019-12-10 10:25
Ok, nevermind I got it
I was doing it wrong by actually taking the photo before leaving the app

**Comment by SamuelleMollard** [comment] 2019-12-10 11:13
By the way, if someone knows what activities/method are called it would be a time saver. Just posting that so that if someone knows they can tell me, I am searching through the code to find it anyway

**Comment by SamuelleMollard** [comment] 2019-12-11 16:49
Ok, I have fixed the issue, I am issuing the PR

**Comment by Pratham2305** [comment] 2021-01-30 18:50
hey @nicolas-raoul, I am able to reproduce this. Can I work on this?

**Comment by nicolas-raoul** [comment] 2021-01-31 00:51
@Pratham2305 Yes thanks!
I think you can rebase Manuelle's pull request to the latest master, and address https://github.com/commons-app/apps-android-commons/pull/3292#pullrequestreview-349131086 and https://github.com/commons-app/apps-android-commons/pull/3292#pullrequestreview-415169298

**Comment by Pratham2305** [comment] 2021-01-31 17:56
@nicolas-raoul I have tested the solution given in #3292 and it's not working as expected. I am also getting multiple merge conflicts on that. Can I make a new PR to address the issue?

**Comment by nicolas-raoul** [comment] 2021-02-01 09:05
@Pratham2305 Yes sure thanks!

**Closed** 2021-02-23 13:42 UTC
Labels: bug, nearby
