### ISSUE TITLE
Cursor missing

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4458] opened 2021-06-15 21:57 UTC
At this point try to enter a  space.
![Screenshot_20210616-055304.jpg](https://user-images.githubusercontent.com/1230959/122128734-94e63400-ce67-11eb-9157-5c6b1416f66b.jpg)
We want to enter another word after the word "rain", and we need to enter a space. Well the space is indeed entered but the cursor doesn't move.

The cursor should move to the next line.

No, I'm not talking about the description field at all.

3.0.1.

**Comment by misaochan** [comment] 2021-06-16 06:30
Sorry, I'm not really clear on what the issue is. For instance if you add "at sunrise" after the space after "rain", does it not move to the next line?

**Comment by jidanni** [comment] 2021-06-16 09:33
Actually, everything works fine. The problem is: if the user looks at the screen he thinks that the blank never got entered so be keeps on hitting the spacebar button.

If he does not look at the screen everything works fine.

(Note that I have fonts set to the largest possible, in my Android settings.)

**Comment by jidanni** [comment] 2021-06-16 09:36
If he answers ABCDEFG..., immediately a new line is formed. But if he enters just spaces nothing happens at all (on the screen). He wants to enter one space but he can't tell that it has been received or not by the program.

**Comment by neslihanturan** [comment] 2021-06-16 13:43
This is a generic behaviour of android text view, I don't know if it really has a function but I think it is a behaviour choice rather than a bug. You can see the same in several apps. Here how it happens in Telegram for example, it does not move to next line if I add more spaces. So I think it shouldn't be considered as a bug.
![resim](https://user-images.githubusercontent.com/3127881/122230078-fa670e80-cec1-11eb-818e-a8d90fe88cac.png)

**Comment by jidanni** [comment] 2021-06-18 19:40
Ah, but in your image I see "rig |" so at least one can see the space has been entered, as there is a cursor "|".
But in my image, there is no cursor!

**Comment by nicolas-raoul** [comment] 2021-06-19 10:28
@jidanni When what you are describing happens, are you able to copy/paste? For instance, can you copy the word "mushroom"?

**Comment by jidanni** [comment] 2021-06-19 11:40
Yes, everything works fine. It's just that
there is no cursor bar "|" so I can tell the difference between
"|" and " |".

**Comment by sivaraam** [comment] 2021-06-19 16:18
Curiously the cursor does show up for me in the Caption field as you could see from the screenshot below. Are you never able to see the cursor or does it not appear only in some cases? 

![Screenshot_20210619-213340](https://user-images.githubusercontent.com/12448084/122648653-c56bed80-d147-11eb-8d06-5456c2467d63.jpg)

I do wonder if this could be device specific. 🤔

**Comment by jidanni** [comment] 2022-02-20 12:35
All I know is I don't have any picture to upload today. Also I can't make movies with my bandwidth allowance. Anyways in a different app I just typed a bunch of spaces and I can always see where the cursor is. So please just type a bunch of spaces and see if you can tell where the cursor is. If you can then this bug can be closed.

**Comment by misaochan** [comment] 2022-02-21 08:55
I can see the location of the cursor too in Caption. :/ Might be device-specific.

**Comment by misaochan** [comment] 2022-02-21 08:58
Closing as requested by issue creator, please feel free to ping if anyone can reproduce this bug, thanks!

**Closed by misaochan** 2022-02-21 08:58 UTC
