### ISSUE TITLE
Crash when trying to upload from camera or gallery

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3706] opened 2020-04-24 09:25 UTC
**Summary:** 
<s>When "access to gallery permission is not given" and attempted to upload from gallery, I experienced this crash:</s>
It crashes from both gallery and camera wheneverI try to upload

```
 --------- beginning of crash
2020-04-24 12:18:31.382 24348-24348/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 24348
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@12e6e78: Unmarshalling unknown type code 2131296413 at offset 13204
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@12e6e78: Unmarshalling unknown type code 2131296413 at offset 13204
        at android.os.Parcel.readValue(Parcel.java:2763)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3134)
        at android.os.Parcel.readSparseArray(Parcel.java:2367)
        at android.os.Parcel.readValue(Parcel.java:2741)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:1010)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:772)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
        at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:27)
        at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7099) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
2020-04-24 12:18:31.384 24348-24348/fr.free.nrw.commons E/ACRA: ACRA caught a RuntimeException for fr.free.nrw.commons
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@12e6e78: Unmarshalling unknown type code 2131296413 at offset 13204
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@12e6e78: Unmarshalling unknown type code 2131296413 at offset 13204
        at android.os.Parcel.readValue(Parcel.java:2763)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3134)
        at android.os.Parcel.readSparseArray(Parcel.java:2367)
        at android.os.Parcel.readValue(Parcel.java:2741)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:1010)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:772)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
        at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:27)
        at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
```
and this
```
2020-04-24 12:27:32.762 343-343/fr.free.nrw.commons W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
2020-04-24 12:27:32.763 343-343/fr.free.nrw.commons W/System.err:     at android.view.ViewRootImpl.getHostVisibility(ViewRootImpl.java:1809)
2020-04-24 12:27:32.763 343-343/fr.free.nrw.commons W/System.err:     at android.view.ViewRootImpl.handleAppVisibility(ViewRootImpl.java:1445)
2020-04-24 12:27:32.766 343-343/fr.free.nrw.commons W/System.err:     at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4829)
2020-04-24 12:27:32.767 343-343/fr.free.nrw.commons W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-04-24 12:27:32.767 343-343/fr.free.nrw.commons W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-04-24 12:27:32.767 343-343/fr.free.nrw.commons W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7099)
2020-04-24 12:27:32.768 343-343/fr.free.nrw.commons W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-04-24 12:27:32.768 343-343/fr.free.nrw.commons W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
2020-04-24 12:27:32.768 343-343/fr.free.nrw.commons W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2020-04-24 12:27:32.797 343-492/fr.free.nrw.commons W/libEGL: EGLNativeWindowType 0x725a451010 disconnect failed
```

**Comment by nicolas-raoul** [comment] 2020-04-24 09:34
Have you tried removing the app's data in the Android settings?
We can't expect all users to do that, but it might be a hint.

**Comment by macgills** [comment] 2020-04-24 09:42
You have do not keep activities turned on, closing

**Comment by misaochan** [comment] 2020-04-24 09:42
@neslihanturan Which branch and commit are you testing?

**Closed by macgills** 2020-04-24 09:42 UTC
Labels: bug

**Comment by neslihanturan** [comment] 2020-04-24 10:01
Ah this settings, Sean is right sorry for wrong allert

**Comment by sivaraam** [comment] 2020-04-24 11:22
> Ah this settings, Sean is right sorry for wrong allert
It's not a wrong alert per se. I believe this is just a part dupe of #3639
