### ISSUE TITLE
Append " (12345)" instead of " -12345" when filemame already exists

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5876] opened 2024-10-20 02:57 UTC
Currently, when the caption chosen would result in a filename that already exists on the server, the app appends " -65728" or similar random number at the end.

While it works well, it sometimes results in a different meaning. For instance in the screenshot below, "Ebisu 2" is not the same geographical location as "Ebisu" so the filename conveys an incorrect meaning.

![Screenshot_20241020-113103~2.png](https://github.com/user-attachments/assets/d2c28f9d-c962-44df-9bd6-75b671fa5ad6)

It also often happens with time indications, for instance "Zenpukuji river, October" becoming "Zenpukuji river, October 2". The meaning changes to affirm that the picture was taken on the second day of October, which is probably untrue.

I believe that putting the number within parenthesis would drastically lower the number of changed meanings.

# Example:

If a user uploads a picture with caption "Zenpukuji river, October", the filename becomes "Zenpukuji river, October" because there is no such filename yet on Wikimedia Commons.

Later, if a user uploads a picture with caption "Zenpukuji river, October", the filename becomes "Zenpukuji river, October (16742)" because the filename "Zenpukuji river, October" already exists.

etc

**Comment by junnzhuu** [comment] 2024-10-20 05:55
I seem to have been unable to reproduce this issue. I uploaded three images named "Ebisu," but no suffix numbers appeared.
![5361729403630_ pic](https://github.com/user-attachments/assets/b2ea927c-48a2-4aee-8aea-810b5972176b)

**Comment by junnzhuu** [comment] 2024-10-20 07:06
This issue does indeed occur. Could you assign it to me?

**Comment by devbytespark** [comment] 2024-10-20 09:56
Happy to let @junnzhuu take this one, thanks for the notice.

**Comment by riabomma** [comment] 2024-10-24 11:39
Hi, could I have a go at this?

**Comment by junnzhuu** [comment] 2024-10-24 12:41
> This issue does indeed occur. Could you assign it to me?这个问题确实存在。可以分配给我吗？

Hi, I have made some attempts, and it seems that this issue has been fixed, as shown in the figure. Now, if the user enters a duplicate caption when uploading, a number in parentheses will be added after the title to differentiate it. If you could assign this issue to me, I can submit a PR.

![image](https://github.com/user-attachments/assets/143bf2d6-ddf5-4271-8a89-1a5bb03d5556)
![image](https://github.com/user-attachments/assets/6c5bbb61-a5c3-4990-96a7-7b354758f479)
![image](https://github.com/user-attachments/assets/962a426a-d672-494c-8f0a-207904b81faf)

**Comment by whym** [comment] 2024-10-29 08:59
Isn't this going to be eventually superseded by #2506 (and #5877)?

**Comment by nicolas-raoul** [comment] 2024-11-14 02:46
@whym Yes it is very related, but not exactly the same change. :-)

**Comment by Sujal-Gupta-SG** [comment] 2024-12-28 06:53
Hi, I would like to request the assignment of this issue (#5876). I have implemented the fix to append random hashes in parentheses instead of directly at the end of filenames, which helps prevent changes in meaning. I have tested the fix on my Realme Narzo 20 and confirmed that it's working as expected.

I am eager to contribute further and would appreciate it if you could assign the issue to me.

Looking forward to your feedback!

Thank you,
Sujal 
![Screenshot_2024-12-28-11-54-35-02_062c6066f629c24413cc8efde3bd9f38](https://github.com/user-attachments/assets/27695d2b-b49c-4007-a260-0ab158fa4945)
![Screenshot_2024-12-28-11-54-24-81_062c6066f629c24413cc8efde3bd9f38](https://github.com/user-attachments/assets/89aa9f5a-0637-4ef4-83a5-0b4ded0959dc)

**Comment by nicolas-raoul** [comment] 2024-12-28 07:31
@Sujal-Gupta-SG Seems great! Looking forward to your pull request. 🙂

**Closed** 2024-12-29 07:09 UTC
Labels: bug

**Comment by Sujal-Gupta-SG** [comment] 2024-12-29 08:45
@nicolas-raoul After merging this commit, the build has failed. Can someone investigate the issue to determine why it failed and let me know if any actions are required to fix it?

**Comment by nicolas-raoul** [comment] 2024-12-29 09:00
Do you mean in main? Somehow coverage calculation is broken in main I believe, don't worry it is not because of this PR. :-)
Unit tests are passing on main, I just ran them now on my computer.

**Comment by Sujal-Gupta-SG** [comment] 2024-12-29 09:58
@nicolas-raoul 
Okay, I got it! Thanks for the clarification.
