### ISSUE TITLE
Wrong image details in Explore

### ISSUE THREAD

**Issue by DeepaMalani** [commons-app/apps-android-commons#3180] opened 2019-10-22 17:52 UTC
**Summary:** 

After getting search results in Explore, sometimes when clicking on image it displays wrong image details.

**Steps to reproduce:** 

How can we reproduce the issue? 
What did you expect the app to do, and what did you see instead?

1. Go to Explore
2. Type cat/fish in search box
3. Click on the list item
4. Wrong image details 
For example - Clicking on second image it displays details of the first image

Try to click on different - different images.
 

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
Sony Xperia
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Android 5.02

 **Commons app version:** 

2.11.0

**Would you like to work on the issue?**
Yes, I can work on this issue.

**Comment by ashishkumar468** [comment] 2019-11-05 18:49
Hi Deepa, Thanks for finding the issue. I am not able to reproduce this, is there a  specific way to produce this. It would be great if you could attach a GIF supporting the same. :-)

**Comment by DeepaMalani** [comment] 2019-11-06 18:50
Hi Ashish,

This issue is related to issue 1650. It will be automatically resolved after solving #1650 
When we get the wrong list in Explore then it displays the wrong details also.

Steps to reproduce are similar to #1650 
For example, I want to get the result for pink

1. Type pi and let the loader starts
Here is the screenshot

![Screenshot_2019-11-06-18-38-46](https://user-images.githubusercontent.com/24900514/68327781-da832e00-0082-11ea-9e8b-2eb2836c11d3.png)

2. Once loader starts immediately type remaining letters for example "nk" in my case.

Screenshot
![Screenshot_2019-11-06-18-42-54](https://user-images.githubusercontent.com/24900514/68327843-f686cf80-0082-11ea-8734-a95fe7c5a245.png)

3. It shows the wrong list. Now, I clicked on the second list item but got the detail of the first item.
![Screenshot_2019-11-06-18-43-09](https://user-images.githubusercontent.com/24900514/68327964-30f06c80-0083-11ea-9543-cc23c2cd0a79.png)

**Comment by nicolas-raoul** [comment] 2019-11-25 09:45
Thanks @DeepaMalani for investigating!
Is it exactly the same issue as #1650? If seems so, so I will close this issue and let you work on #1650 which is assigned to you :-)

**Closed by nicolas-raoul** 2019-11-25 09:45 UTC
