### ISSUE TITLE
Special upload for campaign like WLE and WLM

### ISSUE THREAD

**Issue by Zthomasdewp** [commons-app/apps-android-commons#3375] opened 2020-02-05 11:53 UTC
**Summary:** 

The App should support campaigns like Wiki Loves Monuments and Wiki Loves Earth.

It would be useful that it is possible to upload pictures for Wiki Loves Monuments and Wiki Loves Earth. Adding the "Template" of the campaign.

It would also be useful to fitler for objects that belong to the campaign like "Natural monuments" and "Cultural heritage monunments" or Wikidata-Items like these

**Comment by GearGit** [comment] 2020-02-05 12:16
@Zthomasdewp I would like to work on this issue.

**Comment by nicolas-raoul** [comment] 2020-03-21 13:35
I think this is a duplicate of #545

@Zthomasdewp feel free to add more info there, thanks! :-)

@GearGit Please read bullet 3 at https://github.com/commons-app/documentation/blob/master/android/Volunteers-welcome!.md#developers ;-)

**Comment by neslihanturan** [comment] 2021-02-01 14:33
Closing this one as it is duplicate :)

**Closed by neslihanturan** 2021-02-01 14:33 UTC
