### ISSUE TITLE
Retry of failed upload uploaded image again

### ISSUE THREAD

**Issue by Ainali** [commons-app/apps-android-commons#3218] opened 2019-11-24 11:48 UTC
**Summary:** 

I started an upload of an image and put my phone in the pocket. Next time I open it I have a notification that it failed. In the list on the main view of the app I pressed the retry icon in the lower right corner of the image. The image starts the upload again and it seems to succeed. When I later look at my contributions I noticed that the image actually did succeed the first time and it then uploaded the same image again: 

* https://commons.wikimedia.org/wiki/File:Timorstraat.jpg
* https://commons.wikimedia.org/wiki/File:Timorstraat_2.jpg

In the app it looks like only the second one has been uploaded.

**Steps to reproduce:** 

I don't know how to reproduce.

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?

Samsung Galaxy S7 Edge

What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?

Android version 8.0.0

Samsung Experience version 9.0

Is it the stock version from the manufacturer or a custom ROM ?

The stock version.
 
**Commons app version:** 

2.11.0~93b948d20

**Would you like to work on the issue?**

No.

**Comment by ashishkumar468** [comment] 2019-11-24 15:24
Thanks for figuring out this bug @Ainali. This must have been one of those cases when the image does get uploaded but one of the other steps fail.

**Comment by nicolas-raoul** [comment] 2019-11-25 09:32
Any newcomer willing to take this? :-)
Tip: To make an upload fail, switch Android to airplane mode just after the upload starts.

**Comment by FernandaCG** [comment] 2019-11-29 16:43
Hi, can I work on this??

**Comment by neslihanturan** [comment] 2019-11-29 18:58
It is yours @FernandaCG :) This can be a relatively complicated task, so please communicate with us about the steps you have done so that we can share ideas.

**Comment by FernandaCG** [comment] 2019-12-13 18:58
Hi @neslihanturan, I have been debugging the app, and I think that in the method retryUpload in ContributionViewHolder we could validate if the file already exists, but idk which attribute of the contribution could I use. Can you give me some feedback?

**Comment by gouri-panda** [comment] 2019-12-28 18:07
Hi guys, can I work in this issue?

**Comment by ashishkumar468** [comment] 2020-01-28 04:51
@FernandaCG  Are you still working on this?
About this 

>  I have been debugging the app, and I think that in the method retryUpload in ContributionViewHolder we could validate if the file already exists

You can check that using the title, the titles are supposed to be uniques, in fact, there is an existing method that lets you know if the file exists or not.

**Comment by FernandaCG** [comment] 2020-01-28 19:07
Hi! @gouri-panda you can take the issue :D

**Comment by gouri-panda** [comment] 2020-01-28 19:08
Thanks @FernandaCG

**Comment by gouri-panda** [comment] 2020-01-29 14:55
> Any newcomer willing to take this? :-)
> Tip: To make an upload fail, switch Android to airplane mode just after the upload starts.

@nicolas-raoul  I can't reproduce this issue. I tried several times but it doesn't reproduce. Can you help me?

**Comment by mds08011** [comment] 2020-02-03 18:47
I am having a similar issue.  However, I didn't have an uploading error message and it looks like only one copy of my image uploads commons.wikimedia.org the app showing two.

**Summary:** 

After uploading photos, I see duplicate images in the app's "contributions" screen.

**Steps to reproduce:** 

1. Upload an image to Wikimedia Commons using this Android App.
2. Look though your photos in the "contribution" for duplicate images (they may not be adjacent to each other in the image feed).
3. View your account's "uploads" on https://commons.wikimedia.org and look for any duplicate images.

I see duplicate images on the app but the website shows that the photo uploaded correctly (no duplicates).

**System logs:**

Logs exported from the app: https://privatebin.net/?6ccdcedda9153900#7YwYwPohymf1LZ6iBuUf8jBQBbj9hDzUjiZcwGvejr4i

**Device and Android version:** 

API level: 29
Android version: 10
Device manufacturer: Google
Device model: Pixel 2
Device: walleye
Network type: wifi
App version name: 2.12.3~dc08a5e88
User name: Mds08011
 
**Commons app version:** 

App version name: 2.12.3~dc08a5e88

I am currently using the Beta version but this issue occurred on the regular/stable version as well.

**Screen-shots:** 

Duplicate photo in app:
<img src="https://user-images.githubusercontent.com/8010709/73565371-3fe28300-4416-11ea-90ec-dac8728c5285.png" width="30%">

Duplicate photo in app:
<img src="https://user-images.githubusercontent.com/8010709/73565372-3fe28300-4416-11ea-9dde-c4d98cdd6034.png" width="30%">

"Uplaods" on website showing only single images:
<img src="https://user-images.githubusercontent.com/8010709/73565373-3fe28300-4416-11ea-8987-7eeadf024db6.PNG" width="80%">

**Would you like to work on the issue?**

No.  I don't have the technical knowledge to address this.

**Comment by nicolas-raoul** [comment] 2020-02-04 04:24
@Ainali Do you mean all failed uploads show correctly after you retry them? Have many times did you perform the steps? Thanks :-)

**Comment by isnirp** [comment] 2020-04-04 13:24
I think this issue is similar to what I have reproduced. The upload failed, an attempt to upload again failed even after the progress was complete. I restarted the app and noticed the image was uploaded yet it also showed the failed upload. I experienced this on 2 occasions...
![failed](https://user-images.githubusercontent.com/10153512/78451826-1b11c280-7688-11ea-8a62-a46764acd376.gif)

**Comment by michaelnares** [comment] 2020-07-11 19:05
Can I take this one one, please?

**Comment by maskaravivek** [comment] 2020-07-11 19:42
@michaelnares As a first step, can you try to reproduce this issue and list down the steps here.

**Comment by michaelnares** [comment] 2020-07-12 14:47
> @michaelnares As a first step, can you try to reproduce this issue and list down the steps here.

@maskaravivek I get https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining.  I have success after git clone https://github.com/commons-app/apps-android-commons.git --depth 1
 and cd apps-android-commons/, but the same error after git fetch --unshallow.  Is there any issue with working on the repository without doing git fetch --unshallow, please?

**Comment by ashishkumar468** [comment] 2020-08-14 09:00
Has anyone been able to reproduce this issue on the latest commits?

**Comment by nicolas-raoul** [comment] 2020-08-14 14:20
@ashishkumar468 I am having so many failed upload with recent versions, but retry always works perfectly. I guess this can be closed if nobody manages to reproduce with the latest version.

**Comment by ashishkumar468** [comment] 2020-08-17 07:46
Hi @nicolas-raoul  Should we create a new issue for that, as this issue is related to retries?

**Comment by nicolas-raoul** [comment] 2020-08-17 09:32
There is already an issue about the failures. My comment above was only saying that retry works :-)

**Comment by ashishkumar468** [comment] 2020-08-17 10:07
@nicolas-raoul  Ohh, okay, so we can close this issue right?

**Comment by nicolas-raoul** [comment] 2020-08-17 10:18
I think it is OK to close it, yes.

**Closed by nicolas-raoul** 2020-08-17 10:18 UTC
Labels: assigned, bug, good first issue

**Comment by misaochan** [comment] 2020-08-17 10:30
For reference, the issue regarding failed uploads is #3247 .
