### ISSUE TITLE
[Bug]: Retried uploads stuck in queued state

### ISSUE THREAD

**Issue by pigsonthewing** [commons-app/apps-android-commons#5136] opened 2022-12-31 14:24 UTC
### Summary

Copied from https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app#Image_upload_stuck_at_%22queued%22 - where the only suggestion had been to ignore the issue and start a new upload]

I shared two images using the app yesterday [13 December 2022]; both failed and I retried them. The first ([File:Image 70 coffee set - 2022-12-13 - Andy Mabbett - 01.jpg](https://commons.wikimedia.org/wiki/File:Image_70_coffee_set_-_2022-12-13_-_Andy_Mabbett_-_01.jpg)) then uploaded successfully, but the second (filename ending "02") is showing in the app as "queued". There appears to be no feature in the app allowing me to force the upload to start. I have forced the app to close, and restarted it, to no avail. What should I do? 

### Steps to reproduce

See above.

### Expected behaviour

There should be a way to force "queued" uploads to restart.

### Actual behaviour

See above.

### Device name

OnePlus Nord

### Android version

Android 11

### Commons app version

4.0.5~f03b7dd8d

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment] 2023-01-13 11:00
I am able to reproduce this issue:
1. Start an upload of 3 pictures, then open another heavy app. (or maybe just cut WiFi?)
2. After at least two of them failed, come back to the app and tap the "retry" button for all of the failed pictures.
3. Let one upload succeed.
4. The remaining picture is marked as "queued" and not actionable, even after restarting. Checking my uploads on the Commons website, the picture has not been silently uploaded either.

**Comment by pigsonthewing** [comment] 2023-01-17 18:55
For the record, I used the app today to upload an unrelated new image. The "queued" image from December also uploaded, without my doing anything deliberately to initiate this, and without prior warning.

**Comment by nicolas-raoul** [comment] 2023-01-18 00:55
Andy: I observed this too, I often perform a single upload to "unblock" stucked queued uploads. Far from ideal but that is a workaround.

**Comment by mnalis** [comment] 2023-06-15 15:46
I can confirm both the bug and the workaround, in latest f-droid release (4.1.0~1649d1e2c) on Android 10 (EMUI 12), Huawei P30 Pro.

**Comment by nicolas-raoul** [comment] 2023-06-16 06:57
Since about a month, the workaround [above](https://github.com/commons-app/apps-android-commons/issues/5136#issuecomment-1386304752)  does not work anymore for me (master branch). Stuck upload stay stuck forever even if I upload new pictures and pause/unpause the stuck ones repeatedly.

**Closed** 2023-09-09 17:16 UTC
Labels: bug, upload-reliability
