### ISSUE TITLE
In my home network the Nearby function is showing a position in Indonesia

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#300] opened 2016-10-13 15:12 UTC
Hello, the nearby function generally seems to work in many public places for me as well as at work, but it has some serious problems in my home WiFi network. Specifically, it thinks I am in Pekanbaru, Indonesia, even though I am currently in Glasgow, UK. Not sure why this is the case because all other apps which read my location (Uber, Google Maps) work just fine. 

Any ideas? Thanks

**Comment by nicolas-raoul** [comment] 2016-10-13 15:25
Hi,

Have you tried turning it off and on again? :-)
The app has a short-lived cache, so a wrongful GPS read might be kept in
cache.

But if the problem still happens after killing the app then it must be
another issue, though.
The adb logcat might help.

Cheers!
Nicolas Raoul

**Comment by VojtechDostal** [comment] 2016-10-13 15:28
This has been happening for at least two weeks now and yes, I have switched off the app many times during this time. I hope I understand your advice correctly :-). But it doesn't seem to be the case of just cache. Also I have never been to Indonesia.

**Comment by nicolas-raoul** [comment] 2016-10-13 15:30
Could you please post your ADB logcat? You might need to install the Android SDK and activate developer options in Android, if you haven't done it already.

**Comment by VojtechDostal** [comment] 2016-10-13 19:27
Nicolas could you please send me a link or explain what is ADB logcat? 

I have to install Android SDK where, on my phone?

I downloaded an app that is called "SDK Manager" and fetched some data from the phone but I don't see anything related to the Wikimedia Commons app in there.

**Comment by misaochan** [comment] 2016-10-14 04:52
Hi Vojtech,

This is the method I personally use to view logcat: https://developer.android.com/studio/debug/am-logcat.html#running . It's quite simple and doesn't require use of the command line. However it requires you to download Android Studio, which is a bit of a pain and waste of bandwidth if you don't want to do Android development.

There are other methods that dont require downloading Android Studio but AFAIK those require use of command line. 

For my method, I just connect my phone to the computer, enable USB debugging in my phone, launch android studio, launch android device monitor and select my phone device. When I use the app as usual on my phone, logs display on the screen. 

A simpler option is to use third party apps like http://stackoverflow.com/questions/6376889/can-i-see-the-logcat-on-the-android-phone-itself-without-connecting-it-to-the-c , but I cannot vouch for that as I have never used it personally.

**Comment by nicolas-raoul** [comment] 2016-10-14 05:13
And here is the tutorial I wrote on how to get a logcat:
http://android.stackexchange.com/a/157594/501

Cheers!
Nicolas Raoul

**Comment by VojtechDostal** [comment] 2016-10-16 17:15
Whoa! And I thought Wikipedia was overcomplicating things. 

I didn't move a single inch after trying to get the logcat for 2 hours, using various methods. I am giving up, sorry, this is far too difficult and time-demanding. 

The Android studio has 1.5 GB, I'll try to download this when I have qu

**Comment by misaochan** [comment] 2016-10-16 23:39
Yeah, sorry, it really is overcomplicated. :( I wish there was a simpler way for users to access the logcat, but I don't think we have any control over that. I've heard that the simplest way is the use of third party apps like the third option I've mentioned above, but I think using those apps would require your phone to be rooted, not to mention security concerns. 

Let me know if you have any problems accessing logcat with Android Studio, I can try to help with that.

**Comment by VojtechDostal** [comment] 2016-10-29 15:54
Finally I am able to access my logcat (the problem was I couldn't access developer mode because I didn't have magnification accessibility settings allowed and this prevented me clicking 5 times on the "build number" button which is required for switching developer mode on). 

I will try to replicate the bug and post the logcat here in a few hours time.

**Comment by VojtechDostal** [comment] 2016-10-29 18:14
But now it started working normally :(

**Comment by maskaravivek** [comment] 2017-11-17 20:05
I was also unable to reproduce the issue on my wifi or mobile network. I tried both my home and office Wifi. 
@VojtechDostal if this issue is no longer happening then I would like to close this issue. :)

**Comment by VojtechDostal** [comment] 2017-11-18 07:54
This now hasnt happened for a very long time in the current version of the app. Thanks for closing it @maskaravivek

**Comment by misaochan** [comment] 2017-11-18 13:37
Closing, thanks guys! :)

**Closed by misaochan** 2017-11-18 13:37 UTC
Labels: bug, nearby
