### ISSUE TITLE
Category field should not change to capitals every time a space is typed

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#1468] opened 2018-04-29 16:51 UTC
Every time I add a space when typing categories, the letter case is changed to capitals. Many categories do not start each letter in capitals so this is quite frustrating. What do you think?

**Comment by misaochan** [comment] 2018-04-30 07:05
Hmm, sorry @VojtechDostal , I'm not clear on that the issue is. Do you mean that your phone keyboard auto-corrects your input to a capital for each new word when you are searching for categories in the Categories screen?

If so, firstly I don't know if we can do anything about it - it seems to be a keyboard setting on your device. Secondly I'm not sure if it makes a difference - our categories SHOULD show up when searched regardless of capitals (ie case should be irrelevant). And the categories that are saved at the end of the day are the categories that you select by tapping the "tick" at the end, the textbox above them is just for searching for them and does not affect the final output.

**Comment by VojtechDostal** [comment] 2018-04-30 09:00
It seems to be really specific to this one text field though...

But if the search algorithm disregards letter case, then it's all right for me :-)

**Comment by tanvidadu** [comment] 2018-04-30 15:03
This is might be because of the pull-request #1099 which fixed the issue #1098

**Comment by misaochan** [comment] 2018-04-30 15:41
Wow, I just noticed #1098 ! I really wonder why the search issue mentioned in that issue would occur, when AFAIK our MediaWiki query is case-insensitive? For instance, I searched https://commons.wikimedia.org/w/api.php?action=query&list=search&srwhat=text&srnamespace=14&srlimit=10&srsearch=four%20storeys%20house for `Four Storeys House` and `four storeys house` and got exactly the same results.

@neslihanturan are you sure that lowercase affected the results that you obtained? Even if it did though, lots of categories do not use Camel Case, it is a bit of a mix between the two.

**Comment by neslihanturan** [comment] 2018-05-01 05:08
Hmm, at the time we merged that PR, category search was a little problematic. I remember, several times I had to write exactly same category name to see results. So maybe I misunderstood the root cause of this issue. Do you think it is better to use capital for only first letter? Because I think weight of categories that start with capital is higher. There is no a balanced mixture.

**Comment by nicolas-raoul** [comment] 2023-09-29 06:44
This does not happen anymore, from my experience. If you disagree, feel free to reopen. Thanks all! :-)

**Closed by nicolas-raoul** 2023-09-29 06:44 UTC
Labels: enhancement, categorization
