### ISSUE TITLE
Copy title and description from last upload

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#65] opened 2016-02-16 13:15 UTC
not sure what is the best way to implement. action toolbar?

**Comment by misaochan** [comment] 2016-03-01 06:45
This would be nice! Maybe we could just automatically save the previous picture's title in a short-lived cache, and have a button on the Title/Desc screen that says 'Use previous title/desc'?

**Comment by nicolas-raoul** [comment] 2016-03-01 06:53
Yes that would be nice.
Pre-filling would probably be too much, wasting time of people who never upload two pictures of the same thing.

**Comment by misaochan** [comment] 2016-09-07 04:12
Do you think it would be better to have just one button for both title and desc, or one button for each?

**Comment by nicolas-raoul** [comment] 2016-09-07 05:20
I would be for a single button.

**Comment by misaochan** [comment] 2016-10-07 10:19
I've gotten it working, but am messing around with the design. Does this (transparent button) look OK? Is it self-evident to users that they need to tap it? I initially made a non-transparent button, but it just looked jarring since everything else was transparent.

![transparent-button](https://cloud.githubusercontent.com/assets/3611199/19186785/688e344e-8ce4-11e6-8e44-bd51421dea73.png)

**Comment by nicolas-raoul** [comment] 2016-10-07 10:28
Not a UI expert but looks good to me :-)

**Comment by misaochan** [comment] 2016-10-08 03:40
Released. I decided to go with a matching black background for the button instead, since I figured that fully transparent might be confusing for new users. Let me know if it works okay for you guys!

**Comment by misaochan** [comment] 2019-03-30 12:37
This button does not exist anymore in the new upload screen, AFAIK. I think it would be nice to have it again, both for single and multiple uploads.

**Comment by maskaravivek** [comment] 2019-03-30 12:41
@misaochan Is #2035 a duplicate of this issue? 

@nfatma is working on fixing this in #2713

**Comment by misaochan** [comment] 2019-04-01 10:18
Ah yes, that did not turn up in my search, sorry!

**Closed by misaochan** 2019-04-01 10:18 UTC
Labels: beginner friendly
