### ISSUE TITLE
In nearby tapping on back button does not close nearby list

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2300] opened 2019-01-14 17:57 UTC
**Summary of the issue** 

In the nearby fragment when we press the back button then nearby list doesn't closes instead it takes us to contributiions fragment

**Steps to reproduce:** 

- Click on the nearby tab
- Select the list option located in the end in the toolbar
- Nearby list appears
- Now press the back button
- It takes you to contribution tab

Intead it should have closed the NearbyList 

**Device and Android version:** 
vivo 1713 Android version 7.0 
 
**Commons app version:** 

2.9.0-debud-nearby_list~b23038ac0

**Would you like to work on the issue?**
Yes

**Comment by sp2710** [comment] 2019-01-14 19:38
Is this not same as #2245 ?

**Comment by nicolas-raoul** [comment] 2019-01-15 02:13
Duplicate of #2245

**Closed by nicolas-raoul** 2019-01-15 02:13 UTC
