### ISSUE TITLE
Upload semi-failure for image without EXIF, reproducible 100%

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4940] opened 2022-04-22 06:46 UTC
### Steps to reproduce

1. Install [Scrambled EXIF](https://play.google.com/store/apps/details?id=com.jarsilio.android.scrambledeggsif) app
2. Choose a picture worth uploading to Commons, share it to Scrambled EXIF, then share the result to Commons
3. Enter a caption, press Next
4. A popup `No location found` appears, press `Skip`
5. A popup `Problems found in image` appears, press `Upload`
6. Select a correct depiction, category, license, and send

### Expected behaviour

Upload should succeed

### Actual behaviour

There are two thumbnails, one uploaded and one failed, as seen below (I uploaded only once "Restaurant [...]" picture):

![adb](https://user-images.githubusercontent.com/99590/165007753-2d90445c-efea-41a5-8af3-2250fc8063c8.png)

### Android version

8

### Commons app version

master

### Would you like to work on the issue?

Prefer not

**Comment by misaochan** [comment] 2022-04-22 09:06
Hi @nicolas-raoul , does this only happen with the Scrambled EXIF app specifically, or any other methods of deleting EXIF as well?

**Comment by nicolas-raoul** [comment] 2022-04-22 09:33
I have not tried, sorry.

**Comment by JustinLiang522** [comment] 2022-04-23 10:58
Hi @nicolas-raoul, I followed the steps to reproduce the bug on my pixel 3 (Android 10), but the file was successfully uploaded. Can you send me the picture that caused the failure on your phone via email so that I can test them on mine?

**Comment by nicolas-raoul** [comment] 2022-04-25 02:00
@JustinLiang522 Interesting finding!

I just reinstalled the app and tried again, same issue. I edited the instructions above because I had made a mistake, sorry about that!

Here is one of my pictures that I just passed though ScrambledExif: https://drive.google.com/file/d/1o_Wd3FkDuzsWYdNmsvkpsrX_AmaXGjPi/view?usp=sharing

**Comment by 4D17Y4** [comment] 2022-05-15 10:58
Can reproduce this, 
Upload also fails for images with removed metadata using [ExifEraser](https://play.google.com/store/apps/details?id=com.none.tom.exiferaser&hl=en_IN&gl=US)

**Comment by JustinLiang522** [comment] 2022-05-22 05:54
@nicolas-raoul  I can reproduce it now, can I work on this issue?

**Comment by JustinLiang522** [comment] 2022-05-22 06:14
From the Logcat, a `SecurityException` is raised when the picture is not uploaded by a process whose `uid=10100` (the UID of the preinstalled photo app). I think the issue arises because the common apps deny permission when uploading photos directly from apps other than the system photo app, such as ExifEarser and Scrambled EXIF.

**Comment by JustinLiang522** [comment] 2022-05-26 08:33
According to [this StackOverflow question](https://stackoverflow.com/questions/46684243/openinputstream-cause-securityexceptionpermission-denial-android-n), when the `UploadWorker` try to open the input stream of the content Uri, the read permission is denied, because the `UploadActivity` has terminated at the time.
I suggest the following solutions:
1.  store the hashcode of the image into the `contribution` table before the `UploadActivity` is destroyed so that we don't need to call `openInputStream()` to get the hashcode of the original image file.
2. do not save the contribution to the `uploaded_table`

The first one may need to modify the database table structure and the second one may cause other bugs since I do not know about the usage of the `uploaded_table`. I am wondering if there is any better solution.

**Comment by nicolas-raoul** [comment] 2022-05-26 08:43
Interesting!
Thanks for explaining different strategies.
How about trying to implement based on the first solution?

**Comment by JustinLiang522** [comment] 2022-05-28 07:40
I was trying to access the database, but the connection was closed by the host and I don't know the reason.
![image](https://user-images.githubusercontent.com/73240868/170815721-26889ff7-c20a-43f0-93b3-111f9a778ba8.png)

**Comment by nicolas-raoul** [comment] 2022-05-28 09:25
Do you really need to access any database on wmflabs.org? My understanding is that it is about the app's local SQLite database on the Android device :-)

**Comment by JustinLiang522** [comment] 2022-05-28 10:42
How can I modify the app's local SQLite database? It is new to me. 😓

**Comment by nicolas-raoul** [comment] 2022-05-28 11:46
You can read the content using the various solutions at https://stackoverflow.com/questions/17529766/view-contents-of-database-file-in-android-studio, but to **modify** the content, you will probably want to modify the app's source code, as it is eventually the app that modifies the database (including columns creation/etc).

**Comment by JustinLiang522** [comment] 2022-05-29 04:50
Got it, thanks!

**Comment by nicolas-raoul** [comment] 2022-05-29 10:37
I forgot to mention that the SHA should not be inserted in database before the picture is completely uploaded. How about keeping the SHA somewhere, and adding it to database if the upload is successful?

**Comment by JustinLiang522** [comment] 2022-05-30 02:44
Thanks for reminding me! Actually, the SHA will not be inserted into the `uploaded_table` if the upload fails. It will just be in the `contribution` table. If this situation may still cause problems, do you have any suggestions about where I can store the SHA or can I just delete the SHA from the `contribution` table if the upload fails?

**Comment by nicolas-raoul** [comment] 2022-05-30 05:29
> Actually, the SHA will not be inserted into the uploaded_table if the upload fails. It will just be in the contribution table.

Ah, then it is good, thanks! :-)
I was afraid that the picture could appear as "uploaded already" in the custom selector UI, despite not really having been uploaded successfully.

**Closed** 2022-05-30 07:14 UTC
Labels: bug
