### ISSUE TITLE
User loses sight of the app during  sharing

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4388] opened 2021-04-30 00:37 UTC
First, choose your Android phone's Gallery app and launch it. Okay now find a photo and push Share. Okay now from all the sharing applications pick the Commons application. Okay fill in the  forms as usual and when we finally get to the last screen we touch the Submit button. All is okay so far except now we are switched back to the gallery app looking at the original photo!

( Yes, somewhere in the background in Android the Commons app is actually uploading the  photo but wouldn't it be more pleasant to have a progress bar on the screen and when we finally succeed have a message that it completed and then be sure to have the user touch it before it'll disappear or whatever.)

**Comment by jidanni** [comment] 2021-04-30 00:39
My point is all through the process the user should never lose sight of the Commons app. Not even for one second. Yes after the picture is finally fully uploaded there should be a final way for him to push an okay button to confirm that he understands that all this has finished. And only then should the app disappear.

**Comment by jidanni** [comment] 2021-04-30 00:39
And yes, temporary toast messages aren't good enough. Because his head might have been turned when it popped up. So be sure to have a confirm button. I guess you would call it an okay button.

**Comment by jidanni** [comment] 2021-04-30 00:40
And yes, I reported this bug when a picture was still uploading in the background so I'm not sure what was going to happen next. However the app shouldn't have switched back to the gallery even for one second anyway.

**Comment by Rishavgupta12345** [comment] 2022-03-06 14:22
@nicolas-raoul  @4D17Y4 we have this feature now in our app so we can close this issue now

**Comment by nicolas-raoul** [comment] 2022-03-07 09:38
This is still happening, but I think it is working as intended.
Same happens with the Gmail app.

**Closed by nicolas-raoul** 2022-03-07 09:38 UTC
Labels: debated
