### ISSUE TITLE
App crashes on switching between contribution tab and nearby tab fastly

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4269] opened 2021-02-23 04:15 UTC
**Summary:** 

On denying permission the dialog box pops out. Denying frequently and at the same time switching between contribution tab and nearby tab fastly causes crash.

**Steps to reproduce:** 

https://user-images.githubusercontent.com/65870389/108801255-401e6500-75bb-11eb-8a45-893c604cd96b.mp4

**System logs:**

```
Caused by: java.lang.IllegalStateException: Fragment ContributionsFragment{aa806c3} (8bfccd01-026a-4dec-9538-d1188d1ae72f)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:869)
        at fr.free.nrw.commons.contributions.ContributionsFragment.displayYouWontSeeNearbyMessage(ContributionsFragment.java:485)
        at fr.free.nrw.commons.contributions.ContributionsFragment.lambda$wbj1_b0L0YSojQ4fpcfFc5i9Xp4(Unknown Source:0)
        at fr.free.nrw.commons.contributions.-$$Lambda$ContributionsFragment$wbj1_b0L0YSojQ4fpcfFc5i9Xp4.run(Unknown Source:2)
        at fr.free.nrw.commons.utils.PermissionUtils$1.onPermissionDenied(PermissionUtils.java:125)
        at com.karumi.dexter.MultiplePermissionsListenerToPermissionListenerAdapter.onPermissionsChecked(Unknown Source:23)
        at com.karumi.dexter.MultiplePermissionListenerThreadDecorator$1.run(Unknown Source:8)
        at com.karumi.dexter.MainThread.execute(Unknown Source:6)
        at com.karumi.dexter.MultiplePermissionListenerThreadDecorator.onPermissionsChecked(Unknown Source:7)
        at com.karumi.dexter.DexterInstance.onPermissionsChecked(Unknown Source:57)
        at com.karumi.dexter.DexterInstance.updatePermissionsAsDenied(Unknown Source:36)
        at com.karumi.dexter.DexterInstance.onPermissionRequestDenied(Unknown Source:0)
        at com.karumi.dexter.Dexter.onPermissionsRequested(Unknown Source:9)
        at com.karumi.dexter.DexterActivity.onRequestPermissionsResult(Unknown Source:51)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8408)
        at android.app.Activity.dispatchActivityResult(Activity.java:8253)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4953)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5001) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7590) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 

```

**Device and Android version:** 
Redmi Note 7S and Android 10.

**Commons app version:** 
3.0.0-debug-master.

**Would you like to work on the issue?**
Yes, I would like to work on this.

**Comment by nicolas-raoul** [comment] 2021-02-23 09:23
Strange, I am not able to reproduce this... I merged a few related pull requests a few hours ago, maybe it had an impact?
What commit number can you reproduce this on?

**Comment by mrudultora** [comment] 2021-02-23 09:35
@nicolas-raoul I didn't added the clear commons-app-verison. This is the one 
**3.0.0-debug-master~88be88f25**

**Comment by mrudultora** [comment] 2021-02-23 09:38
It's hard to reproduce. Just for the sake of screencast I have spent approx. 5 minutes. So, that I can catch the crash during the screen recording. Will you please confirm it. Because the logs generated are valid. On switching frequently, the toast produces but the fragment is not attached.

**Comment by nicolas-raoul** [comment] 2021-02-23 09:46
Thanks! Understood, I will try more :-)

**Comment by mrudultora** [comment] 2021-02-23 10:44
@nicolas-raoul The best way to reproduce it is tap yes on the dialog box from contributors tab and then move immediately to nearby tab and then press deny. The app will crash. Tried this 5 times and app crashed all of the time. Sorry for pinging you again and again.

**Comment by nicolas-raoul** [comment] 2021-02-23 11:21
No problem for the pings! :-)
Actually the pending PR https://github.com/commons-app/apps-android-commons/pull/4259 (soon to be merged after style changes) modifies how this permission is asked. Let's wait until that PR is merged, probably tomorrow.

**Comment by mrudultora** [comment] 2021-02-23 11:28
Sure ;-)

**Comment by Rishavgupta12345** [comment] 2022-03-07 06:34
@nicolas-raoul @4D17Y4 this issue is not reproducible any more and so we can close this

**Comment by nicolas-raoul** [comment] 2022-03-07 09:39
I will close this for now, but if anyone manages to reproduce on the latest version, please reopen, thanks!

**Closed by nicolas-raoul** 2022-03-07 09:39 UTC
