### ISSUE TITLE
In depictions selection screen, suggest recently selected items

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3634] opened 2020-04-09 14:21 UTC
For now, the depictions selection screen does not show anything when no search string is entered.
Instead, it would be good if it could suggest:
- Items that were selected during previous uploads.

This feature exists in the category selection activity, so that activity can be studied for inspiration.

**Comment by johnnyrev** [comment] 2020-04-11 08:27
Can it be assigned to me?

**Comment by johnnyrev** [comment] 2020-04-11 09:04
If I get it straight, this is for step 2 of "upload" search. If so, you want the items shown with checkboxes, as they are in step 3, or with their depictions and descriptions?

**Comment by nicolas-raoul** [comment] 2020-04-11 15:18
Yes, this screen:
![Screenshot_20200411-183347_Commons](https://user-images.githubusercontent.com/99590/79047657-ff438900-7c52-11ea-800d-b3f463362851.jpg)
It should show for instance the last 10 chosen items. If possible implement like done in categories, for consistency. Thanks!

**Comment by macgills** [comment] 2020-04-15 13:38
This functionality has been broken for contributions since 13/06/19, partially fixed in #3650

If somebody could tell me what 
```
    private boolean hasDirectCategories() {
        return !directKvStore.getString("Category", "").equals("");
    }
```
a "direct category" is then that would help, as far as I can tell nobody ever writes anything to this preference. @maskaravivek 

@johnnyrev a new Room Dao will have to be added so that when a user selects a depiction we save that to the database. When search term is empty we, if following the example of category model, would take the 25 most recently selected from the database to show them in a list.

There is however a lingering question of precedence for me, do we show items from nearby locations first here or recently selected items first. @nicolas-raoul

**Comment by nicolas-raoul** [comment] 2020-04-17 23:37
My guess would be that "direct" was related to campaigns, and thus can be removed as the campaigns feature was removed years ago.

I would put nearby items before recent items.

**Comment by macgills** [comment] 2020-04-21 09:40
@nicolas-raoul apologies for going off topic here but campaigns have been removed?

![image](https://user-images.githubusercontent.com/3358282/79850787-51577d80-83bc-11ea-9ba7-00190f4497e6.png)

This is only on beta but it looks like the feature is still very much there. Can we remove it? @misaochan

**Comment by nicolas-raoul** [comment] 2020-04-21 12:00
Sorry I was referring to a different feature which tagged all uploads using
a particular category such as "Wiki Loves Earth 2011"

The campaign message is to be kept 🙂

**Comment by macgills** [comment] 2020-04-21 12:03
Thanks for the info @nicolas-raoul 

@johnnyrev are you still working on this? I have availability as I think I have already commented on another of your tickets

**Comment by johnnyrev** [comment] 2020-04-24 08:03
@macgills Actually me and @dafnith have started working on that and we want to totally reproduce it. Thanks for asking, but we can’t give it away!

**Comment by sivaraam** [comment] 2020-04-24 19:10
@johnnyrev It's good to know that you and @dafnith are working on this. I just wanted to let you know that in case you feel stuck somewhere, feel free to ask for help here :)

**Comment by johnnyrev** [comment] 2020-04-24 19:16
@sivaraam Thanks a lot, we appreciate it!

**Comment by dafnith** [comment] 2020-05-17 14:41
It seems that in the category selection screen does not show anything when no search string is entered. It shows a red message that there are no results.  I tried to upload a picture multiple times and somehow it worked. When I tried again the red message appeared again. Is this normal?

I am also wondering what do you mean by "Items that were selected **during previous uploads**."
Previous uploads of the current user or just the uploads that have been made in general?

**Comment by nicolas-raoul** [comment] 2020-05-17 22:33
@dafnith We merged Structured Commons work into the master branch and fixed a few bugs. Please git pull, git switch master, rebuild and test again, if you still see the red message please post a screenshot here. "previous uploads" refers to the images that _the user_ has recently uploaded. I encourage you to check the category selection screen and see how it works :-)

**Comment by dafnith** [comment] 2020-05-19 10:41
@nicolas-raoul Thank you for your response!
As for the implementation we are thinking of creating the Room Dao that @macgills mentioned and name it DepictionsDAO.java. We are going to follow the steps in which CategoriesDAO is made.
If our way is correct then in which branch we are supposed to write the code?

**Comment by nicolas-raoul** [comment] 2020-05-19 11:07
@dafnith Please create a new branch (named for instance `3634-suggest-recently-selected-items`) on the latest master. Thanks!

**Comment by dafnith** [comment] 2020-05-19 11:16
@nicolas-raoul Thank you!
I would also be happy if you could explain the purpose of the structured-data branch and when should I switch at it thought..

**Comment by macgills** [comment] 2020-05-19 12:40
Structured data was a branch where Depictions(multilingual captions/descriptions) were implemented, it has been merged to master for a good few weeks now

**Comment by dafnith** [comment] 2020-06-13 13:05
@sivaraam we actually got stuck trying to save the selected depictions in the database. Our method that inserts recent depictions in recent_depictions table uses a list with RecentDepictions objects.
``` 
  public Single<List<Long>> save(List<RecentDepictions> recentDepictions) {
    return localDataSource.saveRecentDepictions(recentDepictions);
  }
```
We want to call this method from UploadModel.java file but we don't know how to convert the DepictedItem object to RecentDepictions object
``` 
    public void onDepictItemClicked(DepictedItem depictedItem) {
        if (depictedItem.isSelected()) {
            selectedDepictions.add(depictedItem);
        } else {
            selectedDepictions.remove(depictedItem);
        }
    }
```

**Comment by sivaraam** [comment] 2020-06-19 09:13
I think you should be persisting the `DepictedItem` objects of the recently used depictions rather than creating a new class `RecentDepictions. You could see this being done for Categories too.

From `CategoriesModel.kt`:
```kotlin
    fun updateCategoryCount(item: CategoryItem) {
        var category = categoryDao.find(item.name)

        // Newly used category...
        if (category == null) {
            category = Category(null, item.name, Date(), 0)
        }
        category.incTimesUsed()
        categoryDao.save(category) // Note how the Category object itself is saved here
    }
```

Others could comment better about this.

PS: You're more likely to get a faster response when you don't ping specific people :)

**Comment by macgills** [comment] 2020-06-19 10:20
We specifically don't want to use DepictedItems. It is generally good practice to have separate models for different domains of your application and this illustrates that well.

Were we to save DepictedItems, if we follow the example of Category, we would need to add
```
    private Date lastUsed;
```

to the DepictedItems and this would pollute that class as these fields only matter in the database layer of our application, ie nobody else cares about `lastUsed`. a reasonable way to approach this problem is composition

```
data class RecentDepictedItem(item:DepictedItem, lastUsed:Date)
```


`Category` is all around a really bad example, unused fields, legacy contentProvider associated and its name is misleading as unfortunately we don't Type our categories and instead just use Strings when we get them from the API. This problem is likely because of this class stealing the namespace of `Category`  from the application whereas were it `RecentCategory` it would be far more accurately named and not make this sentence heavily confusing when I switch from talking about a `Category` to the categories

**Comment by johnnyrev** [comment] 2020-07-14 17:54
Excuse me for this delayed comment, but due to some problems with the implementation process and the restricted time that we have this period of time, me and @dafnith aren't able to keep up with this issue. So, feel free to assign this issue to someone who is able to spend more time and get this thing done.

By the way thanks for all the information and help that you gave us. It was a very good experience working with you!

Our excuses again!

**Comment by sivaraam** [comment] 2020-07-14 18:28
@johnnyrev Ok. Thanks for letting us know.

**Comment by neslihanturan** [comment] 2021-03-24 08:19
Anyone who is interested with this issue, please make sure you followed previously opened PR  #3771

**Comment by Prince-kushwaha** [comment] 2021-04-14 03:58
@neslihanturan i want to work on this issue

**Comment by nicolas-raoul** [comment] 2021-04-14 05:08
@Prince-kushwaha It is yours, thanks!

**Comment by Prince-kushwaha** [comment] 2021-04-16 05:33
@nicolas-raoul how many max number of recent Selected item i save in Room database

**Comment by nicolas-raoul** [comment] 2021-04-16 07:50
10 should be good. Thanks!

**Comment by Prince-kushwaha** [comment] 2021-04-17 03:19
in room database how delete all element except first 10 element

**Closed** 2021-05-31 10:19 UTC
Labels: enhancement, structured-data
